/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Chem-Vault
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CddProtocolMappingResultResponse,
  CddProtocolSummaryResponse,
  HTTPValidationError,
  ImportCddProtocolApiV1CddImportProtocolsExternalIdPostBody,
  ProtocolResponse
} from '.././model';

import { customInstance } from '.././custom-instance';




/**
 * @summary List Cdd Protocols
 */
export const listCddProtocolsApiV1CddImportProtocolsGet = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<CddProtocolSummaryResponse[]>(
      {url: `/api/v1/cdd-import/protocols`, method: 'GET', signal
    },
      );
    }
  



export const getListCddProtocolsApiV1CddImportProtocolsGetQueryKey = () => {
    return [
    `/api/v1/cdd-import/protocols`
    ] as const;
    }

    
export const getListCddProtocolsApiV1CddImportProtocolsGetQueryOptions = <TData = Awaited<ReturnType<typeof listCddProtocolsApiV1CddImportProtocolsGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCddProtocolsApiV1CddImportProtocolsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListCddProtocolsApiV1CddImportProtocolsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listCddProtocolsApiV1CddImportProtocolsGet>>> = ({ signal }) => listCddProtocolsApiV1CddImportProtocolsGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listCddProtocolsApiV1CddImportProtocolsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListCddProtocolsApiV1CddImportProtocolsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listCddProtocolsApiV1CddImportProtocolsGet>>>
export type ListCddProtocolsApiV1CddImportProtocolsGetQueryError = unknown


export function useListCddProtocolsApiV1CddImportProtocolsGet<TData = Awaited<ReturnType<typeof listCddProtocolsApiV1CddImportProtocolsGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCddProtocolsApiV1CddImportProtocolsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCddProtocolsApiV1CddImportProtocolsGet>>,
          TError,
          Awaited<ReturnType<typeof listCddProtocolsApiV1CddImportProtocolsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListCddProtocolsApiV1CddImportProtocolsGet<TData = Awaited<ReturnType<typeof listCddProtocolsApiV1CddImportProtocolsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCddProtocolsApiV1CddImportProtocolsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCddProtocolsApiV1CddImportProtocolsGet>>,
          TError,
          Awaited<ReturnType<typeof listCddProtocolsApiV1CddImportProtocolsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListCddProtocolsApiV1CddImportProtocolsGet<TData = Awaited<ReturnType<typeof listCddProtocolsApiV1CddImportProtocolsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCddProtocolsApiV1CddImportProtocolsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Cdd Protocols
 */

export function useListCddProtocolsApiV1CddImportProtocolsGet<TData = Awaited<ReturnType<typeof listCddProtocolsApiV1CddImportProtocolsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCddProtocolsApiV1CddImportProtocolsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListCddProtocolsApiV1CddImportProtocolsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Preview Cdd Protocol
 */
export const previewCddProtocolApiV1CddImportProtocolsExternalIdPreviewGet = (
    externalId: number,
 signal?: AbortSignal
) => {
      
      
      return customInstance<CddProtocolMappingResultResponse>(
      {url: `/api/v1/cdd-import/protocols/${externalId}/preview`, method: 'GET', signal
    },
      );
    }
  



export const getPreviewCddProtocolApiV1CddImportProtocolsExternalIdPreviewGetQueryKey = (externalId?: number,) => {
    return [
    `/api/v1/cdd-import/protocols/${externalId}/preview`
    ] as const;
    }

    
export const getPreviewCddProtocolApiV1CddImportProtocolsExternalIdPreviewGetQueryOptions = <TData = Awaited<ReturnType<typeof previewCddProtocolApiV1CddImportProtocolsExternalIdPreviewGet>>, TError = HTTPValidationError>(externalId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previewCddProtocolApiV1CddImportProtocolsExternalIdPreviewGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPreviewCddProtocolApiV1CddImportProtocolsExternalIdPreviewGetQueryKey(externalId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof previewCddProtocolApiV1CddImportProtocolsExternalIdPreviewGet>>> = ({ signal }) => previewCddProtocolApiV1CddImportProtocolsExternalIdPreviewGet(externalId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(externalId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof previewCddProtocolApiV1CddImportProtocolsExternalIdPreviewGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PreviewCddProtocolApiV1CddImportProtocolsExternalIdPreviewGetQueryResult = NonNullable<Awaited<ReturnType<typeof previewCddProtocolApiV1CddImportProtocolsExternalIdPreviewGet>>>
export type PreviewCddProtocolApiV1CddImportProtocolsExternalIdPreviewGetQueryError = HTTPValidationError


export function usePreviewCddProtocolApiV1CddImportProtocolsExternalIdPreviewGet<TData = Awaited<ReturnType<typeof previewCddProtocolApiV1CddImportProtocolsExternalIdPreviewGet>>, TError = HTTPValidationError>(
 externalId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof previewCddProtocolApiV1CddImportProtocolsExternalIdPreviewGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof previewCddProtocolApiV1CddImportProtocolsExternalIdPreviewGet>>,
          TError,
          Awaited<ReturnType<typeof previewCddProtocolApiV1CddImportProtocolsExternalIdPreviewGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePreviewCddProtocolApiV1CddImportProtocolsExternalIdPreviewGet<TData = Awaited<ReturnType<typeof previewCddProtocolApiV1CddImportProtocolsExternalIdPreviewGet>>, TError = HTTPValidationError>(
 externalId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previewCddProtocolApiV1CddImportProtocolsExternalIdPreviewGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof previewCddProtocolApiV1CddImportProtocolsExternalIdPreviewGet>>,
          TError,
          Awaited<ReturnType<typeof previewCddProtocolApiV1CddImportProtocolsExternalIdPreviewGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePreviewCddProtocolApiV1CddImportProtocolsExternalIdPreviewGet<TData = Awaited<ReturnType<typeof previewCddProtocolApiV1CddImportProtocolsExternalIdPreviewGet>>, TError = HTTPValidationError>(
 externalId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previewCddProtocolApiV1CddImportProtocolsExternalIdPreviewGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Preview Cdd Protocol
 */

export function usePreviewCddProtocolApiV1CddImportProtocolsExternalIdPreviewGet<TData = Awaited<ReturnType<typeof previewCddProtocolApiV1CddImportProtocolsExternalIdPreviewGet>>, TError = HTTPValidationError>(
 externalId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previewCddProtocolApiV1CddImportProtocolsExternalIdPreviewGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPreviewCddProtocolApiV1CddImportProtocolsExternalIdPreviewGetQueryOptions(externalId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Import Cdd Protocol
 */
export const importCddProtocolApiV1CddImportProtocolsExternalIdPost = (
    externalId: number,
    importCddProtocolApiV1CddImportProtocolsExternalIdPostBody: ImportCddProtocolApiV1CddImportProtocolsExternalIdPostBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ProtocolResponse>(
      {url: `/api/v1/cdd-import/protocols/${externalId}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: importCddProtocolApiV1CddImportProtocolsExternalIdPostBody, signal
    },
      );
    }
  


export const getImportCddProtocolApiV1CddImportProtocolsExternalIdPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof importCddProtocolApiV1CddImportProtocolsExternalIdPost>>, TError,{externalId: number;data: ImportCddProtocolApiV1CddImportProtocolsExternalIdPostBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof importCddProtocolApiV1CddImportProtocolsExternalIdPost>>, TError,{externalId: number;data: ImportCddProtocolApiV1CddImportProtocolsExternalIdPostBody}, TContext> => {

const mutationKey = ['importCddProtocolApiV1CddImportProtocolsExternalIdPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof importCddProtocolApiV1CddImportProtocolsExternalIdPost>>, {externalId: number;data: ImportCddProtocolApiV1CddImportProtocolsExternalIdPostBody}> = (props) => {
          const {externalId,data} = props ?? {};

          return  importCddProtocolApiV1CddImportProtocolsExternalIdPost(externalId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ImportCddProtocolApiV1CddImportProtocolsExternalIdPostMutationResult = NonNullable<Awaited<ReturnType<typeof importCddProtocolApiV1CddImportProtocolsExternalIdPost>>>
    export type ImportCddProtocolApiV1CddImportProtocolsExternalIdPostMutationBody = ImportCddProtocolApiV1CddImportProtocolsExternalIdPostBody
    export type ImportCddProtocolApiV1CddImportProtocolsExternalIdPostMutationError = HTTPValidationError

    /**
 * @summary Import Cdd Protocol
 */
export const useImportCddProtocolApiV1CddImportProtocolsExternalIdPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof importCddProtocolApiV1CddImportProtocolsExternalIdPost>>, TError,{externalId: number;data: ImportCddProtocolApiV1CddImportProtocolsExternalIdPostBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof importCddProtocolApiV1CddImportProtocolsExternalIdPost>>,
        TError,
        {externalId: number;data: ImportCddProtocolApiV1CddImportProtocolsExternalIdPostBody},
        TContext
      > => {

      const mutationOptions = getImportCddProtocolApiV1CddImportProtocolsExternalIdPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    