/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApproveRequest,
  CellarInterfaceRoutesSampleRequestsFulfillRequest,
  CreateSampleRequestRequest,
  HTTPValidationError,
  ListSampleRequestsApiV1SampleRequestsGetParams,
  RejectRequest,
  SampleRequestResponse,
  UpdateSampleRequestRequest
} from '.././model';

import { customInstance } from '.././custom-instance';




/**
 * @summary Create Sample Request
 */
export const createSampleRequestApiV1SampleRequestsPost = (
    createSampleRequestRequest: CreateSampleRequestRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<SampleRequestResponse>(
      {url: `/api/v1/sample-requests`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createSampleRequestRequest, signal
    },
      );
    }
  


export const getCreateSampleRequestApiV1SampleRequestsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSampleRequestApiV1SampleRequestsPost>>, TError,{data: CreateSampleRequestRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createSampleRequestApiV1SampleRequestsPost>>, TError,{data: CreateSampleRequestRequest}, TContext> => {

const mutationKey = ['createSampleRequestApiV1SampleRequestsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createSampleRequestApiV1SampleRequestsPost>>, {data: CreateSampleRequestRequest}> = (props) => {
          const {data} = props ?? {};

          return  createSampleRequestApiV1SampleRequestsPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateSampleRequestApiV1SampleRequestsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createSampleRequestApiV1SampleRequestsPost>>>
    export type CreateSampleRequestApiV1SampleRequestsPostMutationBody = CreateSampleRequestRequest
    export type CreateSampleRequestApiV1SampleRequestsPostMutationError = HTTPValidationError

    /**
 * @summary Create Sample Request
 */
export const useCreateSampleRequestApiV1SampleRequestsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSampleRequestApiV1SampleRequestsPost>>, TError,{data: CreateSampleRequestRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createSampleRequestApiV1SampleRequestsPost>>,
        TError,
        {data: CreateSampleRequestRequest},
        TContext
      > => {

      const mutationOptions = getCreateSampleRequestApiV1SampleRequestsPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List Sample Requests
 */
export const listSampleRequestsApiV1SampleRequestsGet = (
    params?: ListSampleRequestsApiV1SampleRequestsGetParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<SampleRequestResponse[]>(
      {url: `/api/v1/sample-requests`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getListSampleRequestsApiV1SampleRequestsGetQueryKey = (params?: ListSampleRequestsApiV1SampleRequestsGetParams,) => {
    return [
    `/api/v1/sample-requests`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListSampleRequestsApiV1SampleRequestsGetQueryOptions = <TData = Awaited<ReturnType<typeof listSampleRequestsApiV1SampleRequestsGet>>, TError = HTTPValidationError>(params?: ListSampleRequestsApiV1SampleRequestsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSampleRequestsApiV1SampleRequestsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSampleRequestsApiV1SampleRequestsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSampleRequestsApiV1SampleRequestsGet>>> = ({ signal }) => listSampleRequestsApiV1SampleRequestsGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listSampleRequestsApiV1SampleRequestsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListSampleRequestsApiV1SampleRequestsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listSampleRequestsApiV1SampleRequestsGet>>>
export type ListSampleRequestsApiV1SampleRequestsGetQueryError = HTTPValidationError


export function useListSampleRequestsApiV1SampleRequestsGet<TData = Awaited<ReturnType<typeof listSampleRequestsApiV1SampleRequestsGet>>, TError = HTTPValidationError>(
 params: undefined |  ListSampleRequestsApiV1SampleRequestsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSampleRequestsApiV1SampleRequestsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSampleRequestsApiV1SampleRequestsGet>>,
          TError,
          Awaited<ReturnType<typeof listSampleRequestsApiV1SampleRequestsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSampleRequestsApiV1SampleRequestsGet<TData = Awaited<ReturnType<typeof listSampleRequestsApiV1SampleRequestsGet>>, TError = HTTPValidationError>(
 params?: ListSampleRequestsApiV1SampleRequestsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSampleRequestsApiV1SampleRequestsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSampleRequestsApiV1SampleRequestsGet>>,
          TError,
          Awaited<ReturnType<typeof listSampleRequestsApiV1SampleRequestsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSampleRequestsApiV1SampleRequestsGet<TData = Awaited<ReturnType<typeof listSampleRequestsApiV1SampleRequestsGet>>, TError = HTTPValidationError>(
 params?: ListSampleRequestsApiV1SampleRequestsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSampleRequestsApiV1SampleRequestsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Sample Requests
 */

export function useListSampleRequestsApiV1SampleRequestsGet<TData = Awaited<ReturnType<typeof listSampleRequestsApiV1SampleRequestsGet>>, TError = HTTPValidationError>(
 params?: ListSampleRequestsApiV1SampleRequestsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSampleRequestsApiV1SampleRequestsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListSampleRequestsApiV1SampleRequestsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get Sample Request
 */
export const getSampleRequestApiV1SampleRequestsRequestIdGet = (
    requestId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<SampleRequestResponse>(
      {url: `/api/v1/sample-requests/${requestId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetSampleRequestApiV1SampleRequestsRequestIdGetQueryKey = (requestId?: string,) => {
    return [
    `/api/v1/sample-requests/${requestId}`
    ] as const;
    }

    
export const getGetSampleRequestApiV1SampleRequestsRequestIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getSampleRequestApiV1SampleRequestsRequestIdGet>>, TError = HTTPValidationError>(requestId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSampleRequestApiV1SampleRequestsRequestIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSampleRequestApiV1SampleRequestsRequestIdGetQueryKey(requestId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSampleRequestApiV1SampleRequestsRequestIdGet>>> = ({ signal }) => getSampleRequestApiV1SampleRequestsRequestIdGet(requestId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(requestId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSampleRequestApiV1SampleRequestsRequestIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSampleRequestApiV1SampleRequestsRequestIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getSampleRequestApiV1SampleRequestsRequestIdGet>>>
export type GetSampleRequestApiV1SampleRequestsRequestIdGetQueryError = HTTPValidationError


export function useGetSampleRequestApiV1SampleRequestsRequestIdGet<TData = Awaited<ReturnType<typeof getSampleRequestApiV1SampleRequestsRequestIdGet>>, TError = HTTPValidationError>(
 requestId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSampleRequestApiV1SampleRequestsRequestIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSampleRequestApiV1SampleRequestsRequestIdGet>>,
          TError,
          Awaited<ReturnType<typeof getSampleRequestApiV1SampleRequestsRequestIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSampleRequestApiV1SampleRequestsRequestIdGet<TData = Awaited<ReturnType<typeof getSampleRequestApiV1SampleRequestsRequestIdGet>>, TError = HTTPValidationError>(
 requestId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSampleRequestApiV1SampleRequestsRequestIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSampleRequestApiV1SampleRequestsRequestIdGet>>,
          TError,
          Awaited<ReturnType<typeof getSampleRequestApiV1SampleRequestsRequestIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSampleRequestApiV1SampleRequestsRequestIdGet<TData = Awaited<ReturnType<typeof getSampleRequestApiV1SampleRequestsRequestIdGet>>, TError = HTTPValidationError>(
 requestId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSampleRequestApiV1SampleRequestsRequestIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Sample Request
 */

export function useGetSampleRequestApiV1SampleRequestsRequestIdGet<TData = Awaited<ReturnType<typeof getSampleRequestApiV1SampleRequestsRequestIdGet>>, TError = HTTPValidationError>(
 requestId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSampleRequestApiV1SampleRequestsRequestIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSampleRequestApiV1SampleRequestsRequestIdGetQueryOptions(requestId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update Sample Request
 */
export const updateSampleRequestApiV1SampleRequestsRequestIdPatch = (
    requestId: string,
    updateSampleRequestRequest: UpdateSampleRequestRequest,
 ) => {
      
      
      return customInstance<SampleRequestResponse>(
      {url: `/api/v1/sample-requests/${requestId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateSampleRequestRequest
    },
      );
    }
  


export const getUpdateSampleRequestApiV1SampleRequestsRequestIdPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSampleRequestApiV1SampleRequestsRequestIdPatch>>, TError,{requestId: string;data: UpdateSampleRequestRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateSampleRequestApiV1SampleRequestsRequestIdPatch>>, TError,{requestId: string;data: UpdateSampleRequestRequest}, TContext> => {

const mutationKey = ['updateSampleRequestApiV1SampleRequestsRequestIdPatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateSampleRequestApiV1SampleRequestsRequestIdPatch>>, {requestId: string;data: UpdateSampleRequestRequest}> = (props) => {
          const {requestId,data} = props ?? {};

          return  updateSampleRequestApiV1SampleRequestsRequestIdPatch(requestId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateSampleRequestApiV1SampleRequestsRequestIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateSampleRequestApiV1SampleRequestsRequestIdPatch>>>
    export type UpdateSampleRequestApiV1SampleRequestsRequestIdPatchMutationBody = UpdateSampleRequestRequest
    export type UpdateSampleRequestApiV1SampleRequestsRequestIdPatchMutationError = HTTPValidationError

    /**
 * @summary Update Sample Request
 */
export const useUpdateSampleRequestApiV1SampleRequestsRequestIdPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSampleRequestApiV1SampleRequestsRequestIdPatch>>, TError,{requestId: string;data: UpdateSampleRequestRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateSampleRequestApiV1SampleRequestsRequestIdPatch>>,
        TError,
        {requestId: string;data: UpdateSampleRequestRequest},
        TContext
      > => {

      const mutationOptions = getUpdateSampleRequestApiV1SampleRequestsRequestIdPatchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Approve Sample Request
 */
export const approveSampleRequestApiV1SampleRequestsRequestIdApprovePost = (
    requestId: string,
    approveRequest: ApproveRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<SampleRequestResponse>(
      {url: `/api/v1/sample-requests/${requestId}/approve`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: approveRequest, signal
    },
      );
    }
  


export const getApproveSampleRequestApiV1SampleRequestsRequestIdApprovePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof approveSampleRequestApiV1SampleRequestsRequestIdApprovePost>>, TError,{requestId: string;data: ApproveRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof approveSampleRequestApiV1SampleRequestsRequestIdApprovePost>>, TError,{requestId: string;data: ApproveRequest}, TContext> => {

const mutationKey = ['approveSampleRequestApiV1SampleRequestsRequestIdApprovePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof approveSampleRequestApiV1SampleRequestsRequestIdApprovePost>>, {requestId: string;data: ApproveRequest}> = (props) => {
          const {requestId,data} = props ?? {};

          return  approveSampleRequestApiV1SampleRequestsRequestIdApprovePost(requestId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ApproveSampleRequestApiV1SampleRequestsRequestIdApprovePostMutationResult = NonNullable<Awaited<ReturnType<typeof approveSampleRequestApiV1SampleRequestsRequestIdApprovePost>>>
    export type ApproveSampleRequestApiV1SampleRequestsRequestIdApprovePostMutationBody = ApproveRequest
    export type ApproveSampleRequestApiV1SampleRequestsRequestIdApprovePostMutationError = HTTPValidationError

    /**
 * @summary Approve Sample Request
 */
export const useApproveSampleRequestApiV1SampleRequestsRequestIdApprovePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof approveSampleRequestApiV1SampleRequestsRequestIdApprovePost>>, TError,{requestId: string;data: ApproveRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof approveSampleRequestApiV1SampleRequestsRequestIdApprovePost>>,
        TError,
        {requestId: string;data: ApproveRequest},
        TContext
      > => {

      const mutationOptions = getApproveSampleRequestApiV1SampleRequestsRequestIdApprovePostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Reject Sample Request
 */
export const rejectSampleRequestApiV1SampleRequestsRequestIdRejectPost = (
    requestId: string,
    rejectRequest: RejectRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<SampleRequestResponse>(
      {url: `/api/v1/sample-requests/${requestId}/reject`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: rejectRequest, signal
    },
      );
    }
  


export const getRejectSampleRequestApiV1SampleRequestsRequestIdRejectPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rejectSampleRequestApiV1SampleRequestsRequestIdRejectPost>>, TError,{requestId: string;data: RejectRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof rejectSampleRequestApiV1SampleRequestsRequestIdRejectPost>>, TError,{requestId: string;data: RejectRequest}, TContext> => {

const mutationKey = ['rejectSampleRequestApiV1SampleRequestsRequestIdRejectPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof rejectSampleRequestApiV1SampleRequestsRequestIdRejectPost>>, {requestId: string;data: RejectRequest}> = (props) => {
          const {requestId,data} = props ?? {};

          return  rejectSampleRequestApiV1SampleRequestsRequestIdRejectPost(requestId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RejectSampleRequestApiV1SampleRequestsRequestIdRejectPostMutationResult = NonNullable<Awaited<ReturnType<typeof rejectSampleRequestApiV1SampleRequestsRequestIdRejectPost>>>
    export type RejectSampleRequestApiV1SampleRequestsRequestIdRejectPostMutationBody = RejectRequest
    export type RejectSampleRequestApiV1SampleRequestsRequestIdRejectPostMutationError = HTTPValidationError

    /**
 * @summary Reject Sample Request
 */
export const useRejectSampleRequestApiV1SampleRequestsRequestIdRejectPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rejectSampleRequestApiV1SampleRequestsRequestIdRejectPost>>, TError,{requestId: string;data: RejectRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof rejectSampleRequestApiV1SampleRequestsRequestIdRejectPost>>,
        TError,
        {requestId: string;data: RejectRequest},
        TContext
      > => {

      const mutationOptions = getRejectSampleRequestApiV1SampleRequestsRequestIdRejectPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Start Preparing Sample Request
 */
export const startPreparingSampleRequestApiV1SampleRequestsRequestIdPreparePost = (
    requestId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<SampleRequestResponse>(
      {url: `/api/v1/sample-requests/${requestId}/prepare`, method: 'POST', signal
    },
      );
    }
  


export const getStartPreparingSampleRequestApiV1SampleRequestsRequestIdPreparePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startPreparingSampleRequestApiV1SampleRequestsRequestIdPreparePost>>, TError,{requestId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof startPreparingSampleRequestApiV1SampleRequestsRequestIdPreparePost>>, TError,{requestId: string}, TContext> => {

const mutationKey = ['startPreparingSampleRequestApiV1SampleRequestsRequestIdPreparePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof startPreparingSampleRequestApiV1SampleRequestsRequestIdPreparePost>>, {requestId: string}> = (props) => {
          const {requestId} = props ?? {};

          return  startPreparingSampleRequestApiV1SampleRequestsRequestIdPreparePost(requestId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StartPreparingSampleRequestApiV1SampleRequestsRequestIdPreparePostMutationResult = NonNullable<Awaited<ReturnType<typeof startPreparingSampleRequestApiV1SampleRequestsRequestIdPreparePost>>>
    
    export type StartPreparingSampleRequestApiV1SampleRequestsRequestIdPreparePostMutationError = HTTPValidationError

    /**
 * @summary Start Preparing Sample Request
 */
export const useStartPreparingSampleRequestApiV1SampleRequestsRequestIdPreparePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startPreparingSampleRequestApiV1SampleRequestsRequestIdPreparePost>>, TError,{requestId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof startPreparingSampleRequestApiV1SampleRequestsRequestIdPreparePost>>,
        TError,
        {requestId: string},
        TContext
      > => {

      const mutationOptions = getStartPreparingSampleRequestApiV1SampleRequestsRequestIdPreparePostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Fulfill Sample Request
 */
export const fulfillSampleRequestApiV1SampleRequestsRequestIdFulfillPost = (
    requestId: string,
    cellarInterfaceRoutesSampleRequestsFulfillRequest: CellarInterfaceRoutesSampleRequestsFulfillRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<SampleRequestResponse>(
      {url: `/api/v1/sample-requests/${requestId}/fulfill`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: cellarInterfaceRoutesSampleRequestsFulfillRequest, signal
    },
      );
    }
  


export const getFulfillSampleRequestApiV1SampleRequestsRequestIdFulfillPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof fulfillSampleRequestApiV1SampleRequestsRequestIdFulfillPost>>, TError,{requestId: string;data: CellarInterfaceRoutesSampleRequestsFulfillRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof fulfillSampleRequestApiV1SampleRequestsRequestIdFulfillPost>>, TError,{requestId: string;data: CellarInterfaceRoutesSampleRequestsFulfillRequest}, TContext> => {

const mutationKey = ['fulfillSampleRequestApiV1SampleRequestsRequestIdFulfillPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof fulfillSampleRequestApiV1SampleRequestsRequestIdFulfillPost>>, {requestId: string;data: CellarInterfaceRoutesSampleRequestsFulfillRequest}> = (props) => {
          const {requestId,data} = props ?? {};

          return  fulfillSampleRequestApiV1SampleRequestsRequestIdFulfillPost(requestId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type FulfillSampleRequestApiV1SampleRequestsRequestIdFulfillPostMutationResult = NonNullable<Awaited<ReturnType<typeof fulfillSampleRequestApiV1SampleRequestsRequestIdFulfillPost>>>
    export type FulfillSampleRequestApiV1SampleRequestsRequestIdFulfillPostMutationBody = CellarInterfaceRoutesSampleRequestsFulfillRequest
    export type FulfillSampleRequestApiV1SampleRequestsRequestIdFulfillPostMutationError = HTTPValidationError

    /**
 * @summary Fulfill Sample Request
 */
export const useFulfillSampleRequestApiV1SampleRequestsRequestIdFulfillPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof fulfillSampleRequestApiV1SampleRequestsRequestIdFulfillPost>>, TError,{requestId: string;data: CellarInterfaceRoutesSampleRequestsFulfillRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof fulfillSampleRequestApiV1SampleRequestsRequestIdFulfillPost>>,
        TError,
        {requestId: string;data: CellarInterfaceRoutesSampleRequestsFulfillRequest},
        TContext
      > => {

      const mutationOptions = getFulfillSampleRequestApiV1SampleRequestsRequestIdFulfillPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Cancel Sample Request
 */
export const cancelSampleRequestApiV1SampleRequestsRequestIdCancelPost = (
    requestId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<SampleRequestResponse>(
      {url: `/api/v1/sample-requests/${requestId}/cancel`, method: 'POST', signal
    },
      );
    }
  


export const getCancelSampleRequestApiV1SampleRequestsRequestIdCancelPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelSampleRequestApiV1SampleRequestsRequestIdCancelPost>>, TError,{requestId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof cancelSampleRequestApiV1SampleRequestsRequestIdCancelPost>>, TError,{requestId: string}, TContext> => {

const mutationKey = ['cancelSampleRequestApiV1SampleRequestsRequestIdCancelPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cancelSampleRequestApiV1SampleRequestsRequestIdCancelPost>>, {requestId: string}> = (props) => {
          const {requestId} = props ?? {};

          return  cancelSampleRequestApiV1SampleRequestsRequestIdCancelPost(requestId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CancelSampleRequestApiV1SampleRequestsRequestIdCancelPostMutationResult = NonNullable<Awaited<ReturnType<typeof cancelSampleRequestApiV1SampleRequestsRequestIdCancelPost>>>
    
    export type CancelSampleRequestApiV1SampleRequestsRequestIdCancelPostMutationError = HTTPValidationError

    /**
 * @summary Cancel Sample Request
 */
export const useCancelSampleRequestApiV1SampleRequestsRequestIdCancelPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelSampleRequestApiV1SampleRequestsRequestIdCancelPost>>, TError,{requestId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof cancelSampleRequestApiV1SampleRequestsRequestIdCancelPost>>,
        TError,
        {requestId: string},
        TContext
      > => {

      const mutationOptions = getCancelSampleRequestApiV1SampleRequestsRequestIdCancelPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    