/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Chem-Vault
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CddPlateImportAcceptedResponse,
  CddPlateImportStatusResponse,
  CddPlateImportSummary,
  HTTPValidationError
} from '.././model';

import { customInstance } from '.././custom-instance';




/**
 * @summary List Cdd Plate Imports
 */
export const listCddPlateImportsApiV1CddImportPlatesGet = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<CddPlateImportSummary[]>(
      {url: `/api/v1/cdd-import/plates`, method: 'GET', signal
    },
      );
    }
  



export const getListCddPlateImportsApiV1CddImportPlatesGetQueryKey = () => {
    return [
    `/api/v1/cdd-import/plates`
    ] as const;
    }

    
export const getListCddPlateImportsApiV1CddImportPlatesGetQueryOptions = <TData = Awaited<ReturnType<typeof listCddPlateImportsApiV1CddImportPlatesGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCddPlateImportsApiV1CddImportPlatesGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListCddPlateImportsApiV1CddImportPlatesGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listCddPlateImportsApiV1CddImportPlatesGet>>> = ({ signal }) => listCddPlateImportsApiV1CddImportPlatesGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listCddPlateImportsApiV1CddImportPlatesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListCddPlateImportsApiV1CddImportPlatesGetQueryResult = NonNullable<Awaited<ReturnType<typeof listCddPlateImportsApiV1CddImportPlatesGet>>>
export type ListCddPlateImportsApiV1CddImportPlatesGetQueryError = unknown


export function useListCddPlateImportsApiV1CddImportPlatesGet<TData = Awaited<ReturnType<typeof listCddPlateImportsApiV1CddImportPlatesGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCddPlateImportsApiV1CddImportPlatesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCddPlateImportsApiV1CddImportPlatesGet>>,
          TError,
          Awaited<ReturnType<typeof listCddPlateImportsApiV1CddImportPlatesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListCddPlateImportsApiV1CddImportPlatesGet<TData = Awaited<ReturnType<typeof listCddPlateImportsApiV1CddImportPlatesGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCddPlateImportsApiV1CddImportPlatesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCddPlateImportsApiV1CddImportPlatesGet>>,
          TError,
          Awaited<ReturnType<typeof listCddPlateImportsApiV1CddImportPlatesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListCddPlateImportsApiV1CddImportPlatesGet<TData = Awaited<ReturnType<typeof listCddPlateImportsApiV1CddImportPlatesGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCddPlateImportsApiV1CddImportPlatesGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Cdd Plate Imports
 */

export function useListCddPlateImportsApiV1CddImportPlatesGet<TData = Awaited<ReturnType<typeof listCddPlateImportsApiV1CddImportPlatesGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCddPlateImportsApiV1CddImportPlatesGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListCddPlateImportsApiV1CddImportPlatesGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Start Cdd Plate Import
 */
export const startCddPlateImportApiV1CddImportPlatesPost = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<CddPlateImportAcceptedResponse>(
      {url: `/api/v1/cdd-import/plates`, method: 'POST', signal
    },
      );
    }
  


export const getStartCddPlateImportApiV1CddImportPlatesPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startCddPlateImportApiV1CddImportPlatesPost>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof startCddPlateImportApiV1CddImportPlatesPost>>, TError,void, TContext> => {

const mutationKey = ['startCddPlateImportApiV1CddImportPlatesPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof startCddPlateImportApiV1CddImportPlatesPost>>, void> = () => {
          

          return  startCddPlateImportApiV1CddImportPlatesPost()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StartCddPlateImportApiV1CddImportPlatesPostMutationResult = NonNullable<Awaited<ReturnType<typeof startCddPlateImportApiV1CddImportPlatesPost>>>
    
    export type StartCddPlateImportApiV1CddImportPlatesPostMutationError = unknown

    /**
 * @summary Start Cdd Plate Import
 */
export const useStartCddPlateImportApiV1CddImportPlatesPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startCddPlateImportApiV1CddImportPlatesPost>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof startCddPlateImportApiV1CddImportPlatesPost>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getStartCddPlateImportApiV1CddImportPlatesPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get Cdd Plate Import Status
 */
export const getCddPlateImportStatusApiV1CddImportPlatesWorkflowIdStatusGet = (
    workflowId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<CddPlateImportStatusResponse>(
      {url: `/api/v1/cdd-import/plates/${workflowId}/status`, method: 'GET', signal
    },
      );
    }
  



export const getGetCddPlateImportStatusApiV1CddImportPlatesWorkflowIdStatusGetQueryKey = (workflowId?: string,) => {
    return [
    `/api/v1/cdd-import/plates/${workflowId}/status`
    ] as const;
    }

    
export const getGetCddPlateImportStatusApiV1CddImportPlatesWorkflowIdStatusGetQueryOptions = <TData = Awaited<ReturnType<typeof getCddPlateImportStatusApiV1CddImportPlatesWorkflowIdStatusGet>>, TError = HTTPValidationError>(workflowId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCddPlateImportStatusApiV1CddImportPlatesWorkflowIdStatusGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCddPlateImportStatusApiV1CddImportPlatesWorkflowIdStatusGetQueryKey(workflowId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCddPlateImportStatusApiV1CddImportPlatesWorkflowIdStatusGet>>> = ({ signal }) => getCddPlateImportStatusApiV1CddImportPlatesWorkflowIdStatusGet(workflowId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(workflowId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCddPlateImportStatusApiV1CddImportPlatesWorkflowIdStatusGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCddPlateImportStatusApiV1CddImportPlatesWorkflowIdStatusGetQueryResult = NonNullable<Awaited<ReturnType<typeof getCddPlateImportStatusApiV1CddImportPlatesWorkflowIdStatusGet>>>
export type GetCddPlateImportStatusApiV1CddImportPlatesWorkflowIdStatusGetQueryError = HTTPValidationError


export function useGetCddPlateImportStatusApiV1CddImportPlatesWorkflowIdStatusGet<TData = Awaited<ReturnType<typeof getCddPlateImportStatusApiV1CddImportPlatesWorkflowIdStatusGet>>, TError = HTTPValidationError>(
 workflowId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCddPlateImportStatusApiV1CddImportPlatesWorkflowIdStatusGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCddPlateImportStatusApiV1CddImportPlatesWorkflowIdStatusGet>>,
          TError,
          Awaited<ReturnType<typeof getCddPlateImportStatusApiV1CddImportPlatesWorkflowIdStatusGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCddPlateImportStatusApiV1CddImportPlatesWorkflowIdStatusGet<TData = Awaited<ReturnType<typeof getCddPlateImportStatusApiV1CddImportPlatesWorkflowIdStatusGet>>, TError = HTTPValidationError>(
 workflowId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCddPlateImportStatusApiV1CddImportPlatesWorkflowIdStatusGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCddPlateImportStatusApiV1CddImportPlatesWorkflowIdStatusGet>>,
          TError,
          Awaited<ReturnType<typeof getCddPlateImportStatusApiV1CddImportPlatesWorkflowIdStatusGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCddPlateImportStatusApiV1CddImportPlatesWorkflowIdStatusGet<TData = Awaited<ReturnType<typeof getCddPlateImportStatusApiV1CddImportPlatesWorkflowIdStatusGet>>, TError = HTTPValidationError>(
 workflowId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCddPlateImportStatusApiV1CddImportPlatesWorkflowIdStatusGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Cdd Plate Import Status
 */

export function useGetCddPlateImportStatusApiV1CddImportPlatesWorkflowIdStatusGet<TData = Awaited<ReturnType<typeof getCddPlateImportStatusApiV1CddImportPlatesWorkflowIdStatusGet>>, TError = HTTPValidationError>(
 workflowId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCddPlateImportStatusApiV1CddImportPlatesWorkflowIdStatusGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCddPlateImportStatusApiV1CddImportPlatesWorkflowIdStatusGetQueryOptions(workflowId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Cancel Cdd Plate Import
 */
export const cancelCddPlateImportApiV1CddImportPlatesWorkflowIdCancelPost = (
    workflowId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/cdd-import/plates/${workflowId}/cancel`, method: 'POST', signal
    },
      );
    }
  


export const getCancelCddPlateImportApiV1CddImportPlatesWorkflowIdCancelPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelCddPlateImportApiV1CddImportPlatesWorkflowIdCancelPost>>, TError,{workflowId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof cancelCddPlateImportApiV1CddImportPlatesWorkflowIdCancelPost>>, TError,{workflowId: string}, TContext> => {

const mutationKey = ['cancelCddPlateImportApiV1CddImportPlatesWorkflowIdCancelPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cancelCddPlateImportApiV1CddImportPlatesWorkflowIdCancelPost>>, {workflowId: string}> = (props) => {
          const {workflowId} = props ?? {};

          return  cancelCddPlateImportApiV1CddImportPlatesWorkflowIdCancelPost(workflowId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CancelCddPlateImportApiV1CddImportPlatesWorkflowIdCancelPostMutationResult = NonNullable<Awaited<ReturnType<typeof cancelCddPlateImportApiV1CddImportPlatesWorkflowIdCancelPost>>>
    
    export type CancelCddPlateImportApiV1CddImportPlatesWorkflowIdCancelPostMutationError = HTTPValidationError

    /**
 * @summary Cancel Cdd Plate Import
 */
export const useCancelCddPlateImportApiV1CddImportPlatesWorkflowIdCancelPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelCddPlateImportApiV1CddImportPlatesWorkflowIdCancelPost>>, TError,{workflowId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof cancelCddPlateImportApiV1CddImportPlatesWorkflowIdCancelPost>>,
        TError,
        {workflowId: string},
        TContext
      > => {

      const mutationOptions = getCancelCddPlateImportApiV1CddImportPlatesWorkflowIdCancelPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Force Fail Cdd Plate Import
 */
export const forceFailCddPlateImportApiV1CddImportPlatesImportIdForceFailPost = (
    importId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/cdd-import/plates/${importId}/force-fail`, method: 'POST', signal
    },
      );
    }
  


export const getForceFailCddPlateImportApiV1CddImportPlatesImportIdForceFailPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof forceFailCddPlateImportApiV1CddImportPlatesImportIdForceFailPost>>, TError,{importId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof forceFailCddPlateImportApiV1CddImportPlatesImportIdForceFailPost>>, TError,{importId: string}, TContext> => {

const mutationKey = ['forceFailCddPlateImportApiV1CddImportPlatesImportIdForceFailPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof forceFailCddPlateImportApiV1CddImportPlatesImportIdForceFailPost>>, {importId: string}> = (props) => {
          const {importId} = props ?? {};

          return  forceFailCddPlateImportApiV1CddImportPlatesImportIdForceFailPost(importId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ForceFailCddPlateImportApiV1CddImportPlatesImportIdForceFailPostMutationResult = NonNullable<Awaited<ReturnType<typeof forceFailCddPlateImportApiV1CddImportPlatesImportIdForceFailPost>>>
    
    export type ForceFailCddPlateImportApiV1CddImportPlatesImportIdForceFailPostMutationError = HTTPValidationError

    /**
 * @summary Force Fail Cdd Plate Import
 */
export const useForceFailCddPlateImportApiV1CddImportPlatesImportIdForceFailPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof forceFailCddPlateImportApiV1CddImportPlatesImportIdForceFailPost>>, TError,{importId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof forceFailCddPlateImportApiV1CddImportPlatesImportIdForceFailPost>>,
        TError,
        {importId: string},
        TContext
      > => {

      const mutationOptions = getForceFailCddPlateImportApiV1CddImportPlatesImportIdForceFailPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    