/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Chem-Vault
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  AdminDeleteBody,
  BlockedByDependenciesResponse,
  CascadeDeleteBody,
  CascadeNodeResponse,
  HTTPValidationError
} from '.././model';

import { customInstance } from '.././custom-instance';




/**
 * @summary Admin Hard Delete
 */
export const adminHardDeleteApiV1AdminEntityTypeEntityIdDelete = (
    entityType: string,
    entityId: string,
    adminDeleteBody: AdminDeleteBody,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/admin/${entityType}/${entityId}`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: adminDeleteBody
    },
      );
    }
  


export const getAdminHardDeleteApiV1AdminEntityTypeEntityIdDeleteMutationOptions = <TError = void | BlockedByDependenciesResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminHardDeleteApiV1AdminEntityTypeEntityIdDelete>>, TError,{entityType: string;entityId: string;data: AdminDeleteBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminHardDeleteApiV1AdminEntityTypeEntityIdDelete>>, TError,{entityType: string;entityId: string;data: AdminDeleteBody}, TContext> => {

const mutationKey = ['adminHardDeleteApiV1AdminEntityTypeEntityIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminHardDeleteApiV1AdminEntityTypeEntityIdDelete>>, {entityType: string;entityId: string;data: AdminDeleteBody}> = (props) => {
          const {entityType,entityId,data} = props ?? {};

          return  adminHardDeleteApiV1AdminEntityTypeEntityIdDelete(entityType,entityId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AdminHardDeleteApiV1AdminEntityTypeEntityIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof adminHardDeleteApiV1AdminEntityTypeEntityIdDelete>>>
    export type AdminHardDeleteApiV1AdminEntityTypeEntityIdDeleteMutationBody = AdminDeleteBody
    export type AdminHardDeleteApiV1AdminEntityTypeEntityIdDeleteMutationError = void | BlockedByDependenciesResponse | HTTPValidationError

    /**
 * @summary Admin Hard Delete
 */
export const useAdminHardDeleteApiV1AdminEntityTypeEntityIdDelete = <TError = void | BlockedByDependenciesResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminHardDeleteApiV1AdminEntityTypeEntityIdDelete>>, TError,{entityType: string;entityId: string;data: AdminDeleteBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminHardDeleteApiV1AdminEntityTypeEntityIdDelete>>,
        TError,
        {entityType: string;entityId: string;data: AdminDeleteBody},
        TContext
      > => {

      const mutationOptions = getAdminHardDeleteApiV1AdminEntityTypeEntityIdDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Cascade Preview
 */
export const cascadePreviewApiV1AdminEntityTypeEntityIdCascadePreviewPost = (
    entityType: string,
    entityId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<CascadeNodeResponse>(
      {url: `/api/v1/admin/${entityType}/${entityId}/cascade-preview`, method: 'POST', signal
    },
      );
    }
  


export const getCascadePreviewApiV1AdminEntityTypeEntityIdCascadePreviewPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cascadePreviewApiV1AdminEntityTypeEntityIdCascadePreviewPost>>, TError,{entityType: string;entityId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof cascadePreviewApiV1AdminEntityTypeEntityIdCascadePreviewPost>>, TError,{entityType: string;entityId: string}, TContext> => {

const mutationKey = ['cascadePreviewApiV1AdminEntityTypeEntityIdCascadePreviewPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cascadePreviewApiV1AdminEntityTypeEntityIdCascadePreviewPost>>, {entityType: string;entityId: string}> = (props) => {
          const {entityType,entityId} = props ?? {};

          return  cascadePreviewApiV1AdminEntityTypeEntityIdCascadePreviewPost(entityType,entityId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CascadePreviewApiV1AdminEntityTypeEntityIdCascadePreviewPostMutationResult = NonNullable<Awaited<ReturnType<typeof cascadePreviewApiV1AdminEntityTypeEntityIdCascadePreviewPost>>>
    
    export type CascadePreviewApiV1AdminEntityTypeEntityIdCascadePreviewPostMutationError = HTTPValidationError

    /**
 * @summary Cascade Preview
 */
export const useCascadePreviewApiV1AdminEntityTypeEntityIdCascadePreviewPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cascadePreviewApiV1AdminEntityTypeEntityIdCascadePreviewPost>>, TError,{entityType: string;entityId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof cascadePreviewApiV1AdminEntityTypeEntityIdCascadePreviewPost>>,
        TError,
        {entityType: string;entityId: string},
        TContext
      > => {

      const mutationOptions = getCascadePreviewApiV1AdminEntityTypeEntityIdCascadePreviewPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Cascade Delete
 */
export const cascadeDeleteApiV1AdminEntityTypeEntityIdCascadeDelete = (
    entityType: string,
    entityId: string,
    cascadeDeleteBody: CascadeDeleteBody,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/admin/${entityType}/${entityId}/cascade`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: cascadeDeleteBody
    },
      );
    }
  


export const getCascadeDeleteApiV1AdminEntityTypeEntityIdCascadeDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cascadeDeleteApiV1AdminEntityTypeEntityIdCascadeDelete>>, TError,{entityType: string;entityId: string;data: CascadeDeleteBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof cascadeDeleteApiV1AdminEntityTypeEntityIdCascadeDelete>>, TError,{entityType: string;entityId: string;data: CascadeDeleteBody}, TContext> => {

const mutationKey = ['cascadeDeleteApiV1AdminEntityTypeEntityIdCascadeDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cascadeDeleteApiV1AdminEntityTypeEntityIdCascadeDelete>>, {entityType: string;entityId: string;data: CascadeDeleteBody}> = (props) => {
          const {entityType,entityId,data} = props ?? {};

          return  cascadeDeleteApiV1AdminEntityTypeEntityIdCascadeDelete(entityType,entityId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CascadeDeleteApiV1AdminEntityTypeEntityIdCascadeDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof cascadeDeleteApiV1AdminEntityTypeEntityIdCascadeDelete>>>
    export type CascadeDeleteApiV1AdminEntityTypeEntityIdCascadeDeleteMutationBody = CascadeDeleteBody
    export type CascadeDeleteApiV1AdminEntityTypeEntityIdCascadeDeleteMutationError = HTTPValidationError

    /**
 * @summary Cascade Delete
 */
export const useCascadeDeleteApiV1AdminEntityTypeEntityIdCascadeDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cascadeDeleteApiV1AdminEntityTypeEntityIdCascadeDelete>>, TError,{entityType: string;entityId: string;data: CascadeDeleteBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof cascadeDeleteApiV1AdminEntityTypeEntityIdCascadeDelete>>,
        TError,
        {entityType: string;entityId: string;data: CascadeDeleteBody},
        TContext
      > => {

      const mutationOptions = getCascadeDeleteApiV1AdminEntityTypeEntityIdCascadeDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    