[mypy]
python_version = 3.13
strict = true
plugins = returns.contrib.mypy.returns_plugin
warn_return_any = true
warn_unused_configs = true

[mypy-asyncpg.*]
ignore_missing_imports = true

[mypy-rdkit.*]
ignore_missing_imports = true

[mypy-temporalio.*]
ignore_missing_imports = true

[mypy-lagom.*]
ignore_missing_imports = true
