/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateDataSourceBody,
  DataSourceResponse,
  EntityMappingResponse,
  HTTPValidationError,
  ListDataSourcesApiV1DataSourcesGetParams,
  PaginatedResponseDataSourceResponse,
  UpdateDataSourceBody
} from '.././model';

import { customInstance } from '.././custom-instance';




/**
 * @summary List Data Sources
 */
export const listDataSourcesApiV1DataSourcesGet = (
    params?: ListDataSourcesApiV1DataSourcesGetParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PaginatedResponseDataSourceResponse>(
      {url: `/api/v1/data-sources`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getListDataSourcesApiV1DataSourcesGetQueryKey = (params?: ListDataSourcesApiV1DataSourcesGetParams,) => {
    return [
    `/api/v1/data-sources`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListDataSourcesApiV1DataSourcesGetQueryOptions = <TData = Awaited<ReturnType<typeof listDataSourcesApiV1DataSourcesGet>>, TError = HTTPValidationError>(params?: ListDataSourcesApiV1DataSourcesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDataSourcesApiV1DataSourcesGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListDataSourcesApiV1DataSourcesGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listDataSourcesApiV1DataSourcesGet>>> = ({ signal }) => listDataSourcesApiV1DataSourcesGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listDataSourcesApiV1DataSourcesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListDataSourcesApiV1DataSourcesGetQueryResult = NonNullable<Awaited<ReturnType<typeof listDataSourcesApiV1DataSourcesGet>>>
export type ListDataSourcesApiV1DataSourcesGetQueryError = HTTPValidationError


export function useListDataSourcesApiV1DataSourcesGet<TData = Awaited<ReturnType<typeof listDataSourcesApiV1DataSourcesGet>>, TError = HTTPValidationError>(
 params: undefined |  ListDataSourcesApiV1DataSourcesGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDataSourcesApiV1DataSourcesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDataSourcesApiV1DataSourcesGet>>,
          TError,
          Awaited<ReturnType<typeof listDataSourcesApiV1DataSourcesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDataSourcesApiV1DataSourcesGet<TData = Awaited<ReturnType<typeof listDataSourcesApiV1DataSourcesGet>>, TError = HTTPValidationError>(
 params?: ListDataSourcesApiV1DataSourcesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDataSourcesApiV1DataSourcesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDataSourcesApiV1DataSourcesGet>>,
          TError,
          Awaited<ReturnType<typeof listDataSourcesApiV1DataSourcesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDataSourcesApiV1DataSourcesGet<TData = Awaited<ReturnType<typeof listDataSourcesApiV1DataSourcesGet>>, TError = HTTPValidationError>(
 params?: ListDataSourcesApiV1DataSourcesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDataSourcesApiV1DataSourcesGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Data Sources
 */

export function useListDataSourcesApiV1DataSourcesGet<TData = Awaited<ReturnType<typeof listDataSourcesApiV1DataSourcesGet>>, TError = HTTPValidationError>(
 params?: ListDataSourcesApiV1DataSourcesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDataSourcesApiV1DataSourcesGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListDataSourcesApiV1DataSourcesGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create Data Source
 */
export const createDataSourceApiV1DataSourcesPost = (
    createDataSourceBody: CreateDataSourceBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<DataSourceResponse>(
      {url: `/api/v1/data-sources`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createDataSourceBody, signal
    },
      );
    }
  


export const getCreateDataSourceApiV1DataSourcesPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDataSourceApiV1DataSourcesPost>>, TError,{data: CreateDataSourceBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createDataSourceApiV1DataSourcesPost>>, TError,{data: CreateDataSourceBody}, TContext> => {

const mutationKey = ['createDataSourceApiV1DataSourcesPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createDataSourceApiV1DataSourcesPost>>, {data: CreateDataSourceBody}> = (props) => {
          const {data} = props ?? {};

          return  createDataSourceApiV1DataSourcesPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateDataSourceApiV1DataSourcesPostMutationResult = NonNullable<Awaited<ReturnType<typeof createDataSourceApiV1DataSourcesPost>>>
    export type CreateDataSourceApiV1DataSourcesPostMutationBody = CreateDataSourceBody
    export type CreateDataSourceApiV1DataSourcesPostMutationError = HTTPValidationError

    /**
 * @summary Create Data Source
 */
export const useCreateDataSourceApiV1DataSourcesPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDataSourceApiV1DataSourcesPost>>, TError,{data: CreateDataSourceBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createDataSourceApiV1DataSourcesPost>>,
        TError,
        {data: CreateDataSourceBody},
        TContext
      > => {

      const mutationOptions = getCreateDataSourceApiV1DataSourcesPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Preview default entity mappings for a source type (read-only reference).
 * @summary Get Template
 */
export const getTemplateApiV1DataSourcesTemplatesSourceTypeGet = (
    sourceType: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<EntityMappingResponse[]>(
      {url: `/api/v1/data-sources/templates/${sourceType}`, method: 'GET', signal
    },
      );
    }
  



export const getGetTemplateApiV1DataSourcesTemplatesSourceTypeGetQueryKey = (sourceType?: string,) => {
    return [
    `/api/v1/data-sources/templates/${sourceType}`
    ] as const;
    }

    
export const getGetTemplateApiV1DataSourcesTemplatesSourceTypeGetQueryOptions = <TData = Awaited<ReturnType<typeof getTemplateApiV1DataSourcesTemplatesSourceTypeGet>>, TError = HTTPValidationError>(sourceType: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemplateApiV1DataSourcesTemplatesSourceTypeGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTemplateApiV1DataSourcesTemplatesSourceTypeGetQueryKey(sourceType);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTemplateApiV1DataSourcesTemplatesSourceTypeGet>>> = ({ signal }) => getTemplateApiV1DataSourcesTemplatesSourceTypeGet(sourceType, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(sourceType), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTemplateApiV1DataSourcesTemplatesSourceTypeGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTemplateApiV1DataSourcesTemplatesSourceTypeGetQueryResult = NonNullable<Awaited<ReturnType<typeof getTemplateApiV1DataSourcesTemplatesSourceTypeGet>>>
export type GetTemplateApiV1DataSourcesTemplatesSourceTypeGetQueryError = HTTPValidationError


export function useGetTemplateApiV1DataSourcesTemplatesSourceTypeGet<TData = Awaited<ReturnType<typeof getTemplateApiV1DataSourcesTemplatesSourceTypeGet>>, TError = HTTPValidationError>(
 sourceType: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemplateApiV1DataSourcesTemplatesSourceTypeGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTemplateApiV1DataSourcesTemplatesSourceTypeGet>>,
          TError,
          Awaited<ReturnType<typeof getTemplateApiV1DataSourcesTemplatesSourceTypeGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTemplateApiV1DataSourcesTemplatesSourceTypeGet<TData = Awaited<ReturnType<typeof getTemplateApiV1DataSourcesTemplatesSourceTypeGet>>, TError = HTTPValidationError>(
 sourceType: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemplateApiV1DataSourcesTemplatesSourceTypeGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTemplateApiV1DataSourcesTemplatesSourceTypeGet>>,
          TError,
          Awaited<ReturnType<typeof getTemplateApiV1DataSourcesTemplatesSourceTypeGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTemplateApiV1DataSourcesTemplatesSourceTypeGet<TData = Awaited<ReturnType<typeof getTemplateApiV1DataSourcesTemplatesSourceTypeGet>>, TError = HTTPValidationError>(
 sourceType: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemplateApiV1DataSourcesTemplatesSourceTypeGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Template
 */

export function useGetTemplateApiV1DataSourcesTemplatesSourceTypeGet<TData = Awaited<ReturnType<typeof getTemplateApiV1DataSourcesTemplatesSourceTypeGet>>, TError = HTTPValidationError>(
 sourceType: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemplateApiV1DataSourcesTemplatesSourceTypeGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTemplateApiV1DataSourcesTemplatesSourceTypeGetQueryOptions(sourceType,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get Data Source
 */
export const getDataSourceApiV1DataSourcesDataSourceIdGet = (
    dataSourceId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<DataSourceResponse>(
      {url: `/api/v1/data-sources/${dataSourceId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetDataSourceApiV1DataSourcesDataSourceIdGetQueryKey = (dataSourceId?: string,) => {
    return [
    `/api/v1/data-sources/${dataSourceId}`
    ] as const;
    }

    
export const getGetDataSourceApiV1DataSourcesDataSourceIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getDataSourceApiV1DataSourcesDataSourceIdGet>>, TError = HTTPValidationError>(dataSourceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDataSourceApiV1DataSourcesDataSourceIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDataSourceApiV1DataSourcesDataSourceIdGetQueryKey(dataSourceId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDataSourceApiV1DataSourcesDataSourceIdGet>>> = ({ signal }) => getDataSourceApiV1DataSourcesDataSourceIdGet(dataSourceId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(dataSourceId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDataSourceApiV1DataSourcesDataSourceIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDataSourceApiV1DataSourcesDataSourceIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getDataSourceApiV1DataSourcesDataSourceIdGet>>>
export type GetDataSourceApiV1DataSourcesDataSourceIdGetQueryError = HTTPValidationError


export function useGetDataSourceApiV1DataSourcesDataSourceIdGet<TData = Awaited<ReturnType<typeof getDataSourceApiV1DataSourcesDataSourceIdGet>>, TError = HTTPValidationError>(
 dataSourceId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDataSourceApiV1DataSourcesDataSourceIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDataSourceApiV1DataSourcesDataSourceIdGet>>,
          TError,
          Awaited<ReturnType<typeof getDataSourceApiV1DataSourcesDataSourceIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDataSourceApiV1DataSourcesDataSourceIdGet<TData = Awaited<ReturnType<typeof getDataSourceApiV1DataSourcesDataSourceIdGet>>, TError = HTTPValidationError>(
 dataSourceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDataSourceApiV1DataSourcesDataSourceIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDataSourceApiV1DataSourcesDataSourceIdGet>>,
          TError,
          Awaited<ReturnType<typeof getDataSourceApiV1DataSourcesDataSourceIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDataSourceApiV1DataSourcesDataSourceIdGet<TData = Awaited<ReturnType<typeof getDataSourceApiV1DataSourcesDataSourceIdGet>>, TError = HTTPValidationError>(
 dataSourceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDataSourceApiV1DataSourcesDataSourceIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Data Source
 */

export function useGetDataSourceApiV1DataSourcesDataSourceIdGet<TData = Awaited<ReturnType<typeof getDataSourceApiV1DataSourcesDataSourceIdGet>>, TError = HTTPValidationError>(
 dataSourceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDataSourceApiV1DataSourcesDataSourceIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDataSourceApiV1DataSourcesDataSourceIdGetQueryOptions(dataSourceId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update Data Source
 */
export const updateDataSourceApiV1DataSourcesDataSourceIdPatch = (
    dataSourceId: string,
    updateDataSourceBody: UpdateDataSourceBody,
 ) => {
      
      
      return customInstance<DataSourceResponse>(
      {url: `/api/v1/data-sources/${dataSourceId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateDataSourceBody
    },
      );
    }
  


export const getUpdateDataSourceApiV1DataSourcesDataSourceIdPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDataSourceApiV1DataSourcesDataSourceIdPatch>>, TError,{dataSourceId: string;data: UpdateDataSourceBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateDataSourceApiV1DataSourcesDataSourceIdPatch>>, TError,{dataSourceId: string;data: UpdateDataSourceBody}, TContext> => {

const mutationKey = ['updateDataSourceApiV1DataSourcesDataSourceIdPatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateDataSourceApiV1DataSourcesDataSourceIdPatch>>, {dataSourceId: string;data: UpdateDataSourceBody}> = (props) => {
          const {dataSourceId,data} = props ?? {};

          return  updateDataSourceApiV1DataSourcesDataSourceIdPatch(dataSourceId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateDataSourceApiV1DataSourcesDataSourceIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateDataSourceApiV1DataSourcesDataSourceIdPatch>>>
    export type UpdateDataSourceApiV1DataSourcesDataSourceIdPatchMutationBody = UpdateDataSourceBody
    export type UpdateDataSourceApiV1DataSourcesDataSourceIdPatchMutationError = HTTPValidationError

    /**
 * @summary Update Data Source
 */
export const useUpdateDataSourceApiV1DataSourcesDataSourceIdPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDataSourceApiV1DataSourcesDataSourceIdPatch>>, TError,{dataSourceId: string;data: UpdateDataSourceBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateDataSourceApiV1DataSourcesDataSourceIdPatch>>,
        TError,
        {dataSourceId: string;data: UpdateDataSourceBody},
        TContext
      > => {

      const mutationOptions = getUpdateDataSourceApiV1DataSourcesDataSourceIdPatchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Delete Data Source
 */
export const deleteDataSourceApiV1DataSourcesDataSourceIdDelete = (
    dataSourceId: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/data-sources/${dataSourceId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteDataSourceApiV1DataSourcesDataSourceIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDataSourceApiV1DataSourcesDataSourceIdDelete>>, TError,{dataSourceId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteDataSourceApiV1DataSourcesDataSourceIdDelete>>, TError,{dataSourceId: string}, TContext> => {

const mutationKey = ['deleteDataSourceApiV1DataSourcesDataSourceIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteDataSourceApiV1DataSourcesDataSourceIdDelete>>, {dataSourceId: string}> = (props) => {
          const {dataSourceId} = props ?? {};

          return  deleteDataSourceApiV1DataSourcesDataSourceIdDelete(dataSourceId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteDataSourceApiV1DataSourcesDataSourceIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteDataSourceApiV1DataSourcesDataSourceIdDelete>>>
    
    export type DeleteDataSourceApiV1DataSourcesDataSourceIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Data Source
 */
export const useDeleteDataSourceApiV1DataSourcesDataSourceIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDataSourceApiV1DataSourcesDataSourceIdDelete>>, TError,{dataSourceId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteDataSourceApiV1DataSourcesDataSourceIdDelete>>,
        TError,
        {dataSourceId: string},
        TContext
      > => {

      const mutationOptions = getDeleteDataSourceApiV1DataSourcesDataSourceIdDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    