"use client";

import { Skeleton } from "@/shared/components/ui/skeleton";
import { getRDKit } from "@/shared/lib/rdkit/rdkit-loader";
import { cn } from "@/shared/lib/utils";
import { memo, useEffect, useState } from "react";

interface StructureRendererProps {
  /** SMILES or CXSMILES string */
  smiles: string;
  /** SVG width in pixels */
  width?: number;
  /** SVG height in pixels */
  height?: number;
  /** Optional SMARTS pattern to highlight matching atoms/bonds */
  highlightSmarts?: string;
  /** Additional CSS class */
  className?: string;
}

/**
 * Renders a 2D chemical structure from SMILES using RDKit.js (WASM).
 *
 * Uses SVG blob URLs to avoid innerHTML. The SVG is generated by the trusted
 * RDKit.js WASM library from a parsed molecular graph.
 */
function StructureRendererInner({
  smiles,
  width = 300,
  height = 200,
  highlightSmarts,
  className,
}: StructureRendererProps) {
  const [blobUrl, setBlobUrl] = useState<string | null>(null);
  const [error, setError] = useState(false);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let cancelled = false;
    let url: string | null = null;

    (async () => {
      try {
        setLoading(true);
        setError(false);

        const rdkit = await getRDKit();
        if (cancelled) return;

        const mol = rdkit.get_mol(smiles);
        if (!mol || !mol.is_valid()) {
          mol?.delete();
          setError(true);
          setLoading(false);
          return;
        }

        let svgStr: string;

        if (highlightSmarts) {
          const qmol = rdkit.get_qmol(highlightSmarts);
          if (qmol?.is_valid()) {
            const matchJson = mol.get_substruct_match(qmol);
            svgStr = mol.get_svg_with_highlights(matchJson);
            qmol.delete();
          } else {
            svgStr = mol.get_svg(width, height);
            qmol?.delete();
          }
        } else {
          svgStr = mol.get_svg(width, height);
        }

        mol.delete();

        if (!cancelled) {
          const blob = new Blob([svgStr], { type: "image/svg+xml" });
          url = URL.createObjectURL(blob);
          setBlobUrl(url);
          setLoading(false);
        }
      } catch {
        if (!cancelled) {
          setError(true);
          setLoading(false);
        }
      }
    })();

    return () => {
      cancelled = true;
      if (url) URL.revokeObjectURL(url);
    };
  }, [smiles, width, height, highlightSmarts]);

  if (loading) {
    return <Skeleton className={className} style={{ width, height }} />;
  }

  if (error || !blobUrl) {
    return (
      <div
        className={cn(
          "flex items-center justify-center rounded border border-dashed text-xs text-muted-foreground",
          className,
        )}
        style={{ width, height }}
      >
        Invalid structure
      </div>
    );
  }

  return (
    <img
      src={blobUrl}
      alt={`Structure: ${smiles}`}
      width={width}
      height={height}
      className={cn("dark:invert", className)}
    />
  );
}

export const StructureRenderer = memo(StructureRendererInner);
