/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 1.3.0-17-gd9da37bb-dirty
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateProtocolCategoryBody,
  HTTPValidationError,
  ProtocolCategoryResponse,
  UpdateProtocolCategoryBody
} from '.././model';

import { customInstance } from '.././custom-instance';




/**
 * @summary List Protocol Categories
 */
export const listProtocolCategoriesApiV1ProtocolCategoriesGet = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<ProtocolCategoryResponse[]>(
      {url: `/api/v1/protocol-categories`, method: 'GET', signal
    },
      );
    }
  



export const getListProtocolCategoriesApiV1ProtocolCategoriesGetQueryKey = () => {
    return [
    `/api/v1/protocol-categories`
    ] as const;
    }

    
export const getListProtocolCategoriesApiV1ProtocolCategoriesGetQueryOptions = <TData = Awaited<ReturnType<typeof listProtocolCategoriesApiV1ProtocolCategoriesGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProtocolCategoriesApiV1ProtocolCategoriesGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListProtocolCategoriesApiV1ProtocolCategoriesGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listProtocolCategoriesApiV1ProtocolCategoriesGet>>> = ({ signal }) => listProtocolCategoriesApiV1ProtocolCategoriesGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listProtocolCategoriesApiV1ProtocolCategoriesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListProtocolCategoriesApiV1ProtocolCategoriesGetQueryResult = NonNullable<Awaited<ReturnType<typeof listProtocolCategoriesApiV1ProtocolCategoriesGet>>>
export type ListProtocolCategoriesApiV1ProtocolCategoriesGetQueryError = unknown


export function useListProtocolCategoriesApiV1ProtocolCategoriesGet<TData = Awaited<ReturnType<typeof listProtocolCategoriesApiV1ProtocolCategoriesGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProtocolCategoriesApiV1ProtocolCategoriesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listProtocolCategoriesApiV1ProtocolCategoriesGet>>,
          TError,
          Awaited<ReturnType<typeof listProtocolCategoriesApiV1ProtocolCategoriesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListProtocolCategoriesApiV1ProtocolCategoriesGet<TData = Awaited<ReturnType<typeof listProtocolCategoriesApiV1ProtocolCategoriesGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProtocolCategoriesApiV1ProtocolCategoriesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listProtocolCategoriesApiV1ProtocolCategoriesGet>>,
          TError,
          Awaited<ReturnType<typeof listProtocolCategoriesApiV1ProtocolCategoriesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListProtocolCategoriesApiV1ProtocolCategoriesGet<TData = Awaited<ReturnType<typeof listProtocolCategoriesApiV1ProtocolCategoriesGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProtocolCategoriesApiV1ProtocolCategoriesGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Protocol Categories
 */

export function useListProtocolCategoriesApiV1ProtocolCategoriesGet<TData = Awaited<ReturnType<typeof listProtocolCategoriesApiV1ProtocolCategoriesGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProtocolCategoriesApiV1ProtocolCategoriesGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListProtocolCategoriesApiV1ProtocolCategoriesGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create Protocol Category
 */
export const createProtocolCategoryApiV1ProtocolCategoriesPost = (
    createProtocolCategoryBody: CreateProtocolCategoryBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ProtocolCategoryResponse>(
      {url: `/api/v1/protocol-categories`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createProtocolCategoryBody, signal
    },
      );
    }
  


export const getCreateProtocolCategoryApiV1ProtocolCategoriesPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProtocolCategoryApiV1ProtocolCategoriesPost>>, TError,{data: CreateProtocolCategoryBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createProtocolCategoryApiV1ProtocolCategoriesPost>>, TError,{data: CreateProtocolCategoryBody}, TContext> => {

const mutationKey = ['createProtocolCategoryApiV1ProtocolCategoriesPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProtocolCategoryApiV1ProtocolCategoriesPost>>, {data: CreateProtocolCategoryBody}> = (props) => {
          const {data} = props ?? {};

          return  createProtocolCategoryApiV1ProtocolCategoriesPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateProtocolCategoryApiV1ProtocolCategoriesPostMutationResult = NonNullable<Awaited<ReturnType<typeof createProtocolCategoryApiV1ProtocolCategoriesPost>>>
    export type CreateProtocolCategoryApiV1ProtocolCategoriesPostMutationBody = CreateProtocolCategoryBody
    export type CreateProtocolCategoryApiV1ProtocolCategoriesPostMutationError = HTTPValidationError

    /**
 * @summary Create Protocol Category
 */
export const useCreateProtocolCategoryApiV1ProtocolCategoriesPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProtocolCategoryApiV1ProtocolCategoriesPost>>, TError,{data: CreateProtocolCategoryBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createProtocolCategoryApiV1ProtocolCategoriesPost>>,
        TError,
        {data: CreateProtocolCategoryBody},
        TContext
      > => {

      const mutationOptions = getCreateProtocolCategoryApiV1ProtocolCategoriesPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Add every shipped default category the workspace lacks (existing ones untouched).
 * @summary Seed Default Protocol Categories
 */
export const seedDefaultProtocolCategoriesApiV1ProtocolCategoriesDefaultsPost = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<ProtocolCategoryResponse[]>(
      {url: `/api/v1/protocol-categories/defaults`, method: 'POST', signal
    },
      );
    }
  


export const getSeedDefaultProtocolCategoriesApiV1ProtocolCategoriesDefaultsPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof seedDefaultProtocolCategoriesApiV1ProtocolCategoriesDefaultsPost>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof seedDefaultProtocolCategoriesApiV1ProtocolCategoriesDefaultsPost>>, TError,void, TContext> => {

const mutationKey = ['seedDefaultProtocolCategoriesApiV1ProtocolCategoriesDefaultsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof seedDefaultProtocolCategoriesApiV1ProtocolCategoriesDefaultsPost>>, void> = () => {
          

          return  seedDefaultProtocolCategoriesApiV1ProtocolCategoriesDefaultsPost()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SeedDefaultProtocolCategoriesApiV1ProtocolCategoriesDefaultsPostMutationResult = NonNullable<Awaited<ReturnType<typeof seedDefaultProtocolCategoriesApiV1ProtocolCategoriesDefaultsPost>>>
    
    export type SeedDefaultProtocolCategoriesApiV1ProtocolCategoriesDefaultsPostMutationError = unknown

    /**
 * @summary Seed Default Protocol Categories
 */
export const useSeedDefaultProtocolCategoriesApiV1ProtocolCategoriesDefaultsPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof seedDefaultProtocolCategoriesApiV1ProtocolCategoriesDefaultsPost>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof seedDefaultProtocolCategoriesApiV1ProtocolCategoriesDefaultsPost>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getSeedDefaultProtocolCategoriesApiV1ProtocolCategoriesDefaultsPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Update Protocol Category
 */
export const updateProtocolCategoryApiV1ProtocolCategoriesCategoryIdPatch = (
    categoryId: string,
    updateProtocolCategoryBody: UpdateProtocolCategoryBody,
 ) => {
      
      
      return customInstance<ProtocolCategoryResponse>(
      {url: `/api/v1/protocol-categories/${categoryId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateProtocolCategoryBody
    },
      );
    }
  


export const getUpdateProtocolCategoryApiV1ProtocolCategoriesCategoryIdPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProtocolCategoryApiV1ProtocolCategoriesCategoryIdPatch>>, TError,{categoryId: string;data: UpdateProtocolCategoryBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateProtocolCategoryApiV1ProtocolCategoriesCategoryIdPatch>>, TError,{categoryId: string;data: UpdateProtocolCategoryBody}, TContext> => {

const mutationKey = ['updateProtocolCategoryApiV1ProtocolCategoriesCategoryIdPatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateProtocolCategoryApiV1ProtocolCategoriesCategoryIdPatch>>, {categoryId: string;data: UpdateProtocolCategoryBody}> = (props) => {
          const {categoryId,data} = props ?? {};

          return  updateProtocolCategoryApiV1ProtocolCategoriesCategoryIdPatch(categoryId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateProtocolCategoryApiV1ProtocolCategoriesCategoryIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateProtocolCategoryApiV1ProtocolCategoriesCategoryIdPatch>>>
    export type UpdateProtocolCategoryApiV1ProtocolCategoriesCategoryIdPatchMutationBody = UpdateProtocolCategoryBody
    export type UpdateProtocolCategoryApiV1ProtocolCategoriesCategoryIdPatchMutationError = HTTPValidationError

    /**
 * @summary Update Protocol Category
 */
export const useUpdateProtocolCategoryApiV1ProtocolCategoriesCategoryIdPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProtocolCategoryApiV1ProtocolCategoriesCategoryIdPatch>>, TError,{categoryId: string;data: UpdateProtocolCategoryBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateProtocolCategoryApiV1ProtocolCategoriesCategoryIdPatch>>,
        TError,
        {categoryId: string;data: UpdateProtocolCategoryBody},
        TContext
      > => {

      const mutationOptions = getUpdateProtocolCategoryApiV1ProtocolCategoriesCategoryIdPatchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Delete Protocol Category
 */
export const deleteProtocolCategoryApiV1ProtocolCategoriesCategoryIdDelete = (
    categoryId: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/protocol-categories/${categoryId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteProtocolCategoryApiV1ProtocolCategoriesCategoryIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProtocolCategoryApiV1ProtocolCategoriesCategoryIdDelete>>, TError,{categoryId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteProtocolCategoryApiV1ProtocolCategoriesCategoryIdDelete>>, TError,{categoryId: string}, TContext> => {

const mutationKey = ['deleteProtocolCategoryApiV1ProtocolCategoriesCategoryIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteProtocolCategoryApiV1ProtocolCategoriesCategoryIdDelete>>, {categoryId: string}> = (props) => {
          const {categoryId} = props ?? {};

          return  deleteProtocolCategoryApiV1ProtocolCategoriesCategoryIdDelete(categoryId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteProtocolCategoryApiV1ProtocolCategoriesCategoryIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteProtocolCategoryApiV1ProtocolCategoriesCategoryIdDelete>>>
    
    export type DeleteProtocolCategoryApiV1ProtocolCategoriesCategoryIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Protocol Category
 */
export const useDeleteProtocolCategoryApiV1ProtocolCategoriesCategoryIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProtocolCategoryApiV1ProtocolCategoriesCategoryIdDelete>>, TError,{categoryId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteProtocolCategoryApiV1ProtocolCategoriesCategoryIdDelete>>,
        TError,
        {categoryId: string},
        TContext
      > => {

      const mutationOptions = getDeleteProtocolCategoryApiV1ProtocolCategoriesCategoryIdDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    