/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ActivitySummaryResponse,
  AddIdentifierBody,
  AddIdentifierResponse,
  CreateRelationshipBody,
  DepictRequest,
  DepictResponse,
  HTTPValidationError,
  IdentifierResponse,
  ListMoleculesApiV1MoleculesGetParams,
  MergeBody,
  MergeEventResponse,
  MergeImpactResponse,
  MoleculeResponse,
  MoleculeTestCountsBody,
  MoleculeTestCountsResponse,
  PaginatedResponseMoleculeResponse,
  RegisterMoleculeBody,
  RegistrationResponse,
  RelationshipResponse,
  SearchMoleculesApiV1MoleculesSearchGetParams,
  StructureSearchResponse,
  UpdateMoleculeBody
} from '.././model';

import { customInstance } from '.././custom-instance';




/**
 * @summary Register Molecule
 */
export const registerMoleculeApiV1MoleculesPost = (
    registerMoleculeBody: RegisterMoleculeBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<RegistrationResponse>(
      {url: `/api/v1/molecules`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerMoleculeBody, signal
    },
      );
    }
  


export const getRegisterMoleculeApiV1MoleculesPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerMoleculeApiV1MoleculesPost>>, TError,{data: RegisterMoleculeBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof registerMoleculeApiV1MoleculesPost>>, TError,{data: RegisterMoleculeBody}, TContext> => {

const mutationKey = ['registerMoleculeApiV1MoleculesPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof registerMoleculeApiV1MoleculesPost>>, {data: RegisterMoleculeBody}> = (props) => {
          const {data} = props ?? {};

          return  registerMoleculeApiV1MoleculesPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RegisterMoleculeApiV1MoleculesPostMutationResult = NonNullable<Awaited<ReturnType<typeof registerMoleculeApiV1MoleculesPost>>>
    export type RegisterMoleculeApiV1MoleculesPostMutationBody = RegisterMoleculeBody
    export type RegisterMoleculeApiV1MoleculesPostMutationError = HTTPValidationError

    /**
 * @summary Register Molecule
 */
export const useRegisterMoleculeApiV1MoleculesPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerMoleculeApiV1MoleculesPost>>, TError,{data: RegisterMoleculeBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof registerMoleculeApiV1MoleculesPost>>,
        TError,
        {data: RegisterMoleculeBody},
        TContext
      > => {

      const mutationOptions = getRegisterMoleculeApiV1MoleculesPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List Molecules
 */
export const listMoleculesApiV1MoleculesGet = (
    params?: ListMoleculesApiV1MoleculesGetParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PaginatedResponseMoleculeResponse>(
      {url: `/api/v1/molecules`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getListMoleculesApiV1MoleculesGetQueryKey = (params?: ListMoleculesApiV1MoleculesGetParams,) => {
    return [
    `/api/v1/molecules`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListMoleculesApiV1MoleculesGetQueryOptions = <TData = Awaited<ReturnType<typeof listMoleculesApiV1MoleculesGet>>, TError = HTTPValidationError>(params?: ListMoleculesApiV1MoleculesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMoleculesApiV1MoleculesGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListMoleculesApiV1MoleculesGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listMoleculesApiV1MoleculesGet>>> = ({ signal }) => listMoleculesApiV1MoleculesGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listMoleculesApiV1MoleculesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListMoleculesApiV1MoleculesGetQueryResult = NonNullable<Awaited<ReturnType<typeof listMoleculesApiV1MoleculesGet>>>
export type ListMoleculesApiV1MoleculesGetQueryError = HTTPValidationError


export function useListMoleculesApiV1MoleculesGet<TData = Awaited<ReturnType<typeof listMoleculesApiV1MoleculesGet>>, TError = HTTPValidationError>(
 params: undefined |  ListMoleculesApiV1MoleculesGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMoleculesApiV1MoleculesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMoleculesApiV1MoleculesGet>>,
          TError,
          Awaited<ReturnType<typeof listMoleculesApiV1MoleculesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMoleculesApiV1MoleculesGet<TData = Awaited<ReturnType<typeof listMoleculesApiV1MoleculesGet>>, TError = HTTPValidationError>(
 params?: ListMoleculesApiV1MoleculesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMoleculesApiV1MoleculesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMoleculesApiV1MoleculesGet>>,
          TError,
          Awaited<ReturnType<typeof listMoleculesApiV1MoleculesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMoleculesApiV1MoleculesGet<TData = Awaited<ReturnType<typeof listMoleculesApiV1MoleculesGet>>, TError = HTTPValidationError>(
 params?: ListMoleculesApiV1MoleculesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMoleculesApiV1MoleculesGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Molecules
 */

export function useListMoleculesApiV1MoleculesGet<TData = Awaited<ReturnType<typeof listMoleculesApiV1MoleculesGet>>, TError = HTTPValidationError>(
 params?: ListMoleculesApiV1MoleculesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMoleculesApiV1MoleculesGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListMoleculesApiV1MoleculesGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Structure search: exact (by SMILES), substructure (by SMILES or SMARTS),
or similarity (by SMILES).

For substructure, ``query_kind`` selects the cartridge interpretation —
``"smiles"`` for plain structures (cartridge handles aromaticity),
``"smarts"`` for queries with atom lists / R-groups / query primitives.
Omitted ⇒ legacy SMARTS path (aromatized defensively).

Results are capped at ``limit`` (max 500, default 100).
 * @summary Search Molecules
 */
export const searchMoleculesApiV1MoleculesSearchGet = (
    params: SearchMoleculesApiV1MoleculesSearchGetParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<StructureSearchResponse>(
      {url: `/api/v1/molecules/search`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getSearchMoleculesApiV1MoleculesSearchGetQueryKey = (params?: SearchMoleculesApiV1MoleculesSearchGetParams,) => {
    return [
    `/api/v1/molecules/search`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getSearchMoleculesApiV1MoleculesSearchGetQueryOptions = <TData = Awaited<ReturnType<typeof searchMoleculesApiV1MoleculesSearchGet>>, TError = HTTPValidationError>(params: SearchMoleculesApiV1MoleculesSearchGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchMoleculesApiV1MoleculesSearchGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchMoleculesApiV1MoleculesSearchGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchMoleculesApiV1MoleculesSearchGet>>> = ({ signal }) => searchMoleculesApiV1MoleculesSearchGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchMoleculesApiV1MoleculesSearchGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchMoleculesApiV1MoleculesSearchGetQueryResult = NonNullable<Awaited<ReturnType<typeof searchMoleculesApiV1MoleculesSearchGet>>>
export type SearchMoleculesApiV1MoleculesSearchGetQueryError = HTTPValidationError


export function useSearchMoleculesApiV1MoleculesSearchGet<TData = Awaited<ReturnType<typeof searchMoleculesApiV1MoleculesSearchGet>>, TError = HTTPValidationError>(
 params: SearchMoleculesApiV1MoleculesSearchGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchMoleculesApiV1MoleculesSearchGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchMoleculesApiV1MoleculesSearchGet>>,
          TError,
          Awaited<ReturnType<typeof searchMoleculesApiV1MoleculesSearchGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchMoleculesApiV1MoleculesSearchGet<TData = Awaited<ReturnType<typeof searchMoleculesApiV1MoleculesSearchGet>>, TError = HTTPValidationError>(
 params: SearchMoleculesApiV1MoleculesSearchGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchMoleculesApiV1MoleculesSearchGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchMoleculesApiV1MoleculesSearchGet>>,
          TError,
          Awaited<ReturnType<typeof searchMoleculesApiV1MoleculesSearchGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchMoleculesApiV1MoleculesSearchGet<TData = Awaited<ReturnType<typeof searchMoleculesApiV1MoleculesSearchGet>>, TError = HTTPValidationError>(
 params: SearchMoleculesApiV1MoleculesSearchGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchMoleculesApiV1MoleculesSearchGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Search Molecules
 */

export function useSearchMoleculesApiV1MoleculesSearchGet<TData = Awaited<ReturnType<typeof searchMoleculesApiV1MoleculesSearchGet>>, TError = HTTPValidationError>(
 params: SearchMoleculesApiV1MoleculesSearchGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchMoleculesApiV1MoleculesSearchGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchMoleculesApiV1MoleculesSearchGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Look up a molecule by any external identifier (CAS, ChEMBL, vendor ID, etc.).
 * @summary Get Molecule By Identifier
 */
export const getMoleculeByIdentifierApiV1MoleculesByIdentifierIdentifierGet = (
    identifier: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<MoleculeResponse>(
      {url: `/api/v1/molecules/by-identifier/${identifier}`, method: 'GET', signal
    },
      );
    }
  



export const getGetMoleculeByIdentifierApiV1MoleculesByIdentifierIdentifierGetQueryKey = (identifier?: string,) => {
    return [
    `/api/v1/molecules/by-identifier/${identifier}`
    ] as const;
    }

    
export const getGetMoleculeByIdentifierApiV1MoleculesByIdentifierIdentifierGetQueryOptions = <TData = Awaited<ReturnType<typeof getMoleculeByIdentifierApiV1MoleculesByIdentifierIdentifierGet>>, TError = HTTPValidationError>(identifier: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMoleculeByIdentifierApiV1MoleculesByIdentifierIdentifierGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMoleculeByIdentifierApiV1MoleculesByIdentifierIdentifierGetQueryKey(identifier);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMoleculeByIdentifierApiV1MoleculesByIdentifierIdentifierGet>>> = ({ signal }) => getMoleculeByIdentifierApiV1MoleculesByIdentifierIdentifierGet(identifier, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(identifier), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMoleculeByIdentifierApiV1MoleculesByIdentifierIdentifierGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMoleculeByIdentifierApiV1MoleculesByIdentifierIdentifierGetQueryResult = NonNullable<Awaited<ReturnType<typeof getMoleculeByIdentifierApiV1MoleculesByIdentifierIdentifierGet>>>
export type GetMoleculeByIdentifierApiV1MoleculesByIdentifierIdentifierGetQueryError = HTTPValidationError


export function useGetMoleculeByIdentifierApiV1MoleculesByIdentifierIdentifierGet<TData = Awaited<ReturnType<typeof getMoleculeByIdentifierApiV1MoleculesByIdentifierIdentifierGet>>, TError = HTTPValidationError>(
 identifier: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMoleculeByIdentifierApiV1MoleculesByIdentifierIdentifierGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMoleculeByIdentifierApiV1MoleculesByIdentifierIdentifierGet>>,
          TError,
          Awaited<ReturnType<typeof getMoleculeByIdentifierApiV1MoleculesByIdentifierIdentifierGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMoleculeByIdentifierApiV1MoleculesByIdentifierIdentifierGet<TData = Awaited<ReturnType<typeof getMoleculeByIdentifierApiV1MoleculesByIdentifierIdentifierGet>>, TError = HTTPValidationError>(
 identifier: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMoleculeByIdentifierApiV1MoleculesByIdentifierIdentifierGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMoleculeByIdentifierApiV1MoleculesByIdentifierIdentifierGet>>,
          TError,
          Awaited<ReturnType<typeof getMoleculeByIdentifierApiV1MoleculesByIdentifierIdentifierGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMoleculeByIdentifierApiV1MoleculesByIdentifierIdentifierGet<TData = Awaited<ReturnType<typeof getMoleculeByIdentifierApiV1MoleculesByIdentifierIdentifierGet>>, TError = HTTPValidationError>(
 identifier: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMoleculeByIdentifierApiV1MoleculesByIdentifierIdentifierGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Molecule By Identifier
 */

export function useGetMoleculeByIdentifierApiV1MoleculesByIdentifierIdentifierGet<TData = Awaited<ReturnType<typeof getMoleculeByIdentifierApiV1MoleculesByIdentifierIdentifierGet>>, TError = HTTPValidationError>(
 identifier: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMoleculeByIdentifierApiV1MoleculesByIdentifierIdentifierGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMoleculeByIdentifierApiV1MoleculesByIdentifierIdentifierGetQueryOptions(identifier,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Render 2D structure depictions for a batch of SMILES strings.

Returns a dict mapping each valid SMILES to a base64-encoded PNG.
Invalid SMILES are silently skipped. Max 200 SMILES per request.
 * @summary Depict Structures
 */
export const depictStructuresApiV1MoleculesDepictPost = (
    depictRequest: DepictRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<DepictResponse>(
      {url: `/api/v1/molecules/depict`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: depictRequest, signal
    },
      );
    }
  


export const getDepictStructuresApiV1MoleculesDepictPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof depictStructuresApiV1MoleculesDepictPost>>, TError,{data: DepictRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof depictStructuresApiV1MoleculesDepictPost>>, TError,{data: DepictRequest}, TContext> => {

const mutationKey = ['depictStructuresApiV1MoleculesDepictPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof depictStructuresApiV1MoleculesDepictPost>>, {data: DepictRequest}> = (props) => {
          const {data} = props ?? {};

          return  depictStructuresApiV1MoleculesDepictPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DepictStructuresApiV1MoleculesDepictPostMutationResult = NonNullable<Awaited<ReturnType<typeof depictStructuresApiV1MoleculesDepictPost>>>
    export type DepictStructuresApiV1MoleculesDepictPostMutationBody = DepictRequest
    export type DepictStructuresApiV1MoleculesDepictPostMutationError = HTTPValidationError

    /**
 * @summary Depict Structures
 */
export const useDepictStructuresApiV1MoleculesDepictPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof depictStructuresApiV1MoleculesDepictPost>>, TError,{data: DepictRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof depictStructuresApiV1MoleculesDepictPost>>,
        TError,
        {data: DepictRequest},
        TContext
      > => {

      const mutationOptions = getDepictStructuresApiV1MoleculesDepictPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Return distinct protocol test counts per molecule.

For each molecule ID in the request, return how many distinct protocols
it has at least one dose-response curve in.  When ``project_id`` is
supplied, only protocols linked to that project are counted.

Molecules with no DR data are returned with count=0 so the FE never
has to handle missing keys.
 * @summary Get Molecule Test Counts
 */
export const getMoleculeTestCountsApiV1MoleculesTestCountsPost = (
    moleculeTestCountsBody: MoleculeTestCountsBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<MoleculeTestCountsResponse>(
      {url: `/api/v1/molecules/test-counts`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: moleculeTestCountsBody, signal
    },
      );
    }
  


export const getGetMoleculeTestCountsApiV1MoleculesTestCountsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getMoleculeTestCountsApiV1MoleculesTestCountsPost>>, TError,{data: MoleculeTestCountsBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof getMoleculeTestCountsApiV1MoleculesTestCountsPost>>, TError,{data: MoleculeTestCountsBody}, TContext> => {

const mutationKey = ['getMoleculeTestCountsApiV1MoleculesTestCountsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getMoleculeTestCountsApiV1MoleculesTestCountsPost>>, {data: MoleculeTestCountsBody}> = (props) => {
          const {data} = props ?? {};

          return  getMoleculeTestCountsApiV1MoleculesTestCountsPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type GetMoleculeTestCountsApiV1MoleculesTestCountsPostMutationResult = NonNullable<Awaited<ReturnType<typeof getMoleculeTestCountsApiV1MoleculesTestCountsPost>>>
    export type GetMoleculeTestCountsApiV1MoleculesTestCountsPostMutationBody = MoleculeTestCountsBody
    export type GetMoleculeTestCountsApiV1MoleculesTestCountsPostMutationError = HTTPValidationError

    /**
 * @summary Get Molecule Test Counts
 */
export const useGetMoleculeTestCountsApiV1MoleculesTestCountsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getMoleculeTestCountsApiV1MoleculesTestCountsPost>>, TError,{data: MoleculeTestCountsBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getMoleculeTestCountsApiV1MoleculesTestCountsPost>>,
        TError,
        {data: MoleculeTestCountsBody},
        TContext
      > => {

      const mutationOptions = getGetMoleculeTestCountsApiV1MoleculesTestCountsPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get Molecule
 */
export const getMoleculeApiV1MoleculesMoleculeIdGet = (
    moleculeId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<MoleculeResponse>(
      {url: `/api/v1/molecules/${moleculeId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetMoleculeApiV1MoleculesMoleculeIdGetQueryKey = (moleculeId?: string,) => {
    return [
    `/api/v1/molecules/${moleculeId}`
    ] as const;
    }

    
export const getGetMoleculeApiV1MoleculesMoleculeIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getMoleculeApiV1MoleculesMoleculeIdGet>>, TError = HTTPValidationError>(moleculeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMoleculeApiV1MoleculesMoleculeIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMoleculeApiV1MoleculesMoleculeIdGetQueryKey(moleculeId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMoleculeApiV1MoleculesMoleculeIdGet>>> = ({ signal }) => getMoleculeApiV1MoleculesMoleculeIdGet(moleculeId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(moleculeId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMoleculeApiV1MoleculesMoleculeIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMoleculeApiV1MoleculesMoleculeIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getMoleculeApiV1MoleculesMoleculeIdGet>>>
export type GetMoleculeApiV1MoleculesMoleculeIdGetQueryError = HTTPValidationError


export function useGetMoleculeApiV1MoleculesMoleculeIdGet<TData = Awaited<ReturnType<typeof getMoleculeApiV1MoleculesMoleculeIdGet>>, TError = HTTPValidationError>(
 moleculeId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMoleculeApiV1MoleculesMoleculeIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMoleculeApiV1MoleculesMoleculeIdGet>>,
          TError,
          Awaited<ReturnType<typeof getMoleculeApiV1MoleculesMoleculeIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMoleculeApiV1MoleculesMoleculeIdGet<TData = Awaited<ReturnType<typeof getMoleculeApiV1MoleculesMoleculeIdGet>>, TError = HTTPValidationError>(
 moleculeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMoleculeApiV1MoleculesMoleculeIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMoleculeApiV1MoleculesMoleculeIdGet>>,
          TError,
          Awaited<ReturnType<typeof getMoleculeApiV1MoleculesMoleculeIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMoleculeApiV1MoleculesMoleculeIdGet<TData = Awaited<ReturnType<typeof getMoleculeApiV1MoleculesMoleculeIdGet>>, TError = HTTPValidationError>(
 moleculeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMoleculeApiV1MoleculesMoleculeIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Molecule
 */

export function useGetMoleculeApiV1MoleculesMoleculeIdGet<TData = Awaited<ReturnType<typeof getMoleculeApiV1MoleculesMoleculeIdGet>>, TError = HTTPValidationError>(
 moleculeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMoleculeApiV1MoleculesMoleculeIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMoleculeApiV1MoleculesMoleculeIdGetQueryOptions(moleculeId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update Molecule
 */
export const updateMoleculeApiV1MoleculesMoleculeIdPatch = (
    moleculeId: string,
    updateMoleculeBody: UpdateMoleculeBody,
 ) => {
      
      
      return customInstance<MoleculeResponse>(
      {url: `/api/v1/molecules/${moleculeId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateMoleculeBody
    },
      );
    }
  


export const getUpdateMoleculeApiV1MoleculesMoleculeIdPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMoleculeApiV1MoleculesMoleculeIdPatch>>, TError,{moleculeId: string;data: UpdateMoleculeBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateMoleculeApiV1MoleculesMoleculeIdPatch>>, TError,{moleculeId: string;data: UpdateMoleculeBody}, TContext> => {

const mutationKey = ['updateMoleculeApiV1MoleculesMoleculeIdPatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateMoleculeApiV1MoleculesMoleculeIdPatch>>, {moleculeId: string;data: UpdateMoleculeBody}> = (props) => {
          const {moleculeId,data} = props ?? {};

          return  updateMoleculeApiV1MoleculesMoleculeIdPatch(moleculeId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateMoleculeApiV1MoleculesMoleculeIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateMoleculeApiV1MoleculesMoleculeIdPatch>>>
    export type UpdateMoleculeApiV1MoleculesMoleculeIdPatchMutationBody = UpdateMoleculeBody
    export type UpdateMoleculeApiV1MoleculesMoleculeIdPatchMutationError = HTTPValidationError

    /**
 * @summary Update Molecule
 */
export const useUpdateMoleculeApiV1MoleculesMoleculeIdPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMoleculeApiV1MoleculesMoleculeIdPatch>>, TError,{moleculeId: string;data: UpdateMoleculeBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateMoleculeApiV1MoleculesMoleculeIdPatch>>,
        TError,
        {moleculeId: string;data: UpdateMoleculeBody},
        TContext
      > => {

      const mutationOptions = getUpdateMoleculeApiV1MoleculesMoleculeIdPatchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get activity summary for a molecule across all protocols.
 * @summary Get Molecule Activity
 */
export const getMoleculeActivityApiV1MoleculesMoleculeIdActivityGet = (
    moleculeId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ActivitySummaryResponse>(
      {url: `/api/v1/molecules/${moleculeId}/activity`, method: 'GET', signal
    },
      );
    }
  



export const getGetMoleculeActivityApiV1MoleculesMoleculeIdActivityGetQueryKey = (moleculeId?: string,) => {
    return [
    `/api/v1/molecules/${moleculeId}/activity`
    ] as const;
    }

    
export const getGetMoleculeActivityApiV1MoleculesMoleculeIdActivityGetQueryOptions = <TData = Awaited<ReturnType<typeof getMoleculeActivityApiV1MoleculesMoleculeIdActivityGet>>, TError = HTTPValidationError>(moleculeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMoleculeActivityApiV1MoleculesMoleculeIdActivityGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMoleculeActivityApiV1MoleculesMoleculeIdActivityGetQueryKey(moleculeId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMoleculeActivityApiV1MoleculesMoleculeIdActivityGet>>> = ({ signal }) => getMoleculeActivityApiV1MoleculesMoleculeIdActivityGet(moleculeId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(moleculeId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMoleculeActivityApiV1MoleculesMoleculeIdActivityGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMoleculeActivityApiV1MoleculesMoleculeIdActivityGetQueryResult = NonNullable<Awaited<ReturnType<typeof getMoleculeActivityApiV1MoleculesMoleculeIdActivityGet>>>
export type GetMoleculeActivityApiV1MoleculesMoleculeIdActivityGetQueryError = HTTPValidationError


export function useGetMoleculeActivityApiV1MoleculesMoleculeIdActivityGet<TData = Awaited<ReturnType<typeof getMoleculeActivityApiV1MoleculesMoleculeIdActivityGet>>, TError = HTTPValidationError>(
 moleculeId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMoleculeActivityApiV1MoleculesMoleculeIdActivityGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMoleculeActivityApiV1MoleculesMoleculeIdActivityGet>>,
          TError,
          Awaited<ReturnType<typeof getMoleculeActivityApiV1MoleculesMoleculeIdActivityGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMoleculeActivityApiV1MoleculesMoleculeIdActivityGet<TData = Awaited<ReturnType<typeof getMoleculeActivityApiV1MoleculesMoleculeIdActivityGet>>, TError = HTTPValidationError>(
 moleculeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMoleculeActivityApiV1MoleculesMoleculeIdActivityGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMoleculeActivityApiV1MoleculesMoleculeIdActivityGet>>,
          TError,
          Awaited<ReturnType<typeof getMoleculeActivityApiV1MoleculesMoleculeIdActivityGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMoleculeActivityApiV1MoleculesMoleculeIdActivityGet<TData = Awaited<ReturnType<typeof getMoleculeActivityApiV1MoleculesMoleculeIdActivityGet>>, TError = HTTPValidationError>(
 moleculeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMoleculeActivityApiV1MoleculesMoleculeIdActivityGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Molecule Activity
 */

export function useGetMoleculeActivityApiV1MoleculesMoleculeIdActivityGet<TData = Awaited<ReturnType<typeof getMoleculeActivityApiV1MoleculesMoleculeIdActivityGet>>, TError = HTTPValidationError>(
 moleculeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMoleculeActivityApiV1MoleculesMoleculeIdActivityGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMoleculeActivityApiV1MoleculesMoleculeIdActivityGetQueryOptions(moleculeId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * List all registered plates containing batches of this molecule.
 * @summary List Molecule Plates
 */
export const listMoleculePlatesApiV1MoleculesMoleculeIdPlatesGet = (
    moleculeId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/molecules/${moleculeId}/plates`, method: 'GET', signal
    },
      );
    }
  



export const getListMoleculePlatesApiV1MoleculesMoleculeIdPlatesGetQueryKey = (moleculeId?: string,) => {
    return [
    `/api/v1/molecules/${moleculeId}/plates`
    ] as const;
    }

    
export const getListMoleculePlatesApiV1MoleculesMoleculeIdPlatesGetQueryOptions = <TData = Awaited<ReturnType<typeof listMoleculePlatesApiV1MoleculesMoleculeIdPlatesGet>>, TError = HTTPValidationError>(moleculeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMoleculePlatesApiV1MoleculesMoleculeIdPlatesGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListMoleculePlatesApiV1MoleculesMoleculeIdPlatesGetQueryKey(moleculeId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listMoleculePlatesApiV1MoleculesMoleculeIdPlatesGet>>> = ({ signal }) => listMoleculePlatesApiV1MoleculesMoleculeIdPlatesGet(moleculeId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(moleculeId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listMoleculePlatesApiV1MoleculesMoleculeIdPlatesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListMoleculePlatesApiV1MoleculesMoleculeIdPlatesGetQueryResult = NonNullable<Awaited<ReturnType<typeof listMoleculePlatesApiV1MoleculesMoleculeIdPlatesGet>>>
export type ListMoleculePlatesApiV1MoleculesMoleculeIdPlatesGetQueryError = HTTPValidationError


export function useListMoleculePlatesApiV1MoleculesMoleculeIdPlatesGet<TData = Awaited<ReturnType<typeof listMoleculePlatesApiV1MoleculesMoleculeIdPlatesGet>>, TError = HTTPValidationError>(
 moleculeId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMoleculePlatesApiV1MoleculesMoleculeIdPlatesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMoleculePlatesApiV1MoleculesMoleculeIdPlatesGet>>,
          TError,
          Awaited<ReturnType<typeof listMoleculePlatesApiV1MoleculesMoleculeIdPlatesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMoleculePlatesApiV1MoleculesMoleculeIdPlatesGet<TData = Awaited<ReturnType<typeof listMoleculePlatesApiV1MoleculesMoleculeIdPlatesGet>>, TError = HTTPValidationError>(
 moleculeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMoleculePlatesApiV1MoleculesMoleculeIdPlatesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMoleculePlatesApiV1MoleculesMoleculeIdPlatesGet>>,
          TError,
          Awaited<ReturnType<typeof listMoleculePlatesApiV1MoleculesMoleculeIdPlatesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMoleculePlatesApiV1MoleculesMoleculeIdPlatesGet<TData = Awaited<ReturnType<typeof listMoleculePlatesApiV1MoleculesMoleculeIdPlatesGet>>, TError = HTTPValidationError>(
 moleculeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMoleculePlatesApiV1MoleculesMoleculeIdPlatesGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Molecule Plates
 */

export function useListMoleculePlatesApiV1MoleculesMoleculeIdPlatesGet<TData = Awaited<ReturnType<typeof listMoleculePlatesApiV1MoleculesMoleculeIdPlatesGet>>, TError = HTTPValidationError>(
 moleculeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMoleculePlatesApiV1MoleculesMoleculeIdPlatesGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListMoleculePlatesApiV1MoleculesMoleculeIdPlatesGetQueryOptions(moleculeId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * List collections containing this molecule.
 * @summary List Molecule Collections
 */
export const listMoleculeCollectionsApiV1MoleculesMoleculeIdCollectionsGet = (
    moleculeId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/molecules/${moleculeId}/collections`, method: 'GET', signal
    },
      );
    }
  



export const getListMoleculeCollectionsApiV1MoleculesMoleculeIdCollectionsGetQueryKey = (moleculeId?: string,) => {
    return [
    `/api/v1/molecules/${moleculeId}/collections`
    ] as const;
    }

    
export const getListMoleculeCollectionsApiV1MoleculesMoleculeIdCollectionsGetQueryOptions = <TData = Awaited<ReturnType<typeof listMoleculeCollectionsApiV1MoleculesMoleculeIdCollectionsGet>>, TError = HTTPValidationError>(moleculeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMoleculeCollectionsApiV1MoleculesMoleculeIdCollectionsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListMoleculeCollectionsApiV1MoleculesMoleculeIdCollectionsGetQueryKey(moleculeId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listMoleculeCollectionsApiV1MoleculesMoleculeIdCollectionsGet>>> = ({ signal }) => listMoleculeCollectionsApiV1MoleculesMoleculeIdCollectionsGet(moleculeId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(moleculeId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listMoleculeCollectionsApiV1MoleculesMoleculeIdCollectionsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListMoleculeCollectionsApiV1MoleculesMoleculeIdCollectionsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listMoleculeCollectionsApiV1MoleculesMoleculeIdCollectionsGet>>>
export type ListMoleculeCollectionsApiV1MoleculesMoleculeIdCollectionsGetQueryError = HTTPValidationError


export function useListMoleculeCollectionsApiV1MoleculesMoleculeIdCollectionsGet<TData = Awaited<ReturnType<typeof listMoleculeCollectionsApiV1MoleculesMoleculeIdCollectionsGet>>, TError = HTTPValidationError>(
 moleculeId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMoleculeCollectionsApiV1MoleculesMoleculeIdCollectionsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMoleculeCollectionsApiV1MoleculesMoleculeIdCollectionsGet>>,
          TError,
          Awaited<ReturnType<typeof listMoleculeCollectionsApiV1MoleculesMoleculeIdCollectionsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMoleculeCollectionsApiV1MoleculesMoleculeIdCollectionsGet<TData = Awaited<ReturnType<typeof listMoleculeCollectionsApiV1MoleculesMoleculeIdCollectionsGet>>, TError = HTTPValidationError>(
 moleculeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMoleculeCollectionsApiV1MoleculesMoleculeIdCollectionsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMoleculeCollectionsApiV1MoleculesMoleculeIdCollectionsGet>>,
          TError,
          Awaited<ReturnType<typeof listMoleculeCollectionsApiV1MoleculesMoleculeIdCollectionsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMoleculeCollectionsApiV1MoleculesMoleculeIdCollectionsGet<TData = Awaited<ReturnType<typeof listMoleculeCollectionsApiV1MoleculesMoleculeIdCollectionsGet>>, TError = HTTPValidationError>(
 moleculeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMoleculeCollectionsApiV1MoleculesMoleculeIdCollectionsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Molecule Collections
 */

export function useListMoleculeCollectionsApiV1MoleculesMoleculeIdCollectionsGet<TData = Awaited<ReturnType<typeof listMoleculeCollectionsApiV1MoleculesMoleculeIdCollectionsGet>>, TError = HTTPValidationError>(
 moleculeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMoleculeCollectionsApiV1MoleculesMoleculeIdCollectionsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListMoleculeCollectionsApiV1MoleculesMoleculeIdCollectionsGetQueryOptions(moleculeId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * List all external identifiers for a molecule.
 * @summary List Identifiers
 */
export const listIdentifiersApiV1MoleculesMoleculeIdIdentifiersGet = (
    moleculeId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<IdentifierResponse[]>(
      {url: `/api/v1/molecules/${moleculeId}/identifiers`, method: 'GET', signal
    },
      );
    }
  



export const getListIdentifiersApiV1MoleculesMoleculeIdIdentifiersGetQueryKey = (moleculeId?: string,) => {
    return [
    `/api/v1/molecules/${moleculeId}/identifiers`
    ] as const;
    }

    
export const getListIdentifiersApiV1MoleculesMoleculeIdIdentifiersGetQueryOptions = <TData = Awaited<ReturnType<typeof listIdentifiersApiV1MoleculesMoleculeIdIdentifiersGet>>, TError = HTTPValidationError>(moleculeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listIdentifiersApiV1MoleculesMoleculeIdIdentifiersGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListIdentifiersApiV1MoleculesMoleculeIdIdentifiersGetQueryKey(moleculeId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listIdentifiersApiV1MoleculesMoleculeIdIdentifiersGet>>> = ({ signal }) => listIdentifiersApiV1MoleculesMoleculeIdIdentifiersGet(moleculeId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(moleculeId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listIdentifiersApiV1MoleculesMoleculeIdIdentifiersGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListIdentifiersApiV1MoleculesMoleculeIdIdentifiersGetQueryResult = NonNullable<Awaited<ReturnType<typeof listIdentifiersApiV1MoleculesMoleculeIdIdentifiersGet>>>
export type ListIdentifiersApiV1MoleculesMoleculeIdIdentifiersGetQueryError = HTTPValidationError


export function useListIdentifiersApiV1MoleculesMoleculeIdIdentifiersGet<TData = Awaited<ReturnType<typeof listIdentifiersApiV1MoleculesMoleculeIdIdentifiersGet>>, TError = HTTPValidationError>(
 moleculeId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listIdentifiersApiV1MoleculesMoleculeIdIdentifiersGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listIdentifiersApiV1MoleculesMoleculeIdIdentifiersGet>>,
          TError,
          Awaited<ReturnType<typeof listIdentifiersApiV1MoleculesMoleculeIdIdentifiersGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListIdentifiersApiV1MoleculesMoleculeIdIdentifiersGet<TData = Awaited<ReturnType<typeof listIdentifiersApiV1MoleculesMoleculeIdIdentifiersGet>>, TError = HTTPValidationError>(
 moleculeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listIdentifiersApiV1MoleculesMoleculeIdIdentifiersGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listIdentifiersApiV1MoleculesMoleculeIdIdentifiersGet>>,
          TError,
          Awaited<ReturnType<typeof listIdentifiersApiV1MoleculesMoleculeIdIdentifiersGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListIdentifiersApiV1MoleculesMoleculeIdIdentifiersGet<TData = Awaited<ReturnType<typeof listIdentifiersApiV1MoleculesMoleculeIdIdentifiersGet>>, TError = HTTPValidationError>(
 moleculeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listIdentifiersApiV1MoleculesMoleculeIdIdentifiersGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Identifiers
 */

export function useListIdentifiersApiV1MoleculesMoleculeIdIdentifiersGet<TData = Awaited<ReturnType<typeof listIdentifiersApiV1MoleculesMoleculeIdIdentifiersGet>>, TError = HTTPValidationError>(
 moleculeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listIdentifiersApiV1MoleculesMoleculeIdIdentifiersGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListIdentifiersApiV1MoleculesMoleculeIdIdentifiersGetQueryOptions(moleculeId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Add an external identifier to a molecule. Returns updated list + mirror summary.
 * @summary Add Identifier
 */
export const addIdentifierApiV1MoleculesMoleculeIdIdentifiersPost = (
    moleculeId: string,
    addIdentifierBody: AddIdentifierBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<AddIdentifierResponse>(
      {url: `/api/v1/molecules/${moleculeId}/identifiers`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addIdentifierBody, signal
    },
      );
    }
  


export const getAddIdentifierApiV1MoleculesMoleculeIdIdentifiersPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addIdentifierApiV1MoleculesMoleculeIdIdentifiersPost>>, TError,{moleculeId: string;data: AddIdentifierBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof addIdentifierApiV1MoleculesMoleculeIdIdentifiersPost>>, TError,{moleculeId: string;data: AddIdentifierBody}, TContext> => {

const mutationKey = ['addIdentifierApiV1MoleculesMoleculeIdIdentifiersPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addIdentifierApiV1MoleculesMoleculeIdIdentifiersPost>>, {moleculeId: string;data: AddIdentifierBody}> = (props) => {
          const {moleculeId,data} = props ?? {};

          return  addIdentifierApiV1MoleculesMoleculeIdIdentifiersPost(moleculeId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddIdentifierApiV1MoleculesMoleculeIdIdentifiersPostMutationResult = NonNullable<Awaited<ReturnType<typeof addIdentifierApiV1MoleculesMoleculeIdIdentifiersPost>>>
    export type AddIdentifierApiV1MoleculesMoleculeIdIdentifiersPostMutationBody = AddIdentifierBody
    export type AddIdentifierApiV1MoleculesMoleculeIdIdentifiersPostMutationError = HTTPValidationError

    /**
 * @summary Add Identifier
 */
export const useAddIdentifierApiV1MoleculesMoleculeIdIdentifiersPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addIdentifierApiV1MoleculesMoleculeIdIdentifiersPost>>, TError,{moleculeId: string;data: AddIdentifierBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addIdentifierApiV1MoleculesMoleculeIdIdentifiersPost>>,
        TError,
        {moleculeId: string;data: AddIdentifierBody},
        TContext
      > => {

      const mutationOptions = getAddIdentifierApiV1MoleculesMoleculeIdIdentifiersPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Remove an identifier from a molecule.
 * @summary Remove Identifier
 */
export const removeIdentifierApiV1MoleculesMoleculeIdIdentifiersIdentifierIdDelete = (
    moleculeId: string,
    identifierId: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/molecules/${moleculeId}/identifiers/${identifierId}`, method: 'DELETE'
    },
      );
    }
  


export const getRemoveIdentifierApiV1MoleculesMoleculeIdIdentifiersIdentifierIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeIdentifierApiV1MoleculesMoleculeIdIdentifiersIdentifierIdDelete>>, TError,{moleculeId: string;identifierId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof removeIdentifierApiV1MoleculesMoleculeIdIdentifiersIdentifierIdDelete>>, TError,{moleculeId: string;identifierId: string}, TContext> => {

const mutationKey = ['removeIdentifierApiV1MoleculesMoleculeIdIdentifiersIdentifierIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeIdentifierApiV1MoleculesMoleculeIdIdentifiersIdentifierIdDelete>>, {moleculeId: string;identifierId: string}> = (props) => {
          const {moleculeId,identifierId} = props ?? {};

          return  removeIdentifierApiV1MoleculesMoleculeIdIdentifiersIdentifierIdDelete(moleculeId,identifierId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RemoveIdentifierApiV1MoleculesMoleculeIdIdentifiersIdentifierIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof removeIdentifierApiV1MoleculesMoleculeIdIdentifiersIdentifierIdDelete>>>
    
    export type RemoveIdentifierApiV1MoleculesMoleculeIdIdentifiersIdentifierIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Remove Identifier
 */
export const useRemoveIdentifierApiV1MoleculesMoleculeIdIdentifiersIdentifierIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeIdentifierApiV1MoleculesMoleculeIdIdentifiersIdentifierIdDelete>>, TError,{moleculeId: string;identifierId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removeIdentifierApiV1MoleculesMoleculeIdIdentifiersIdentifierIdDelete>>,
        TError,
        {moleculeId: string;identifierId: string},
        TContext
      > => {

      const mutationOptions = getRemoveIdentifierApiV1MoleculesMoleculeIdIdentifiersIdentifierIdDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List Molecule Projects
 */
export const listMoleculeProjectsApiV1MoleculesMoleculeIdProjectsGet = (
    moleculeId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<string[]>(
      {url: `/api/v1/molecules/${moleculeId}/projects`, method: 'GET', signal
    },
      );
    }
  



export const getListMoleculeProjectsApiV1MoleculesMoleculeIdProjectsGetQueryKey = (moleculeId?: string,) => {
    return [
    `/api/v1/molecules/${moleculeId}/projects`
    ] as const;
    }

    
export const getListMoleculeProjectsApiV1MoleculesMoleculeIdProjectsGetQueryOptions = <TData = Awaited<ReturnType<typeof listMoleculeProjectsApiV1MoleculesMoleculeIdProjectsGet>>, TError = HTTPValidationError>(moleculeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMoleculeProjectsApiV1MoleculesMoleculeIdProjectsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListMoleculeProjectsApiV1MoleculesMoleculeIdProjectsGetQueryKey(moleculeId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listMoleculeProjectsApiV1MoleculesMoleculeIdProjectsGet>>> = ({ signal }) => listMoleculeProjectsApiV1MoleculesMoleculeIdProjectsGet(moleculeId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(moleculeId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listMoleculeProjectsApiV1MoleculesMoleculeIdProjectsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListMoleculeProjectsApiV1MoleculesMoleculeIdProjectsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listMoleculeProjectsApiV1MoleculesMoleculeIdProjectsGet>>>
export type ListMoleculeProjectsApiV1MoleculesMoleculeIdProjectsGetQueryError = HTTPValidationError


export function useListMoleculeProjectsApiV1MoleculesMoleculeIdProjectsGet<TData = Awaited<ReturnType<typeof listMoleculeProjectsApiV1MoleculesMoleculeIdProjectsGet>>, TError = HTTPValidationError>(
 moleculeId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMoleculeProjectsApiV1MoleculesMoleculeIdProjectsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMoleculeProjectsApiV1MoleculesMoleculeIdProjectsGet>>,
          TError,
          Awaited<ReturnType<typeof listMoleculeProjectsApiV1MoleculesMoleculeIdProjectsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMoleculeProjectsApiV1MoleculesMoleculeIdProjectsGet<TData = Awaited<ReturnType<typeof listMoleculeProjectsApiV1MoleculesMoleculeIdProjectsGet>>, TError = HTTPValidationError>(
 moleculeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMoleculeProjectsApiV1MoleculesMoleculeIdProjectsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMoleculeProjectsApiV1MoleculesMoleculeIdProjectsGet>>,
          TError,
          Awaited<ReturnType<typeof listMoleculeProjectsApiV1MoleculesMoleculeIdProjectsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMoleculeProjectsApiV1MoleculesMoleculeIdProjectsGet<TData = Awaited<ReturnType<typeof listMoleculeProjectsApiV1MoleculesMoleculeIdProjectsGet>>, TError = HTTPValidationError>(
 moleculeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMoleculeProjectsApiV1MoleculesMoleculeIdProjectsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Molecule Projects
 */

export function useListMoleculeProjectsApiV1MoleculesMoleculeIdProjectsGet<TData = Awaited<ReturnType<typeof listMoleculeProjectsApiV1MoleculesMoleculeIdProjectsGet>>, TError = HTTPValidationError>(
 moleculeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMoleculeProjectsApiV1MoleculesMoleculeIdProjectsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListMoleculeProjectsApiV1MoleculesMoleculeIdProjectsGetQueryOptions(moleculeId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Merge Molecules
 */
export const mergeMoleculesApiV1MoleculesSourceMoleculeIdMergePost = (
    sourceMoleculeId: string,
    mergeBody: MergeBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<MergeEventResponse>(
      {url: `/api/v1/molecules/${sourceMoleculeId}/merge`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: mergeBody, signal
    },
      );
    }
  


export const getMergeMoleculesApiV1MoleculesSourceMoleculeIdMergePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof mergeMoleculesApiV1MoleculesSourceMoleculeIdMergePost>>, TError,{sourceMoleculeId: string;data: MergeBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof mergeMoleculesApiV1MoleculesSourceMoleculeIdMergePost>>, TError,{sourceMoleculeId: string;data: MergeBody}, TContext> => {

const mutationKey = ['mergeMoleculesApiV1MoleculesSourceMoleculeIdMergePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof mergeMoleculesApiV1MoleculesSourceMoleculeIdMergePost>>, {sourceMoleculeId: string;data: MergeBody}> = (props) => {
          const {sourceMoleculeId,data} = props ?? {};

          return  mergeMoleculesApiV1MoleculesSourceMoleculeIdMergePost(sourceMoleculeId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type MergeMoleculesApiV1MoleculesSourceMoleculeIdMergePostMutationResult = NonNullable<Awaited<ReturnType<typeof mergeMoleculesApiV1MoleculesSourceMoleculeIdMergePost>>>
    export type MergeMoleculesApiV1MoleculesSourceMoleculeIdMergePostMutationBody = MergeBody
    export type MergeMoleculesApiV1MoleculesSourceMoleculeIdMergePostMutationError = HTTPValidationError

    /**
 * @summary Merge Molecules
 */
export const useMergeMoleculesApiV1MoleculesSourceMoleculeIdMergePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof mergeMoleculesApiV1MoleculesSourceMoleculeIdMergePost>>, TError,{sourceMoleculeId: string;data: MergeBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof mergeMoleculesApiV1MoleculesSourceMoleculeIdMergePost>>,
        TError,
        {sourceMoleculeId: string;data: MergeBody},
        TContext
      > => {

      const mutationOptions = getMergeMoleculesApiV1MoleculesSourceMoleculeIdMergePostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieve merge history for a molecule (as source or target).
 * @summary Get Merge History
 */
export const getMergeHistoryApiV1MoleculesMoleculeIdMergeHistoryGet = (
    moleculeId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<MergeEventResponse[]>(
      {url: `/api/v1/molecules/${moleculeId}/merge-history`, method: 'GET', signal
    },
      );
    }
  



export const getGetMergeHistoryApiV1MoleculesMoleculeIdMergeHistoryGetQueryKey = (moleculeId?: string,) => {
    return [
    `/api/v1/molecules/${moleculeId}/merge-history`
    ] as const;
    }

    
export const getGetMergeHistoryApiV1MoleculesMoleculeIdMergeHistoryGetQueryOptions = <TData = Awaited<ReturnType<typeof getMergeHistoryApiV1MoleculesMoleculeIdMergeHistoryGet>>, TError = HTTPValidationError>(moleculeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMergeHistoryApiV1MoleculesMoleculeIdMergeHistoryGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMergeHistoryApiV1MoleculesMoleculeIdMergeHistoryGetQueryKey(moleculeId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMergeHistoryApiV1MoleculesMoleculeIdMergeHistoryGet>>> = ({ signal }) => getMergeHistoryApiV1MoleculesMoleculeIdMergeHistoryGet(moleculeId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(moleculeId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMergeHistoryApiV1MoleculesMoleculeIdMergeHistoryGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMergeHistoryApiV1MoleculesMoleculeIdMergeHistoryGetQueryResult = NonNullable<Awaited<ReturnType<typeof getMergeHistoryApiV1MoleculesMoleculeIdMergeHistoryGet>>>
export type GetMergeHistoryApiV1MoleculesMoleculeIdMergeHistoryGetQueryError = HTTPValidationError


export function useGetMergeHistoryApiV1MoleculesMoleculeIdMergeHistoryGet<TData = Awaited<ReturnType<typeof getMergeHistoryApiV1MoleculesMoleculeIdMergeHistoryGet>>, TError = HTTPValidationError>(
 moleculeId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMergeHistoryApiV1MoleculesMoleculeIdMergeHistoryGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMergeHistoryApiV1MoleculesMoleculeIdMergeHistoryGet>>,
          TError,
          Awaited<ReturnType<typeof getMergeHistoryApiV1MoleculesMoleculeIdMergeHistoryGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMergeHistoryApiV1MoleculesMoleculeIdMergeHistoryGet<TData = Awaited<ReturnType<typeof getMergeHistoryApiV1MoleculesMoleculeIdMergeHistoryGet>>, TError = HTTPValidationError>(
 moleculeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMergeHistoryApiV1MoleculesMoleculeIdMergeHistoryGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMergeHistoryApiV1MoleculesMoleculeIdMergeHistoryGet>>,
          TError,
          Awaited<ReturnType<typeof getMergeHistoryApiV1MoleculesMoleculeIdMergeHistoryGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMergeHistoryApiV1MoleculesMoleculeIdMergeHistoryGet<TData = Awaited<ReturnType<typeof getMergeHistoryApiV1MoleculesMoleculeIdMergeHistoryGet>>, TError = HTTPValidationError>(
 moleculeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMergeHistoryApiV1MoleculesMoleculeIdMergeHistoryGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Merge History
 */

export function useGetMergeHistoryApiV1MoleculesMoleculeIdMergeHistoryGet<TData = Awaited<ReturnType<typeof getMergeHistoryApiV1MoleculesMoleculeIdMergeHistoryGet>>, TError = HTTPValidationError>(
 moleculeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMergeHistoryApiV1MoleculesMoleculeIdMergeHistoryGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMergeHistoryApiV1MoleculesMoleculeIdMergeHistoryGetQueryOptions(moleculeId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Preview what data would be affected by merging source into target.
 * @summary Get Merge Impact
 */
export const getMergeImpactApiV1MoleculesSourceMoleculeIdMergeImpactTargetMoleculeIdGet = (
    sourceMoleculeId: string,
    targetMoleculeId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<MergeImpactResponse>(
      {url: `/api/v1/molecules/${sourceMoleculeId}/merge-impact/${targetMoleculeId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetMergeImpactApiV1MoleculesSourceMoleculeIdMergeImpactTargetMoleculeIdGetQueryKey = (sourceMoleculeId?: string,
    targetMoleculeId?: string,) => {
    return [
    `/api/v1/molecules/${sourceMoleculeId}/merge-impact/${targetMoleculeId}`
    ] as const;
    }

    
export const getGetMergeImpactApiV1MoleculesSourceMoleculeIdMergeImpactTargetMoleculeIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getMergeImpactApiV1MoleculesSourceMoleculeIdMergeImpactTargetMoleculeIdGet>>, TError = HTTPValidationError>(sourceMoleculeId: string,
    targetMoleculeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMergeImpactApiV1MoleculesSourceMoleculeIdMergeImpactTargetMoleculeIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMergeImpactApiV1MoleculesSourceMoleculeIdMergeImpactTargetMoleculeIdGetQueryKey(sourceMoleculeId,targetMoleculeId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMergeImpactApiV1MoleculesSourceMoleculeIdMergeImpactTargetMoleculeIdGet>>> = ({ signal }) => getMergeImpactApiV1MoleculesSourceMoleculeIdMergeImpactTargetMoleculeIdGet(sourceMoleculeId,targetMoleculeId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(sourceMoleculeId && targetMoleculeId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMergeImpactApiV1MoleculesSourceMoleculeIdMergeImpactTargetMoleculeIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMergeImpactApiV1MoleculesSourceMoleculeIdMergeImpactTargetMoleculeIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getMergeImpactApiV1MoleculesSourceMoleculeIdMergeImpactTargetMoleculeIdGet>>>
export type GetMergeImpactApiV1MoleculesSourceMoleculeIdMergeImpactTargetMoleculeIdGetQueryError = HTTPValidationError


export function useGetMergeImpactApiV1MoleculesSourceMoleculeIdMergeImpactTargetMoleculeIdGet<TData = Awaited<ReturnType<typeof getMergeImpactApiV1MoleculesSourceMoleculeIdMergeImpactTargetMoleculeIdGet>>, TError = HTTPValidationError>(
 sourceMoleculeId: string,
    targetMoleculeId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMergeImpactApiV1MoleculesSourceMoleculeIdMergeImpactTargetMoleculeIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMergeImpactApiV1MoleculesSourceMoleculeIdMergeImpactTargetMoleculeIdGet>>,
          TError,
          Awaited<ReturnType<typeof getMergeImpactApiV1MoleculesSourceMoleculeIdMergeImpactTargetMoleculeIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMergeImpactApiV1MoleculesSourceMoleculeIdMergeImpactTargetMoleculeIdGet<TData = Awaited<ReturnType<typeof getMergeImpactApiV1MoleculesSourceMoleculeIdMergeImpactTargetMoleculeIdGet>>, TError = HTTPValidationError>(
 sourceMoleculeId: string,
    targetMoleculeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMergeImpactApiV1MoleculesSourceMoleculeIdMergeImpactTargetMoleculeIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMergeImpactApiV1MoleculesSourceMoleculeIdMergeImpactTargetMoleculeIdGet>>,
          TError,
          Awaited<ReturnType<typeof getMergeImpactApiV1MoleculesSourceMoleculeIdMergeImpactTargetMoleculeIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMergeImpactApiV1MoleculesSourceMoleculeIdMergeImpactTargetMoleculeIdGet<TData = Awaited<ReturnType<typeof getMergeImpactApiV1MoleculesSourceMoleculeIdMergeImpactTargetMoleculeIdGet>>, TError = HTTPValidationError>(
 sourceMoleculeId: string,
    targetMoleculeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMergeImpactApiV1MoleculesSourceMoleculeIdMergeImpactTargetMoleculeIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Merge Impact
 */

export function useGetMergeImpactApiV1MoleculesSourceMoleculeIdMergeImpactTargetMoleculeIdGet<TData = Awaited<ReturnType<typeof getMergeImpactApiV1MoleculesSourceMoleculeIdMergeImpactTargetMoleculeIdGet>>, TError = HTTPValidationError>(
 sourceMoleculeId: string,
    targetMoleculeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMergeImpactApiV1MoleculesSourceMoleculeIdMergeImpactTargetMoleculeIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMergeImpactApiV1MoleculesSourceMoleculeIdMergeImpactTargetMoleculeIdGetQueryOptions(sourceMoleculeId,targetMoleculeId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create Relationship
 */
export const createRelationshipApiV1MoleculesMoleculeIdRelationshipsPost = (
    moleculeId: string,
    createRelationshipBody: CreateRelationshipBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<RelationshipResponse>(
      {url: `/api/v1/molecules/${moleculeId}/relationships`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createRelationshipBody, signal
    },
      );
    }
  


export const getCreateRelationshipApiV1MoleculesMoleculeIdRelationshipsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRelationshipApiV1MoleculesMoleculeIdRelationshipsPost>>, TError,{moleculeId: string;data: CreateRelationshipBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createRelationshipApiV1MoleculesMoleculeIdRelationshipsPost>>, TError,{moleculeId: string;data: CreateRelationshipBody}, TContext> => {

const mutationKey = ['createRelationshipApiV1MoleculesMoleculeIdRelationshipsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createRelationshipApiV1MoleculesMoleculeIdRelationshipsPost>>, {moleculeId: string;data: CreateRelationshipBody}> = (props) => {
          const {moleculeId,data} = props ?? {};

          return  createRelationshipApiV1MoleculesMoleculeIdRelationshipsPost(moleculeId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateRelationshipApiV1MoleculesMoleculeIdRelationshipsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createRelationshipApiV1MoleculesMoleculeIdRelationshipsPost>>>
    export type CreateRelationshipApiV1MoleculesMoleculeIdRelationshipsPostMutationBody = CreateRelationshipBody
    export type CreateRelationshipApiV1MoleculesMoleculeIdRelationshipsPostMutationError = HTTPValidationError

    /**
 * @summary Create Relationship
 */
export const useCreateRelationshipApiV1MoleculesMoleculeIdRelationshipsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRelationshipApiV1MoleculesMoleculeIdRelationshipsPost>>, TError,{moleculeId: string;data: CreateRelationshipBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createRelationshipApiV1MoleculesMoleculeIdRelationshipsPost>>,
        TError,
        {moleculeId: string;data: CreateRelationshipBody},
        TContext
      > => {

      const mutationOptions = getCreateRelationshipApiV1MoleculesMoleculeIdRelationshipsPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List Relationships
 */
export const listRelationshipsApiV1MoleculesMoleculeIdRelationshipsGet = (
    moleculeId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<RelationshipResponse[]>(
      {url: `/api/v1/molecules/${moleculeId}/relationships`, method: 'GET', signal
    },
      );
    }
  



export const getListRelationshipsApiV1MoleculesMoleculeIdRelationshipsGetQueryKey = (moleculeId?: string,) => {
    return [
    `/api/v1/molecules/${moleculeId}/relationships`
    ] as const;
    }

    
export const getListRelationshipsApiV1MoleculesMoleculeIdRelationshipsGetQueryOptions = <TData = Awaited<ReturnType<typeof listRelationshipsApiV1MoleculesMoleculeIdRelationshipsGet>>, TError = HTTPValidationError>(moleculeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRelationshipsApiV1MoleculesMoleculeIdRelationshipsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListRelationshipsApiV1MoleculesMoleculeIdRelationshipsGetQueryKey(moleculeId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listRelationshipsApiV1MoleculesMoleculeIdRelationshipsGet>>> = ({ signal }) => listRelationshipsApiV1MoleculesMoleculeIdRelationshipsGet(moleculeId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(moleculeId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listRelationshipsApiV1MoleculesMoleculeIdRelationshipsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListRelationshipsApiV1MoleculesMoleculeIdRelationshipsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listRelationshipsApiV1MoleculesMoleculeIdRelationshipsGet>>>
export type ListRelationshipsApiV1MoleculesMoleculeIdRelationshipsGetQueryError = HTTPValidationError


export function useListRelationshipsApiV1MoleculesMoleculeIdRelationshipsGet<TData = Awaited<ReturnType<typeof listRelationshipsApiV1MoleculesMoleculeIdRelationshipsGet>>, TError = HTTPValidationError>(
 moleculeId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRelationshipsApiV1MoleculesMoleculeIdRelationshipsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listRelationshipsApiV1MoleculesMoleculeIdRelationshipsGet>>,
          TError,
          Awaited<ReturnType<typeof listRelationshipsApiV1MoleculesMoleculeIdRelationshipsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListRelationshipsApiV1MoleculesMoleculeIdRelationshipsGet<TData = Awaited<ReturnType<typeof listRelationshipsApiV1MoleculesMoleculeIdRelationshipsGet>>, TError = HTTPValidationError>(
 moleculeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRelationshipsApiV1MoleculesMoleculeIdRelationshipsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listRelationshipsApiV1MoleculesMoleculeIdRelationshipsGet>>,
          TError,
          Awaited<ReturnType<typeof listRelationshipsApiV1MoleculesMoleculeIdRelationshipsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListRelationshipsApiV1MoleculesMoleculeIdRelationshipsGet<TData = Awaited<ReturnType<typeof listRelationshipsApiV1MoleculesMoleculeIdRelationshipsGet>>, TError = HTTPValidationError>(
 moleculeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRelationshipsApiV1MoleculesMoleculeIdRelationshipsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Relationships
 */

export function useListRelationshipsApiV1MoleculesMoleculeIdRelationshipsGet<TData = Awaited<ReturnType<typeof listRelationshipsApiV1MoleculesMoleculeIdRelationshipsGet>>, TError = HTTPValidationError>(
 moleculeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRelationshipsApiV1MoleculesMoleculeIdRelationshipsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListRelationshipsApiV1MoleculesMoleculeIdRelationshipsGetQueryOptions(moleculeId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Delete Relationship
 */
export const deleteRelationshipApiV1MoleculesMoleculeIdRelationshipsRelationshipIdDelete = (
    moleculeId: string,
    relationshipId: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/molecules/${moleculeId}/relationships/${relationshipId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteRelationshipApiV1MoleculesMoleculeIdRelationshipsRelationshipIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRelationshipApiV1MoleculesMoleculeIdRelationshipsRelationshipIdDelete>>, TError,{moleculeId: string;relationshipId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteRelationshipApiV1MoleculesMoleculeIdRelationshipsRelationshipIdDelete>>, TError,{moleculeId: string;relationshipId: string}, TContext> => {

const mutationKey = ['deleteRelationshipApiV1MoleculesMoleculeIdRelationshipsRelationshipIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteRelationshipApiV1MoleculesMoleculeIdRelationshipsRelationshipIdDelete>>, {moleculeId: string;relationshipId: string}> = (props) => {
          const {moleculeId,relationshipId} = props ?? {};

          return  deleteRelationshipApiV1MoleculesMoleculeIdRelationshipsRelationshipIdDelete(moleculeId,relationshipId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteRelationshipApiV1MoleculesMoleculeIdRelationshipsRelationshipIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteRelationshipApiV1MoleculesMoleculeIdRelationshipsRelationshipIdDelete>>>
    
    export type DeleteRelationshipApiV1MoleculesMoleculeIdRelationshipsRelationshipIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Relationship
 */
export const useDeleteRelationshipApiV1MoleculesMoleculeIdRelationshipsRelationshipIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRelationshipApiV1MoleculesMoleculeIdRelationshipsRelationshipIdDelete>>, TError,{moleculeId: string;relationshipId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteRelationshipApiV1MoleculesMoleculeIdRelationshipsRelationshipIdDelete>>,
        TError,
        {moleculeId: string;relationshipId: string},
        TContext
      > => {

      const mutationOptions = getDeleteRelationshipApiV1MoleculesMoleculeIdRelationshipsRelationshipIdDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    