/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BodyImportRunReadoutsApiV1RunsRunIdImportReadoutsPost,
  BodyParsePlateMapFileApiV1RunsRunIdPlateSetupParsePost,
  HTTPValidationError,
  ImportReadoutsResponse,
  ImportRunReadoutsApiV1RunsRunIdImportReadoutsPostParams,
  LinkRunPlateBody,
  ParsePlateMapResponse,
  PlateMapResponse,
  RecomputeRunApiV1RunsRunIdRecomputePostBody,
  RecomputeRunResponse,
  RunPlateLinkResponse,
  SetUpRunPlateRequest,
  SetUpRunPlateResponse
} from '.././model';

import { customInstance } from '.././custom-instance';




/**
 * Upload a plate map file (CSV or XLSX) and return parsed compound assignments.

Supported layouts:
- Well-level: ``Well, Compound`` columns — one row per well.
- Row-range: ``Compound, Start Row, End Row`` columns — compound assigned
  to all wells in those rows.
 * @summary Parse Plate Map File
 */
export const parsePlateMapFileApiV1RunsRunIdPlateSetupParsePost = (
    runId: string,
    bodyParsePlateMapFileApiV1RunsRunIdPlateSetupParsePost: BodyParsePlateMapFileApiV1RunsRunIdPlateSetupParsePost,
 signal?: AbortSignal
) => {
      
      const formData = new FormData();
formData.append(`file`, bodyParsePlateMapFileApiV1RunsRunIdPlateSetupParsePost.file)

      return customInstance<ParsePlateMapResponse>(
      {url: `/api/v1/runs/${runId}/plate-setup/parse`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData, signal
    },
      );
    }
  


export const getParsePlateMapFileApiV1RunsRunIdPlateSetupParsePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof parsePlateMapFileApiV1RunsRunIdPlateSetupParsePost>>, TError,{runId: string;data: BodyParsePlateMapFileApiV1RunsRunIdPlateSetupParsePost}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof parsePlateMapFileApiV1RunsRunIdPlateSetupParsePost>>, TError,{runId: string;data: BodyParsePlateMapFileApiV1RunsRunIdPlateSetupParsePost}, TContext> => {

const mutationKey = ['parsePlateMapFileApiV1RunsRunIdPlateSetupParsePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof parsePlateMapFileApiV1RunsRunIdPlateSetupParsePost>>, {runId: string;data: BodyParsePlateMapFileApiV1RunsRunIdPlateSetupParsePost}> = (props) => {
          const {runId,data} = props ?? {};

          return  parsePlateMapFileApiV1RunsRunIdPlateSetupParsePost(runId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ParsePlateMapFileApiV1RunsRunIdPlateSetupParsePostMutationResult = NonNullable<Awaited<ReturnType<typeof parsePlateMapFileApiV1RunsRunIdPlateSetupParsePost>>>
    export type ParsePlateMapFileApiV1RunsRunIdPlateSetupParsePostMutationBody = BodyParsePlateMapFileApiV1RunsRunIdPlateSetupParsePost
    export type ParsePlateMapFileApiV1RunsRunIdPlateSetupParsePostMutationError = HTTPValidationError

    /**
 * @summary Parse Plate Map File
 */
export const useParsePlateMapFileApiV1RunsRunIdPlateSetupParsePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof parsePlateMapFileApiV1RunsRunIdPlateSetupParsePost>>, TError,{runId: string;data: BodyParsePlateMapFileApiV1RunsRunIdPlateSetupParsePost}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof parsePlateMapFileApiV1RunsRunIdPlateSetupParsePost>>,
        TError,
        {runId: string;data: BodyParsePlateMapFileApiV1RunsRunIdPlateSetupParsePost},
        TContext
      > => {

      const mutationOptions = getParsePlateMapFileApiV1RunsRunIdPlateSetupParsePostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Create wells on a run plate from compound assignments.
 * @summary Set Up Run Plate
 */
export const setUpRunPlateApiV1RunsRunIdPlateSetupPost = (
    runId: string,
    setUpRunPlateRequest: SetUpRunPlateRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<SetUpRunPlateResponse>(
      {url: `/api/v1/runs/${runId}/plate-setup`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: setUpRunPlateRequest, signal
    },
      );
    }
  


export const getSetUpRunPlateApiV1RunsRunIdPlateSetupPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setUpRunPlateApiV1RunsRunIdPlateSetupPost>>, TError,{runId: string;data: SetUpRunPlateRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof setUpRunPlateApiV1RunsRunIdPlateSetupPost>>, TError,{runId: string;data: SetUpRunPlateRequest}, TContext> => {

const mutationKey = ['setUpRunPlateApiV1RunsRunIdPlateSetupPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof setUpRunPlateApiV1RunsRunIdPlateSetupPost>>, {runId: string;data: SetUpRunPlateRequest}> = (props) => {
          const {runId,data} = props ?? {};

          return  setUpRunPlateApiV1RunsRunIdPlateSetupPost(runId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SetUpRunPlateApiV1RunsRunIdPlateSetupPostMutationResult = NonNullable<Awaited<ReturnType<typeof setUpRunPlateApiV1RunsRunIdPlateSetupPost>>>
    export type SetUpRunPlateApiV1RunsRunIdPlateSetupPostMutationBody = SetUpRunPlateRequest
    export type SetUpRunPlateApiV1RunsRunIdPlateSetupPostMutationError = HTTPValidationError

    /**
 * @summary Set Up Run Plate
 */
export const useSetUpRunPlateApiV1RunsRunIdPlateSetupPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setUpRunPlateApiV1RunsRunIdPlateSetupPost>>, TError,{runId: string;data: SetUpRunPlateRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof setUpRunPlateApiV1RunsRunIdPlateSetupPost>>,
        TError,
        {runId: string;data: SetUpRunPlateRequest},
        TContext
      > => {

      const mutationOptions = getSetUpRunPlateApiV1RunsRunIdPlateSetupPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Return structured plate map data with molecule names and concentrations.

Loads the run's plates and wells, then batch-resolves molecule names from
the chemical registration store for display.
 * @summary Get Plate Map
 */
export const getPlateMapApiV1RunsRunIdPlateMapGet = (
    runId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PlateMapResponse>(
      {url: `/api/v1/runs/${runId}/plate-map`, method: 'GET', signal
    },
      );
    }
  



export const getGetPlateMapApiV1RunsRunIdPlateMapGetQueryKey = (runId?: string,) => {
    return [
    `/api/v1/runs/${runId}/plate-map`
    ] as const;
    }

    
export const getGetPlateMapApiV1RunsRunIdPlateMapGetQueryOptions = <TData = Awaited<ReturnType<typeof getPlateMapApiV1RunsRunIdPlateMapGet>>, TError = HTTPValidationError>(runId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlateMapApiV1RunsRunIdPlateMapGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPlateMapApiV1RunsRunIdPlateMapGetQueryKey(runId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPlateMapApiV1RunsRunIdPlateMapGet>>> = ({ signal }) => getPlateMapApiV1RunsRunIdPlateMapGet(runId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(runId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPlateMapApiV1RunsRunIdPlateMapGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPlateMapApiV1RunsRunIdPlateMapGetQueryResult = NonNullable<Awaited<ReturnType<typeof getPlateMapApiV1RunsRunIdPlateMapGet>>>
export type GetPlateMapApiV1RunsRunIdPlateMapGetQueryError = HTTPValidationError


export function useGetPlateMapApiV1RunsRunIdPlateMapGet<TData = Awaited<ReturnType<typeof getPlateMapApiV1RunsRunIdPlateMapGet>>, TError = HTTPValidationError>(
 runId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlateMapApiV1RunsRunIdPlateMapGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlateMapApiV1RunsRunIdPlateMapGet>>,
          TError,
          Awaited<ReturnType<typeof getPlateMapApiV1RunsRunIdPlateMapGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPlateMapApiV1RunsRunIdPlateMapGet<TData = Awaited<ReturnType<typeof getPlateMapApiV1RunsRunIdPlateMapGet>>, TError = HTTPValidationError>(
 runId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlateMapApiV1RunsRunIdPlateMapGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlateMapApiV1RunsRunIdPlateMapGet>>,
          TError,
          Awaited<ReturnType<typeof getPlateMapApiV1RunsRunIdPlateMapGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPlateMapApiV1RunsRunIdPlateMapGet<TData = Awaited<ReturnType<typeof getPlateMapApiV1RunsRunIdPlateMapGet>>, TError = HTTPValidationError>(
 runId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlateMapApiV1RunsRunIdPlateMapGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Plate Map
 */

export function useGetPlateMapApiV1RunsRunIdPlateMapGet<TData = Awaited<ReturnType<typeof getPlateMapApiV1RunsRunIdPlateMapGet>>, TError = HTTPValidationError>(
 runId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlateMapApiV1RunsRunIdPlateMapGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPlateMapApiV1RunsRunIdPlateMapGetQueryOptions(runId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Point a run plate at the physical inventory plate it was run on.

``barcode`` accepts a barcode or a plate label. Relinking overwrites.
 * @summary Link Run Plate
 */
export const linkRunPlateApiV1RunsRunIdPlatesPlateIdLinkPost = (
    runId: string,
    plateId: string,
    linkRunPlateBody: LinkRunPlateBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<RunPlateLinkResponse>(
      {url: `/api/v1/runs/${runId}/plates/${plateId}:link`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: linkRunPlateBody, signal
    },
      );
    }
  


export const getLinkRunPlateApiV1RunsRunIdPlatesPlateIdLinkPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof linkRunPlateApiV1RunsRunIdPlatesPlateIdLinkPost>>, TError,{runId: string;plateId: string;data: LinkRunPlateBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof linkRunPlateApiV1RunsRunIdPlatesPlateIdLinkPost>>, TError,{runId: string;plateId: string;data: LinkRunPlateBody}, TContext> => {

const mutationKey = ['linkRunPlateApiV1RunsRunIdPlatesPlateIdLinkPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof linkRunPlateApiV1RunsRunIdPlatesPlateIdLinkPost>>, {runId: string;plateId: string;data: LinkRunPlateBody}> = (props) => {
          const {runId,plateId,data} = props ?? {};

          return  linkRunPlateApiV1RunsRunIdPlatesPlateIdLinkPost(runId,plateId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LinkRunPlateApiV1RunsRunIdPlatesPlateIdLinkPostMutationResult = NonNullable<Awaited<ReturnType<typeof linkRunPlateApiV1RunsRunIdPlatesPlateIdLinkPost>>>
    export type LinkRunPlateApiV1RunsRunIdPlatesPlateIdLinkPostMutationBody = LinkRunPlateBody
    export type LinkRunPlateApiV1RunsRunIdPlatesPlateIdLinkPostMutationError = HTTPValidationError

    /**
 * @summary Link Run Plate
 */
export const useLinkRunPlateApiV1RunsRunIdPlatesPlateIdLinkPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof linkRunPlateApiV1RunsRunIdPlatesPlateIdLinkPost>>, TError,{runId: string;plateId: string;data: LinkRunPlateBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof linkRunPlateApiV1RunsRunIdPlatesPlateIdLinkPost>>,
        TError,
        {runId: string;plateId: string;data: LinkRunPlateBody},
        TContext
      > => {

      const mutationOptions = getLinkRunPlateApiV1RunsRunIdPlatesPlateIdLinkPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Clear a run plate's inventory link.
 * @summary Unlink Run Plate
 */
export const unlinkRunPlateApiV1RunsRunIdPlatesPlateIdUnlinkPost = (
    runId: string,
    plateId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<RunPlateLinkResponse>(
      {url: `/api/v1/runs/${runId}/plates/${plateId}:unlink`, method: 'POST', signal
    },
      );
    }
  


export const getUnlinkRunPlateApiV1RunsRunIdPlatesPlateIdUnlinkPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unlinkRunPlateApiV1RunsRunIdPlatesPlateIdUnlinkPost>>, TError,{runId: string;plateId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof unlinkRunPlateApiV1RunsRunIdPlatesPlateIdUnlinkPost>>, TError,{runId: string;plateId: string}, TContext> => {

const mutationKey = ['unlinkRunPlateApiV1RunsRunIdPlatesPlateIdUnlinkPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof unlinkRunPlateApiV1RunsRunIdPlatesPlateIdUnlinkPost>>, {runId: string;plateId: string}> = (props) => {
          const {runId,plateId} = props ?? {};

          return  unlinkRunPlateApiV1RunsRunIdPlatesPlateIdUnlinkPost(runId,plateId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UnlinkRunPlateApiV1RunsRunIdPlatesPlateIdUnlinkPostMutationResult = NonNullable<Awaited<ReturnType<typeof unlinkRunPlateApiV1RunsRunIdPlatesPlateIdUnlinkPost>>>
    
    export type UnlinkRunPlateApiV1RunsRunIdPlatesPlateIdUnlinkPostMutationError = HTTPValidationError

    /**
 * @summary Unlink Run Plate
 */
export const useUnlinkRunPlateApiV1RunsRunIdPlatesPlateIdUnlinkPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unlinkRunPlateApiV1RunsRunIdPlatesPlateIdUnlinkPost>>, TError,{runId: string;plateId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof unlinkRunPlateApiV1RunsRunIdPlatesPlateIdUnlinkPost>>,
        TError,
        {runId: string;plateId: string},
        TContext
      > => {

      const mutationOptions = getUnlinkRunPlateApiV1RunsRunIdPlatesPlateIdUnlinkPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Import readout data from a CSV or XLSX into a run that already has wells set up.

Wells must have been created via the plate-setup endpoint first.
After import, the readout calculation engine runs automatically to
normalize, aggregate, and fit dose-response curves.

Supported layouts:
- Single-value: ``Well, Value`` columns with ``readout_definition_id`` query param.
- Multi-column: ``Well, <ReadoutDefName1>, <ReadoutDefName2>, ...`` — headers
  matched case-insensitively to readout definition names.
- Grid (``layout=grid``): a plate matrix (column numbers across the top, row
  letters down the side) for a single ``readout_definition_id``; reshaped to
  ``Well, Value`` before import.
 * @summary Import Run Readouts
 */
export const importRunReadoutsApiV1RunsRunIdImportReadoutsPost = (
    runId: string,
    bodyImportRunReadoutsApiV1RunsRunIdImportReadoutsPost: BodyImportRunReadoutsApiV1RunsRunIdImportReadoutsPost,
    params?: ImportRunReadoutsApiV1RunsRunIdImportReadoutsPostParams,
 signal?: AbortSignal
) => {
      
      const formData = new FormData();
formData.append(`file`, bodyImportRunReadoutsApiV1RunsRunIdImportReadoutsPost.file)

      return customInstance<ImportReadoutsResponse>(
      {url: `/api/v1/runs/${runId}/import-readouts`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData,
        params, signal
    },
      );
    }
  


export const getImportRunReadoutsApiV1RunsRunIdImportReadoutsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof importRunReadoutsApiV1RunsRunIdImportReadoutsPost>>, TError,{runId: string;data: BodyImportRunReadoutsApiV1RunsRunIdImportReadoutsPost;params?: ImportRunReadoutsApiV1RunsRunIdImportReadoutsPostParams}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof importRunReadoutsApiV1RunsRunIdImportReadoutsPost>>, TError,{runId: string;data: BodyImportRunReadoutsApiV1RunsRunIdImportReadoutsPost;params?: ImportRunReadoutsApiV1RunsRunIdImportReadoutsPostParams}, TContext> => {

const mutationKey = ['importRunReadoutsApiV1RunsRunIdImportReadoutsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof importRunReadoutsApiV1RunsRunIdImportReadoutsPost>>, {runId: string;data: BodyImportRunReadoutsApiV1RunsRunIdImportReadoutsPost;params?: ImportRunReadoutsApiV1RunsRunIdImportReadoutsPostParams}> = (props) => {
          const {runId,data,params} = props ?? {};

          return  importRunReadoutsApiV1RunsRunIdImportReadoutsPost(runId,data,params,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ImportRunReadoutsApiV1RunsRunIdImportReadoutsPostMutationResult = NonNullable<Awaited<ReturnType<typeof importRunReadoutsApiV1RunsRunIdImportReadoutsPost>>>
    export type ImportRunReadoutsApiV1RunsRunIdImportReadoutsPostMutationBody = BodyImportRunReadoutsApiV1RunsRunIdImportReadoutsPost
    export type ImportRunReadoutsApiV1RunsRunIdImportReadoutsPostMutationError = HTTPValidationError

    /**
 * @summary Import Run Readouts
 */
export const useImportRunReadoutsApiV1RunsRunIdImportReadoutsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof importRunReadoutsApiV1RunsRunIdImportReadoutsPost>>, TError,{runId: string;data: BodyImportRunReadoutsApiV1RunsRunIdImportReadoutsPost;params?: ImportRunReadoutsApiV1RunsRunIdImportReadoutsPostParams}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof importRunReadoutsApiV1RunsRunIdImportReadoutsPost>>,
        TError,
        {runId: string;data: BodyImportRunReadoutsApiV1RunsRunIdImportReadoutsPost;params?: ImportRunReadoutsApiV1RunsRunIdImportReadoutsPostParams},
        TContext
      > => {

      const mutationOptions = getImportRunReadoutsApiV1RunsRunIdImportReadoutsPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Re-run the readout calculation pipeline on a run's existing raw data.

Idempotent: the engine deletes previously-computed readouts and
dose-response curves before recomputing. Useful when a normalization
formula or computed readout definition has changed and the persisted
computed values need to be regenerated without re-importing the file.

The optional body allows transient per-run constraint overrides on the
dose-response fits (top/bottom plateau bounds, hill slope). Overrides
apply to this recompute pass only and are not stored.
 * @summary Recompute Run
 */
export const recomputeRunApiV1RunsRunIdRecomputePost = (
    runId: string,
    recomputeRunApiV1RunsRunIdRecomputePostBody: RecomputeRunApiV1RunsRunIdRecomputePostBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<RecomputeRunResponse>(
      {url: `/api/v1/runs/${runId}/recompute`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: recomputeRunApiV1RunsRunIdRecomputePostBody, signal
    },
      );
    }
  


export const getRecomputeRunApiV1RunsRunIdRecomputePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof recomputeRunApiV1RunsRunIdRecomputePost>>, TError,{runId: string;data: RecomputeRunApiV1RunsRunIdRecomputePostBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof recomputeRunApiV1RunsRunIdRecomputePost>>, TError,{runId: string;data: RecomputeRunApiV1RunsRunIdRecomputePostBody}, TContext> => {

const mutationKey = ['recomputeRunApiV1RunsRunIdRecomputePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof recomputeRunApiV1RunsRunIdRecomputePost>>, {runId: string;data: RecomputeRunApiV1RunsRunIdRecomputePostBody}> = (props) => {
          const {runId,data} = props ?? {};

          return  recomputeRunApiV1RunsRunIdRecomputePost(runId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RecomputeRunApiV1RunsRunIdRecomputePostMutationResult = NonNullable<Awaited<ReturnType<typeof recomputeRunApiV1RunsRunIdRecomputePost>>>
    export type RecomputeRunApiV1RunsRunIdRecomputePostMutationBody = RecomputeRunApiV1RunsRunIdRecomputePostBody
    export type RecomputeRunApiV1RunsRunIdRecomputePostMutationError = HTTPValidationError

    /**
 * @summary Recompute Run
 */
export const useRecomputeRunApiV1RunsRunIdRecomputePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof recomputeRunApiV1RunsRunIdRecomputePost>>, TError,{runId: string;data: RecomputeRunApiV1RunsRunIdRecomputePostBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof recomputeRunApiV1RunsRunIdRecomputePost>>,
        TError,
        {runId: string;data: RecomputeRunApiV1RunsRunIdRecomputePostBody},
        TContext
      > => {

      const mutationOptions = getRecomputeRunApiV1RunsRunIdRecomputePostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    