/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AttachableType,
  AttachmentResponse,
  BodyUploadAttachmentApiV1EntityTypeEntityIdAttachmentsPost,
  HTTPValidationError
} from '.././model';

import { customInstance } from '.././custom-instance';




/**
 * @summary Upload Attachment
 */
export const uploadAttachmentApiV1EntityTypeEntityIdAttachmentsPost = (
    entityType: AttachableType,
    entityId: string,
    bodyUploadAttachmentApiV1EntityTypeEntityIdAttachmentsPost: BodyUploadAttachmentApiV1EntityTypeEntityIdAttachmentsPost,
 signal?: AbortSignal
) => {
      
      const formData = new FormData();
formData.append(`file`, bodyUploadAttachmentApiV1EntityTypeEntityIdAttachmentsPost.file)

      return customInstance<AttachmentResponse>(
      {url: `/api/v1/${entityType}/${entityId}/attachments`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData, signal
    },
      );
    }
  


export const getUploadAttachmentApiV1EntityTypeEntityIdAttachmentsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadAttachmentApiV1EntityTypeEntityIdAttachmentsPost>>, TError,{entityType: AttachableType;entityId: string;data: BodyUploadAttachmentApiV1EntityTypeEntityIdAttachmentsPost}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof uploadAttachmentApiV1EntityTypeEntityIdAttachmentsPost>>, TError,{entityType: AttachableType;entityId: string;data: BodyUploadAttachmentApiV1EntityTypeEntityIdAttachmentsPost}, TContext> => {

const mutationKey = ['uploadAttachmentApiV1EntityTypeEntityIdAttachmentsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadAttachmentApiV1EntityTypeEntityIdAttachmentsPost>>, {entityType: AttachableType;entityId: string;data: BodyUploadAttachmentApiV1EntityTypeEntityIdAttachmentsPost}> = (props) => {
          const {entityType,entityId,data} = props ?? {};

          return  uploadAttachmentApiV1EntityTypeEntityIdAttachmentsPost(entityType,entityId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UploadAttachmentApiV1EntityTypeEntityIdAttachmentsPostMutationResult = NonNullable<Awaited<ReturnType<typeof uploadAttachmentApiV1EntityTypeEntityIdAttachmentsPost>>>
    export type UploadAttachmentApiV1EntityTypeEntityIdAttachmentsPostMutationBody = BodyUploadAttachmentApiV1EntityTypeEntityIdAttachmentsPost
    export type UploadAttachmentApiV1EntityTypeEntityIdAttachmentsPostMutationError = HTTPValidationError

    /**
 * @summary Upload Attachment
 */
export const useUploadAttachmentApiV1EntityTypeEntityIdAttachmentsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadAttachmentApiV1EntityTypeEntityIdAttachmentsPost>>, TError,{entityType: AttachableType;entityId: string;data: BodyUploadAttachmentApiV1EntityTypeEntityIdAttachmentsPost}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadAttachmentApiV1EntityTypeEntityIdAttachmentsPost>>,
        TError,
        {entityType: AttachableType;entityId: string;data: BodyUploadAttachmentApiV1EntityTypeEntityIdAttachmentsPost},
        TContext
      > => {

      const mutationOptions = getUploadAttachmentApiV1EntityTypeEntityIdAttachmentsPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List Attachments
 */
export const listAttachmentsApiV1EntityTypeEntityIdAttachmentsGet = (
    entityType: AttachableType,
    entityId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<AttachmentResponse[]>(
      {url: `/api/v1/${entityType}/${entityId}/attachments`, method: 'GET', signal
    },
      );
    }
  



export const getListAttachmentsApiV1EntityTypeEntityIdAttachmentsGetQueryKey = (entityType?: AttachableType,
    entityId?: string,) => {
    return [
    `/api/v1/${entityType}/${entityId}/attachments`
    ] as const;
    }

    
export const getListAttachmentsApiV1EntityTypeEntityIdAttachmentsGetQueryOptions = <TData = Awaited<ReturnType<typeof listAttachmentsApiV1EntityTypeEntityIdAttachmentsGet>>, TError = HTTPValidationError>(entityType: AttachableType,
    entityId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAttachmentsApiV1EntityTypeEntityIdAttachmentsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAttachmentsApiV1EntityTypeEntityIdAttachmentsGetQueryKey(entityType,entityId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAttachmentsApiV1EntityTypeEntityIdAttachmentsGet>>> = ({ signal }) => listAttachmentsApiV1EntityTypeEntityIdAttachmentsGet(entityType,entityId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(entityType && entityId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAttachmentsApiV1EntityTypeEntityIdAttachmentsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAttachmentsApiV1EntityTypeEntityIdAttachmentsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listAttachmentsApiV1EntityTypeEntityIdAttachmentsGet>>>
export type ListAttachmentsApiV1EntityTypeEntityIdAttachmentsGetQueryError = HTTPValidationError


export function useListAttachmentsApiV1EntityTypeEntityIdAttachmentsGet<TData = Awaited<ReturnType<typeof listAttachmentsApiV1EntityTypeEntityIdAttachmentsGet>>, TError = HTTPValidationError>(
 entityType: AttachableType,
    entityId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAttachmentsApiV1EntityTypeEntityIdAttachmentsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAttachmentsApiV1EntityTypeEntityIdAttachmentsGet>>,
          TError,
          Awaited<ReturnType<typeof listAttachmentsApiV1EntityTypeEntityIdAttachmentsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAttachmentsApiV1EntityTypeEntityIdAttachmentsGet<TData = Awaited<ReturnType<typeof listAttachmentsApiV1EntityTypeEntityIdAttachmentsGet>>, TError = HTTPValidationError>(
 entityType: AttachableType,
    entityId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAttachmentsApiV1EntityTypeEntityIdAttachmentsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAttachmentsApiV1EntityTypeEntityIdAttachmentsGet>>,
          TError,
          Awaited<ReturnType<typeof listAttachmentsApiV1EntityTypeEntityIdAttachmentsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAttachmentsApiV1EntityTypeEntityIdAttachmentsGet<TData = Awaited<ReturnType<typeof listAttachmentsApiV1EntityTypeEntityIdAttachmentsGet>>, TError = HTTPValidationError>(
 entityType: AttachableType,
    entityId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAttachmentsApiV1EntityTypeEntityIdAttachmentsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Attachments
 */

export function useListAttachmentsApiV1EntityTypeEntityIdAttachmentsGet<TData = Awaited<ReturnType<typeof listAttachmentsApiV1EntityTypeEntityIdAttachmentsGet>>, TError = HTTPValidationError>(
 entityType: AttachableType,
    entityId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAttachmentsApiV1EntityTypeEntityIdAttachmentsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAttachmentsApiV1EntityTypeEntityIdAttachmentsGetQueryOptions(entityType,entityId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Download Attachment
 */
export const downloadAttachmentApiV1AttachmentsAttachmentIdDownloadGet = (
    attachmentId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/attachments/${attachmentId}/download`, method: 'GET', signal
    },
      );
    }
  



export const getDownloadAttachmentApiV1AttachmentsAttachmentIdDownloadGetQueryKey = (attachmentId?: string,) => {
    return [
    `/api/v1/attachments/${attachmentId}/download`
    ] as const;
    }

    
export const getDownloadAttachmentApiV1AttachmentsAttachmentIdDownloadGetQueryOptions = <TData = Awaited<ReturnType<typeof downloadAttachmentApiV1AttachmentsAttachmentIdDownloadGet>>, TError = HTTPValidationError>(attachmentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadAttachmentApiV1AttachmentsAttachmentIdDownloadGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDownloadAttachmentApiV1AttachmentsAttachmentIdDownloadGetQueryKey(attachmentId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadAttachmentApiV1AttachmentsAttachmentIdDownloadGet>>> = ({ signal }) => downloadAttachmentApiV1AttachmentsAttachmentIdDownloadGet(attachmentId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(attachmentId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof downloadAttachmentApiV1AttachmentsAttachmentIdDownloadGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DownloadAttachmentApiV1AttachmentsAttachmentIdDownloadGetQueryResult = NonNullable<Awaited<ReturnType<typeof downloadAttachmentApiV1AttachmentsAttachmentIdDownloadGet>>>
export type DownloadAttachmentApiV1AttachmentsAttachmentIdDownloadGetQueryError = HTTPValidationError


export function useDownloadAttachmentApiV1AttachmentsAttachmentIdDownloadGet<TData = Awaited<ReturnType<typeof downloadAttachmentApiV1AttachmentsAttachmentIdDownloadGet>>, TError = HTTPValidationError>(
 attachmentId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadAttachmentApiV1AttachmentsAttachmentIdDownloadGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadAttachmentApiV1AttachmentsAttachmentIdDownloadGet>>,
          TError,
          Awaited<ReturnType<typeof downloadAttachmentApiV1AttachmentsAttachmentIdDownloadGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadAttachmentApiV1AttachmentsAttachmentIdDownloadGet<TData = Awaited<ReturnType<typeof downloadAttachmentApiV1AttachmentsAttachmentIdDownloadGet>>, TError = HTTPValidationError>(
 attachmentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadAttachmentApiV1AttachmentsAttachmentIdDownloadGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadAttachmentApiV1AttachmentsAttachmentIdDownloadGet>>,
          TError,
          Awaited<ReturnType<typeof downloadAttachmentApiV1AttachmentsAttachmentIdDownloadGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadAttachmentApiV1AttachmentsAttachmentIdDownloadGet<TData = Awaited<ReturnType<typeof downloadAttachmentApiV1AttachmentsAttachmentIdDownloadGet>>, TError = HTTPValidationError>(
 attachmentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadAttachmentApiV1AttachmentsAttachmentIdDownloadGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Download Attachment
 */

export function useDownloadAttachmentApiV1AttachmentsAttachmentIdDownloadGet<TData = Awaited<ReturnType<typeof downloadAttachmentApiV1AttachmentsAttachmentIdDownloadGet>>, TError = HTTPValidationError>(
 attachmentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadAttachmentApiV1AttachmentsAttachmentIdDownloadGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDownloadAttachmentApiV1AttachmentsAttachmentIdDownloadGetQueryOptions(attachmentId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Delete Attachment
 */
export const deleteAttachmentApiV1AttachmentsAttachmentIdDelete = (
    attachmentId: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/attachments/${attachmentId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteAttachmentApiV1AttachmentsAttachmentIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAttachmentApiV1AttachmentsAttachmentIdDelete>>, TError,{attachmentId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteAttachmentApiV1AttachmentsAttachmentIdDelete>>, TError,{attachmentId: string}, TContext> => {

const mutationKey = ['deleteAttachmentApiV1AttachmentsAttachmentIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAttachmentApiV1AttachmentsAttachmentIdDelete>>, {attachmentId: string}> = (props) => {
          const {attachmentId} = props ?? {};

          return  deleteAttachmentApiV1AttachmentsAttachmentIdDelete(attachmentId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAttachmentApiV1AttachmentsAttachmentIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAttachmentApiV1AttachmentsAttachmentIdDelete>>>
    
    export type DeleteAttachmentApiV1AttachmentsAttachmentIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Attachment
 */
export const useDeleteAttachmentApiV1AttachmentsAttachmentIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAttachmentApiV1AttachmentsAttachmentIdDelete>>, TError,{attachmentId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAttachmentApiV1AttachmentsAttachmentIdDelete>>,
        TError,
        {attachmentId: string},
        TContext
      > => {

      const mutationOptions = getDeleteAttachmentApiV1AttachmentsAttachmentIdDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    