/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Chem-Vault
 * OpenAPI spec version: 0.1.0
 */
import type { AddChannelRequestQcFilter } from './addChannelRequestQcFilter';
import type { AddChannelRequestHitThreshold } from './addChannelRequestHitThreshold';

export interface AddChannelRequest {
  label: string;
  protocol_id: string;
  readout_definition_id: string;
  source_kind: string;
  selection_rule: string;
  qualifier_handling: string;
  qc_filter?: AddChannelRequestQcFilter;
  hit_threshold?: AddChannelRequestHitThreshold;
  display_order?: number;
}
