/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { CommentTarget } from './commentTarget';
import type { AddCommentBodyLoanId } from './addCommentBodyLoanId';

export interface AddCommentBody {
  target_type: CommentTarget;
  target_id: string;
  /**
   * @minLength 1
   * @maxLength 5000
   */
  body: string;
  loan_id?: AddCommentBodyLoanId;
}
