/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 1.1.0-14-gdd8a8c7e-dirty
 */
import type { AddChannelRequestQcFilter } from './addChannelRequestQcFilter';
import type { AddChannelRequestNormalizationApplied } from './addChannelRequestNormalizationApplied';
import type { AddChannelRequestInterceptKey } from './addChannelRequestInterceptKey';

export interface AddChannelRequest {
  label: string;
  protocol_id: string;
  readout_definition_id: string;
  source_kind: string;
  selection_rule: string;
  qualifier_handling: string;
  qc_filter?: AddChannelRequestQcFilter;
  display_order?: number;
  normalization_applied?: AddChannelRequestNormalizationApplied;
  intercept_key?: AddChannelRequestInterceptKey;
}
