/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Chem-Vault
 * OpenAPI spec version: 0.1.0
 */
import type { AuditEntryResponseOldValue } from './auditEntryResponseOldValue';
import type { AuditEntryResponseNewValue } from './auditEntryResponseNewValue';

export interface AuditEntryResponse {
  id: string;
  field_name: string;
  old_value: AuditEntryResponseOldValue;
  new_value: AuditEntryResponseNewValue;
  entry_type: string;
}
