/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 1.2.0-dirty
 */
import type { BodyStartBulkRegistrationApiV1BulkRegistrationsPostCreateBatchOnDuplicate } from './bodyStartBulkRegistrationApiV1BulkRegistrationsPostCreateBatchOnDuplicate';

export interface BodyStartBulkRegistrationApiV1BulkRegistrationsPost {
  file: string;
  originating_org_id: string;
  file_format: string;
  create_batch_on_duplicate?: BodyStartBulkRegistrationApiV1BulkRegistrationsPostCreateBatchOnDuplicate;
  project_ids?: string[];
}
