/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Chem-Vault
 * OpenAPI spec version: 0.1.0
 */

export interface BodyStartBulkRegistrationApiV1BulkRegistrationsPost {
  file: string;
  originating_org_id: string;
  file_format: string;
}
