/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { BulkRegistrationItemResponse } from './bulkRegistrationItemResponse';

export interface BulkRegistrationResponse {
  id: string;
  status: string;
  total_count: number;
  registered_count: number;
  duplicate_count: number;
  error_count: number;
  items: BulkRegistrationItemResponse[];
}
