/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { BulkRegistrationStatusResponseMergeCandidatesItem } from './bulkRegistrationStatusResponseMergeCandidatesItem';

export interface BulkRegistrationStatusResponse {
  bulk_reg_id: string;
  status: string;
  total_count: number;
  registered_count: number;
  duplicate_count: number;
  error_count: number;
  disclosed_count?: number;
  merge_candidate_count?: number;
  conflict_count?: number;
  merge_candidates?: BulkRegistrationStatusResponseMergeCandidatesItem[];
  chunks_processed: number;
  chunks_total: number;
}
