/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { BulkReadoutDataItemWellId } from './bulkReadoutDataItemWellId';
import type { BulkReadoutDataItemMoleculeId } from './bulkReadoutDataItemMoleculeId';
import type { BulkReadoutDataItemBatchId } from './bulkReadoutDataItemBatchId';
import type { BulkReadoutDataItemReadoutDefinitionId } from './bulkReadoutDataItemReadoutDefinitionId';
import type { BulkReadoutDataItemRegistrationNumber } from './bulkReadoutDataItemRegistrationNumber';
import type { BulkReadoutDataItemBatchNumber } from './bulkReadoutDataItemBatchNumber';
import type { BulkReadoutDataItemReadoutDefinitionName } from './bulkReadoutDataItemReadoutDefinitionName';
import type { BulkReadoutDataItemValueNumeric } from './bulkReadoutDataItemValueNumeric';
import type { BulkReadoutDataItemValueQualifier } from './bulkReadoutDataItemValueQualifier';
import type { BulkReadoutDataItemValueText } from './bulkReadoutDataItemValueText';

/**
 * Request item for bulk readout import.

Supports both UUID-based references (molecule_id, batch_id,
readout_definition_id) and human-readable alternatives
(registration_number, batch_number, readout_definition_name).
When both are provided, the UUID takes precedence.
 */
export interface BulkReadoutDataItem {
  run_id: string;
  well_id?: BulkReadoutDataItemWellId;
  molecule_id?: BulkReadoutDataItemMoleculeId;
  batch_id?: BulkReadoutDataItemBatchId;
  readout_definition_id?: BulkReadoutDataItemReadoutDefinitionId;
  registration_number?: BulkReadoutDataItemRegistrationNumber;
  batch_number?: BulkReadoutDataItemBatchNumber;
  readout_definition_name?: BulkReadoutDataItemReadoutDefinitionName;
  value_numeric?: BulkReadoutDataItemValueNumeric;
  value_qualifier?: BulkReadoutDataItemValueQualifier;
  value_text?: BulkReadoutDataItemValueText;
  is_outlier?: boolean;
}
