/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { BulkAddRowBody } from './bulkAddRowBody';
import type { BulkAddRequestBodyTemplateId } from './bulkAddRequestBodyTemplateId';
import type { BulkAddRequestBodyPreviewId } from './bulkAddRequestBodyPreviewId';

export interface BulkAddRequestBody {
  rows: BulkAddRowBody[];
  template_id?: BulkAddRequestBodyTemplateId;
  preview_id?: BulkAddRequestBodyPreviewId;
}
