/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 1.1.0-14-gdd8a8c7e-dirty
 */
import type { CampaignResultResponseRepresentativeBatchId } from './campaignResultResponseRepresentativeBatchId';
import type { CampaignResultResponseNotes } from './campaignResultResponseNotes';
import type { CampaignMeasurementResponse } from './campaignMeasurementResponse';
import type { StageOutcomeResponse } from './stageOutcomeResponse';

export interface CampaignResultResponse {
  id: string;
  molecule_id: string;
  representative_batch_id?: CampaignResultResponseRepresentativeBatchId;
  notes?: CampaignResultResponseNotes;
  measurements: CampaignMeasurementResponse[];
  stage_outcomes: StageOutcomeResponse[];
}
