/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { CddMoleculeImportSummaryWorkflowId } from './cddMoleculeImportSummaryWorkflowId';
import type { CddMoleculeImportSummaryCompletedAt } from './cddMoleculeImportSummaryCompletedAt';

export interface CddMoleculeImportSummary {
  id: string;
  cdd_vault_id: string;
  import_mode: string;
  status: string;
  workflow_id: CddMoleculeImportSummaryWorkflowId;
  total_count: number;
  registered_count: number;
  duplicate_count: number;
  error_count: number;
  skipped_count: number;
  submitted_at: string;
  completed_at: CddMoleculeImportSummaryCompletedAt;
}
