/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */

export interface CddMoleculeImportStatusResponse {
  import_id: string;
  status: string;
  total_count: number;
  registered_count: number;
  duplicate_count: number;
  error_count: number;
  skipped_count: number;
  current_offset: number;
  pages_processed: number;
}
