/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Chem-Vault
 * OpenAPI spec version: 0.1.0
 */

export interface CddPlateImportStatusResponse {
  import_id: string;
  status: string;
  total_count: number;
  plates_registered: number;
  plates_duplicate: number;
  plates_error: number;
  wells_mapped: number;
  wells_unresolved: number;
  current_offset: number;
  pages_processed: number;
}
