/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { CellarInterfaceRoutesBatchesRowOutcomeResponseBatchId } from './cellarInterfaceRoutesBatchesRowOutcomeResponseBatchId';
import type { CellarInterfaceRoutesBatchesRowOutcomeResponseResolvedBatchNumber } from './cellarInterfaceRoutesBatchesRowOutcomeResponseResolvedBatchNumber';
import type { CellarInterfaceRoutesBatchesRowOutcomeResponseConflictBatchId } from './cellarInterfaceRoutesBatchesRowOutcomeResponseConflictBatchId';
import type { CellarInterfaceRoutesBatchesRowOutcomeResponseConflictBatchNumber } from './cellarInterfaceRoutesBatchesRowOutcomeResponseConflictBatchNumber';
import type { CellarInterfaceRoutesBatchesRowOutcomeResponseMessage } from './cellarInterfaceRoutesBatchesRowOutcomeResponseMessage';

export interface CellarInterfaceRoutesBatchesRowOutcomeResponse {
  row_index: number;
  status: string;
  external_identifier: string;
  batch_id?: CellarInterfaceRoutesBatchesRowOutcomeResponseBatchId;
  resolved_batch_number?: CellarInterfaceRoutesBatchesRowOutcomeResponseResolvedBatchNumber;
  created?: boolean;
  conflict_batch_id?: CellarInterfaceRoutesBatchesRowOutcomeResponseConflictBatchId;
  conflict_batch_number?: CellarInterfaceRoutesBatchesRowOutcomeResponseConflictBatchNumber;
  message?: CellarInterfaceRoutesBatchesRowOutcomeResponseMessage;
}
