/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Chem-Vault
 * OpenAPI spec version: 0.1.0
 */

export interface ChemVaultInterfaceRoutesSynthesisRequestsFulfillRequest {
  batch_id: string;
}
