/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { CloseCampaignRequestSignatureMeaning } from './closeCampaignRequestSignatureMeaning';
import type { CloseCampaignRequestPublishesCollection } from './closeCampaignRequestPublishesCollection';

export interface CloseCampaignRequest {
  signature_id: string;
  signature_meaning?: CloseCampaignRequestSignatureMeaning;
  publishes_collection?: CloseCampaignRequestPublishesCollection;
}
