/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { CollectionImportTemplateResponseDescription } from './collectionImportTemplateResponseDescription';
import type { CollectionImportTemplateResponseColumnMapping } from './collectionImportTemplateResponseColumnMapping';
import type { CollectionImportTemplateResponseUpdatedAt } from './collectionImportTemplateResponseUpdatedAt';

export interface CollectionImportTemplateResponse {
  id: string;
  workspace_id: string;
  name: string;
  description: CollectionImportTemplateResponseDescription;
  column_mapping: CollectionImportTemplateResponseColumnMapping;
  created_by: string;
  created_at: string;
  updated_at: CollectionImportTemplateResponseUpdatedAt;
  used_in_this_collection?: boolean;
}
