/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { CommentTarget } from './commentTarget';
import type { CommentResponseLoanId } from './commentResponseLoanId';
import type { CommentResponseAuthorId } from './commentResponseAuthorId';

export interface CommentResponse {
  id: string;
  target_type: CommentTarget;
  target_id: string;
  loan_id?: CommentResponseLoanId;
  body: string;
  author_id?: CommentResponseAuthorId;
  author_name: string;
  created_at: string;
}
