/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 1.1.0-103-g192b27ac-dirty
 */
import type { ComputeMcsBodyCollectionId } from './computeMcsBodyCollectionId';
import type { ComputeMcsBodyMoleculeIds } from './computeMcsBodyMoleculeIds';

/**
 * Exactly one of ``collection_id`` or ``molecule_ids`` must be supplied.
 */
export interface ComputeMcsBody {
  collection_id?: ComputeMcsBodyCollectionId;
  molecule_ids?: ComputeMcsBodyMoleculeIds;
}
