/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 1.1.0-103-g192b27ac-dirty
 */
import type { McsResultDto } from './mcsResultDto';

export type ComputeMcsResponseResult = McsResultDto | null;
