/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Chem-Vault
 * OpenAPI spec version: 0.1.0
 */
import type { CompoundAssignmentResponseBatchRef } from './compoundAssignmentResponseBatchRef';

export interface CompoundAssignmentResponse {
  molecule_ref: string;
  batch_ref?: CompoundAssignmentResponseBatchRef;
  well_positions: string[];
}
