/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { CreateCampaignRequestDescription } from './createCampaignRequestDescription';
import type { CreateCampaignRequestSupersedesCampaignId } from './createCampaignRequestSupersedesCampaignId';

export interface CreateCampaignRequest {
  name: string;
  description?: CreateCampaignRequestDescription;
  project_id: string;
  publishes_collection?: boolean;
  supersedes_campaign_id?: CreateCampaignRequestSupersedesCampaignId;
}
