/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { CreateProjectBodyDescription } from './createProjectBodyDescription';

export interface CreateProjectBody {
  name: string;
  description?: CreateProjectBodyDescription;
}
