/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Chem-Vault
 * OpenAPI spec version: 0.1.0
 */
import type { PlateFormat } from './plateFormat';
import type { CreatePlateTemplateBodyTemplateMap } from './createPlateTemplateBodyTemplateMap';
import type { CreatePlateTemplateBodyDescription } from './createPlateTemplateBodyDescription';

export interface CreatePlateTemplateBody {
  name: string;
  format: PlateFormat;
  template_map: CreatePlateTemplateBodyTemplateMap;
  description?: CreatePlateTemplateBodyDescription;
}
