/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { CreateFlagRequestNote } from './createFlagRequestNote';

export interface CreateFlagRequest {
  molecule_id: string;
  flag_type?: string;
  note?: CreateFlagRequestNote;
}
