/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { CreateImportTemplateBodyColumnMappings } from './createImportTemplateBodyColumnMappings';
import type { CreateImportTemplateBodyDescription } from './createImportTemplateBodyDescription';
import type { CreateImportTemplateBodyDefaultProtocolId } from './createImportTemplateBodyDefaultProtocolId';

export interface CreateImportTemplateBody {
  name: string;
  column_mappings: CreateImportTemplateBodyColumnMappings;
  description?: CreateImportTemplateBodyDescription;
  default_protocol_id?: CreateImportTemplateBodyDefaultProtocolId;
}
