/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 1.3.0-17-gd9da37bb-dirty
 */
import type { CreateProtocolFormBodyDescription } from './createProtocolFormBodyDescription';
import type { CreateProtocolFormBodyProtocolType } from './createProtocolFormBodyProtocolType';
import type { CreateProtocolFormBodyCategoryId } from './createProtocolFormBodyCategoryId';
import type { ProtocolFormReadoutTemplate } from './protocolFormReadoutTemplate';
import type { CreateProtocolFormBodyConditionTemplates } from './createProtocolFormBodyConditionTemplates';
import type { CreateProtocolFormBodyOntologyDefaults } from './createProtocolFormBodyOntologyDefaults';

export interface CreateProtocolFormBody {
  name: string;
  description?: CreateProtocolFormBodyDescription;
  protocol_type?: CreateProtocolFormBodyProtocolType;
  is_default?: boolean;
  category_id?: CreateProtocolFormBodyCategoryId;
  assay_format_from_target?: boolean;
  readout_templates: ProtocolFormReadoutTemplate[];
  condition_templates?: CreateProtocolFormBodyConditionTemplates;
  ontology_defaults?: CreateProtocolFormBodyOntologyDefaults;
}
