/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { CreateCollectionBodyDescription } from './createCollectionBodyDescription';
import type { CreateCollectionBodyProjectId } from './createCollectionBodyProjectId';
import type { CreateCollectionBodyOwnedByOrgId } from './createCollectionBodyOwnedByOrgId';
import type { CollectionType } from './collectionType';

export interface CreateCollectionBody {
  name: string;
  description?: CreateCollectionBodyDescription;
  project_id?: CreateCollectionBodyProjectId;
  owned_by_org_id?: CreateCollectionBodyOwnedByOrgId;
  visibility?: string;
  type?: CollectionType;
}
