/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Chem-Vault
 * OpenAPI spec version: 0.1.0
 */
import type { CreateBatchRequestSaltEntryId } from './createBatchRequestSaltEntryId';
import type { CreateBatchRequestSaltName } from './createBatchRequestSaltName';
import type { CreateBatchRequestSaltSmiles } from './createBatchRequestSaltSmiles';
import type { CreateBatchRequestFormulaWeight } from './createBatchRequestFormulaWeight';
import type { CreateBatchRequestPurity } from './createBatchRequestPurity';
import type { CreateBatchRequestConcentrationValue } from './createBatchRequestConcentrationValue';
import type { CreateBatchRequestConcentrationUnit } from './createBatchRequestConcentrationUnit';
import type { CreateBatchRequestSupplierOrgId } from './createBatchRequestSupplierOrgId';
import type { CreateBatchRequestVendorCatalogNumber } from './createBatchRequestVendorCatalogNumber';
import type { CreateBatchRequestVendorLotNumber } from './createBatchRequestVendorLotNumber';
import type { CreateBatchRequestSynthesisDate } from './createBatchRequestSynthesisDate';
import type { CreateBatchRequestExpiryDate } from './createBatchRequestExpiryDate';
import type { CreateBatchRequestNotebookReference } from './createBatchRequestNotebookReference';
import type { CreateBatchRequestAppearance } from './createBatchRequestAppearance';
import type { CreateBatchRequestCustomFields } from './createBatchRequestCustomFields';

export interface CreateBatchRequest {
  molecule_id: string;
  source: string;
  amount_value: number;
  amount_unit: string;
  salt_entry_id?: CreateBatchRequestSaltEntryId;
  salt_name?: CreateBatchRequestSaltName;
  salt_smiles?: CreateBatchRequestSaltSmiles;
  salt_stoichiometry?: number;
  formula_weight?: CreateBatchRequestFormulaWeight;
  purity?: CreateBatchRequestPurity;
  concentration_value?: CreateBatchRequestConcentrationValue;
  concentration_unit?: CreateBatchRequestConcentrationUnit;
  supplier_org_id?: CreateBatchRequestSupplierOrgId;
  vendor_catalog_number?: CreateBatchRequestVendorCatalogNumber;
  vendor_lot_number?: CreateBatchRequestVendorLotNumber;
  synthesis_date?: CreateBatchRequestSynthesisDate;
  expiry_date?: CreateBatchRequestExpiryDate;
  notebook_reference?: CreateBatchRequestNotebookReference;
  appearance?: CreateBatchRequestAppearance;
  custom_fields?: CreateBatchRequestCustomFields;
}
