/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { CreateOntologySlotBodyRootConceptId } from './createOntologySlotBodyRootConceptId';

export interface CreateOntologySlotBody {
  name: string;
  label: string;
  ontology_sources: string[];
  root_concept_id?: CreateOntologySlotBodyRootConceptId;
  is_required?: boolean;
  allow_free_text?: boolean;
  display_order?: number;
}
