/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Chem-Vault
 * OpenAPI spec version: 0.1.0
 */
import type { CreateCustomFieldBodyDefaultValue } from './createCustomFieldBodyDefaultValue';
import type { CreateCustomFieldBodyPickListValues } from './createCustomFieldBodyPickListValues';
import type { CreateCustomFieldBodyVocabularyId } from './createCustomFieldBodyVocabularyId';

export interface CreateCustomFieldBody {
  name: string;
  label: string;
  data_type: string;
  applies_to: string;
  is_required?: boolean;
  default_value?: CreateCustomFieldBodyDefaultValue;
  display_order?: number;
  pick_list_values?: CreateCustomFieldBodyPickListValues;
  vocabulary_id?: CreateCustomFieldBodyVocabularyId;
}
