/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { CurveDetailResponseRunDate } from './curveDetailResponseRunDate';
import type { CurveDetailResponseCurveClass } from './curveDetailResponseCurveClass';
import type { CurveDetailResponseConfidenceIntervalLow } from './curveDetailResponseConfidenceIntervalLow';
import type { CurveDetailResponseConfidenceIntervalHigh } from './curveDetailResponseConfidenceIntervalHigh';
import type { CurveDetailResponseRawDataItem } from './curveDetailResponseRawDataItem';
import type { CurveDetailResponseExcludedPoints } from './curveDetailResponseExcludedPoints';
import type { InterceptValueResponse } from './interceptValueResponse';

export interface CurveDetailResponse {
  curve_id: string;
  run_id: string;
  run_date?: CurveDetailResponseRunDate;
  batch_id: string;
  readout_definition_id: string;
  curve_type: string;
  fitted_value: number;
  fitted_unit: string;
  hill_slope: number;
  r_squared: number;
  curve_class?: CurveDetailResponseCurveClass;
  top: number;
  bottom: number;
  num_points: number;
  confidence_interval_low?: CurveDetailResponseConfidenceIntervalLow;
  confidence_interval_high?: CurveDetailResponseConfidenceIntervalHigh;
  raw_data?: CurveDetailResponseRawDataItem[];
  excluded_points?: CurveDetailResponseExcludedPoints;
  fit_quality_warnings?: string[];
  intercept_values?: InterceptValueResponse[];
}
