/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Chem-Vault
 * OpenAPI spec version: 0.1.0
 */
import type { CurveDetailResponseCurveClass } from './curveDetailResponseCurveClass';
import type { CurveDetailResponseConfidenceIntervalLow } from './curveDetailResponseConfidenceIntervalLow';
import type { CurveDetailResponseConfidenceIntervalHigh } from './curveDetailResponseConfidenceIntervalHigh';
import type { CurveDetailResponseRawDataItem } from './curveDetailResponseRawDataItem';

export interface CurveDetailResponse {
  curve_id: string;
  run_id: string;
  batch_id: string;
  curve_type: string;
  fitted_value: number;
  fitted_unit: string;
  hill_slope: number;
  r_squared: number;
  curve_class?: CurveDetailResponseCurveClass;
  top: number;
  bottom: number;
  num_points: number;
  confidence_interval_low?: CurveDetailResponseConfidenceIntervalLow;
  confidence_interval_high?: CurveDetailResponseConfidenceIntervalHigh;
  raw_data?: CurveDetailResponseRawDataItem[];
}
