/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 1.0.0-3-g8cef97a9-dirty
 */
import type { DisclosureRequestResponseBulkDisclosureId } from './disclosureRequestResponseBulkDisclosureId';
import type { DisclosureRequestResponseCanonicalSmiles } from './disclosureRequestResponseCanonicalSmiles';
import type { DisclosureRequestResponseInchiKey } from './disclosureRequestResponseInchiKey';
import type { DisclosureRequestResponseResolutionType } from './disclosureRequestResponseResolutionType';
import type { DisclosureRequestResponseResolvedToMoleculeId } from './disclosureRequestResponseResolvedToMoleculeId';
import type { DisclosureRequestResponseMatchedMoleculeId } from './disclosureRequestResponseMatchedMoleculeId';
import type { DisclosureRequestResponseDisclosingOrgId } from './disclosureRequestResponseDisclosingOrgId';
import type { DisclosureRequestResponseScientistName } from './disclosureRequestResponseScientistName';
import type { DisclosureRequestResponseResolvedAt } from './disclosureRequestResponseResolvedAt';
import type { DisclosureRequestResponseDisclosureDate } from './disclosureRequestResponseDisclosureDate';
import type { DisclosureRequestResponseConflictReason } from './disclosureRequestResponseConflictReason';
import type { DisclosureRequestResponseNotes } from './disclosureRequestResponseNotes';

export interface DisclosureRequestResponse {
  id: string;
  bulk_disclosure_id?: DisclosureRequestResponseBulkDisclosureId;
  molecule_id: string;
  disclosed_smiles: string;
  canonical_smiles?: DisclosureRequestResponseCanonicalSmiles;
  inchi_key?: DisclosureRequestResponseInchiKey;
  status: string;
  resolution_type?: DisclosureRequestResponseResolutionType;
  resolved_to_molecule_id?: DisclosureRequestResponseResolvedToMoleculeId;
  matched_molecule_id?: DisclosureRequestResponseMatchedMoleculeId;
  disclosing_org_id?: DisclosureRequestResponseDisclosingOrgId;
  scientist_name?: DisclosureRequestResponseScientistName;
  requested_by: string;
  requested_at: string;
  resolved_at?: DisclosureRequestResponseResolvedAt;
  disclosure_date?: DisclosureRequestResponseDisclosureDate;
  conflict_reason?: DisclosureRequestResponseConflictReason;
  notes?: DisclosureRequestResponseNotes;
  version: number;
}
