/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { EffectiveCollectionCoverageResponseFraction } from './effectiveCollectionCoverageResponseFraction';

/**
 * Protocol rollup: adds the count of attaching runs.
 */
export interface EffectiveCollectionCoverageResponse {
  id: string;
  name: string;
  type: string;
  covered: number;
  total: number;
  fraction: EffectiveCollectionCoverageResponseFraction;
  run_count: number;
}
