/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { ExclusionPayloadEntryBodyIdx } from './exclusionPayloadEntryBodyIdx';
import type { ExclusionPayloadEntryBodySource } from './exclusionPayloadEntryBodySource';
import type { ExclusionPayloadEntryBodyReason } from './exclusionPayloadEntryBodyReason';
import type { ExclusionPayloadEntryBodyNote } from './exclusionPayloadEntryBodyNote';
import type { ExclusionPayloadEntryBodyConcentration } from './exclusionPayloadEntryBodyConcentration';
import type { ExclusionPayloadEntryBodyResponse } from './exclusionPayloadEntryBodyResponse';

/**
 * One entry in the Sprint 2 rich exclusion payload.

Mirrors the application-layer ``ExclusionPayloadEntry`` dataclass — the
route is a pure pass-through; the use case owns branching/validation.
 */
export interface ExclusionPayloadEntryBody {
  idx: ExclusionPayloadEntryBodyIdx;
  source: ExclusionPayloadEntryBodySource;
  excluded: boolean;
  reason: ExclusionPayloadEntryBodyReason;
  note?: ExclusionPayloadEntryBodyNote;
  concentration?: ExclusionPayloadEntryBodyConcentration;
  response?: ExclusionPayloadEntryBodyResponse;
}
