/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Chem-Vault
 * OpenAPI spec version: 0.1.0
 */
import type { HitCriterionDTOValue } from './hitCriterionDTOValue';

export interface HitCriterionDTO {
  readout_name: string;
  operator: string;
  value: HitCriterionDTOValue;
}
