/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { WellConflictModel } from './wellConflictModel';
import type { ReadoutConflictModel } from './readoutConflictModel';
import type { ImportRunFileResponseAttachmentId } from './importRunFileResponseAttachmentId';
import type { ImportRunFileResponseComputeWarning } from './importRunFileResponseComputeWarning';
import type { ImportRunFileResponseAttachmentWarning } from './importRunFileResponseAttachmentWarning';

export interface ImportRunFileResponse {
  rows_total: number;
  plates_created: number;
  wells_created: number;
  readouts_created: number;
  unmatched_batches: string[];
  unmatched_compound_refs?: string[];
  controls_from_template: number;
  controls_unclassified: number;
  skipped_rows: number;
  conflicts_well_metadata?: WellConflictModel[];
  conflicts_readout?: ReadoutConflictModel[];
  attachment_id?: ImportRunFileResponseAttachmentId;
  compute_warning?: ImportRunFileResponseComputeWarning;
  attachment_warning?: ImportRunFileResponseAttachmentWarning;
  fit_warnings?: string[];
}
