/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 1.0.0-31-g6cda55f2-dirty
 */
import type { ImportRowErrorModel } from './importRowErrorModel';
import type { ImportRunFileResponseAttachmentId } from './importRunFileResponseAttachmentId';
import type { ImportRunFileResponseAttachmentWarning } from './importRunFileResponseAttachmentWarning';
import type { WellConflictModel } from './wellConflictModel';
import type { ReadoutConflictModel } from './readoutConflictModel';
import type { ImportRunFileResponseComputeWarning } from './importRunFileResponseComputeWarning';

/**
 * Plate-file import outcome. Shared vocabulary from ``ImportResultModel`` plus
the plate-specific extras. ``values_updated`` stays 0 (never overwrites) and
``errors`` is empty: a conflicting or ambiguous file is refused before any write.
 */
export interface ImportRunFileResponse {
  total_rows: number;
  matched_compound_count: number;
  unmatched_compound_refs?: string[];
  unmatched_batch_refs?: string[];
  rows_skipped: number;
  errors?: ImportRowErrorModel[];
  values_inserted: number;
  values_updated: number;
  attachment_id?: ImportRunFileResponseAttachmentId;
  attachment_warning?: ImportRunFileResponseAttachmentWarning;
  plates_created: number;
  wells_created: number;
  controls_from_template: number;
  controls_unclassified: number;
  well_conflicts?: WellConflictModel[];
  readout_conflicts?: ReadoutConflictModel[];
  compute_warning?: ImportRunFileResponseComputeWarning;
  fit_warnings?: string[];
  auto_created_batches?: number;
}
