/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { ColumnMappingRequest } from './columnMappingRequest';
import type { CompoundBatchOverrideRequest } from './compoundBatchOverrideRequest';

export interface ImportRunFileRequest {
  preview_id: string;
  mapping: ColumnMappingRequest;
  compound_batch_overrides?: CompoundBatchOverrideRequest[];
  auto_create_unmatched_batches?: boolean;
}
