/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Chem-Vault
 * OpenAPI spec version: 0.1.0
 */
import type { ImportTemplateResponseDescription } from './importTemplateResponseDescription';
import type { ImportTemplateResponseColumnMappings } from './importTemplateResponseColumnMappings';
import type { ImportTemplateResponseDefaultProtocolId } from './importTemplateResponseDefaultProtocolId';

export interface ImportTemplateResponse {
  id: string;
  workspace_id: string;
  name: string;
  description?: ImportTemplateResponseDescription;
  column_mappings: ImportTemplateResponseColumnMappings;
  default_protocol_id?: ImportTemplateResponseDefaultProtocolId;
  created_by: string;
}
