/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Chem-Vault
 * OpenAPI spec version: 0.1.0
 */
import type { ColumnMappingRequest } from './columnMappingRequest';

export interface ImportRunFileRequest {
  preview_id: string;
  mapping: ColumnMappingRequest;
}
