/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */

export type ListBatchesGlobalApiV1BatchesGetParams = {
search?: string | null;
source?: string[] | null;
expiring_within_days?: number | null;
cursor?: string | null;
page_size?: number | null;
};
