/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */

export type ListBatchesGlobalApiV1BatchesGetTagLogic = typeof ListBatchesGlobalApiV1BatchesGetTagLogic[keyof typeof ListBatchesGlobalApiV1BatchesGetTagLogic];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListBatchesGlobalApiV1BatchesGetTagLogic = {
  any: 'any',
  all: 'all',
} as const;
