/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 1.1.0-14-gdd8a8c7e-dirty
 */
import type { ListCampaignsApiV1CampaignsGetTagLogic } from './listCampaignsApiV1CampaignsGetTagLogic';
import type { ListCampaignsApiV1CampaignsGetTargetLogic } from './listCampaignsApiV1CampaignsGetTargetLogic';

export type ListCampaignsApiV1CampaignsGetParams = {
project_id?: string | null;
cursor?: string | null;
limit?: number | null;
tags?: string[] | null;
tag_logic?: ListCampaignsApiV1CampaignsGetTagLogic;
targets?: string[] | null;
target_logic?: ListCampaignsApiV1CampaignsGetTargetLogic;
status?: 'draft' | 'closed' | 'superseded' | null;
};
