/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 1.1.0-14-gdd8a8c7e-dirty
 */
import type { StageOutcome } from './stageOutcome';
import type { ListCampaignResultsApiV1CampaignsCampaignIdResultsGetDirection } from './listCampaignResultsApiV1CampaignsCampaignIdResultsGetDirection';

export type ListCampaignResultsApiV1CampaignsCampaignIdResultsGetParams = {
stage_id?: string | null;
outcome?: StageOutcome | null;
/**
 * Channel id to sort by; omit for row order
 */
order_by?: string | null;
direction?: ListCampaignResultsApiV1CampaignsCampaignIdResultsGetDirection;
cursor?: string | null;
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
};
