/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { LoanStatus } from './loanStatus';

export type ListLoansApiV1PlateLoansGetParams = {
status?: LoanStatus | null;
owner_org_id?: string | null;
borrower_org_id?: string | null;
mine?: boolean;
plate_id?: string | null;
overdue?: boolean;
};
