/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { MeResponseOrgId } from './meResponseOrgId';
import type { MeResponseOrgSlug } from './meResponseOrgSlug';

export interface MeResponse {
  user_id: string;
  email: string;
  name: string;
  org_id?: MeResponseOrgId;
  org_slug?: MeResponseOrgSlug;
}
