/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Chem-Vault
 * OpenAPI spec version: 0.1.0
 */
import type { MoleculeSummaryResponse } from './moleculeSummaryResponse';
import type { MergeImpactCategoryResponse } from './mergeImpactCategoryResponse';

export interface MergeImpactResponse {
  source: MoleculeSummaryResponse;
  target: MoleculeSummaryResponse;
  categories: MergeImpactCategoryResponse[];
  blockers: string[];
}
