/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { MergeReason } from './mergeReason';
import type { MergeBodyNotes } from './mergeBodyNotes';

export interface MergeBody {
  target_molecule_id: string;
  reason?: MergeReason;
  notes?: MergeBodyNotes;
}
