/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 1.0.0-3-g8cef97a9-dirty
 */
import type { MoleculeResponseStructure } from './moleculeResponseStructure';
import type { MoleculeResponseDescriptors } from './moleculeResponseDescriptors';
import type { MoleculeResponseMolecularFormula } from './moleculeResponseMolecularFormula';
import type { MoleculeResponseStereochemistry } from './moleculeResponseStereochemistry';
import type { MoleculeResponseInventionDate } from './moleculeResponseInventionDate';
import type { MoleculeResponseDisclosedAt } from './moleculeResponseDisclosedAt';
import type { MoleculeResponseDisclosureDate } from './moleculeResponseDisclosureDate';
import type { MoleculeResponseMergedIntoId } from './moleculeResponseMergedIntoId';
import type { MoleculeResponseCustomFields } from './moleculeResponseCustomFields';
import type { MoleculeResponseScientistName } from './moleculeResponseScientistName';
import type { IdentifierResponse } from './identifierResponse';
import type { MoleculeResponseSimilarityScore } from './moleculeResponseSimilarityScore';

export interface MoleculeResponse {
  id: string;
  workspace_id: string;
  registration_number: string;
  name: string;
  molecule_type: string;
  structure?: MoleculeResponseStructure;
  descriptors?: MoleculeResponseDescriptors;
  molecular_formula?: MoleculeResponseMolecularFormula;
  structure_status: string;
  registration_status: string;
  synthesis_status: string;
  lifecycle_stage: string;
  stereochemistry?: MoleculeResponseStereochemistry;
  invention_date?: MoleculeResponseInventionDate;
  disclosed_at?: MoleculeResponseDisclosedAt;
  disclosure_date?: MoleculeResponseDisclosureDate;
  merged_into_id?: MoleculeResponseMergedIntoId;
  custom_fields?: MoleculeResponseCustomFields;
  originating_org_id: string;
  scientist_name?: MoleculeResponseScientistName;
  identifiers: IdentifierResponse[];
  version: number;
  similarity_score?: MoleculeResponseSimilarityScore;
}
