/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 1.3.0-17-gd9da37bb-dirty
 */

export type NamingChangeRequestKind = typeof NamingChangeRequestKind[keyof typeof NamingChangeRequestKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NamingChangeRequestKind = {
  category: 'category',
  label: 'label',
  home_organism: 'home_organism',
} as const;
