/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { OntologyTermRequestUri } from './ontologyTermRequestUri';

/**
 * An ontology-annotation term as it arrives over the wire. Mirrors
`OntologyTermResponse` so the facet boundary is symmetric and typed —
a malformed term is a clean 422 instead of a KeyError deep in the use
case. Routes convert these to plain dicts before building commands so
the application layer stays framework-agnostic.
 */
export interface OntologyTermRequest {
  term_id: string;
  label: string;
  ontology_source: string;
  uri?: OntologyTermRequestUri;
}
