/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { OntologyTermResponseUri } from './ontologyTermResponseUri';

export interface OntologyTermResponse {
  term_id: string;
  label: string;
  ontology_source: string;
  uri?: OntologyTermResponseUri;
}
