/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { AuditOperationResponse } from './auditOperationResponse';
import type { PaginatedResponseAuditOperationResponseNextCursor } from './paginatedResponseAuditOperationResponseNextCursor';
import type { PaginatedResponseAuditOperationResponseTotalCount } from './paginatedResponseAuditOperationResponseTotalCount';

export interface PaginatedResponseAuditOperationResponse {
  items: AuditOperationResponse[];
  next_cursor?: PaginatedResponseAuditOperationResponseNextCursor;
  total_count?: PaginatedResponseAuditOperationResponseTotalCount;
}
