/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 1.1.0-14-gdd8a8c7e-dirty
 */
import type { CampaignSummaryResponse } from './campaignSummaryResponse';
import type { PaginatedResponseCampaignSummaryResponseNextCursor } from './paginatedResponseCampaignSummaryResponseNextCursor';
import type { PaginatedResponseCampaignSummaryResponseTotalCount } from './paginatedResponseCampaignSummaryResponseTotalCount';

export interface PaginatedResponseCampaignSummaryResponse {
  items: CampaignSummaryResponse[];
  next_cursor?: PaginatedResponseCampaignSummaryResponseNextCursor;
  total_count?: PaginatedResponseCampaignSummaryResponseTotalCount;
}
