/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { DataSourceResponse } from './dataSourceResponse';
import type { PaginatedResponseDataSourceResponseNextCursor } from './paginatedResponseDataSourceResponseNextCursor';
import type { PaginatedResponseDataSourceResponseTotalCount } from './paginatedResponseDataSourceResponseTotalCount';

export interface PaginatedResponseDataSourceResponse {
  items: DataSourceResponse[];
  next_cursor?: PaginatedResponseDataSourceResponseNextCursor;
  total_count?: PaginatedResponseDataSourceResponseTotalCount;
}
