/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 1.0.0-31-g6cda55f2-dirty
 */
import type { ImportRowErrorModel } from './importRowErrorModel';
import type { HeaderSuggestionModel } from './headerSuggestionModel';
import type { PreviewRunFileResponseSampleRowsItem } from './previewRunFileResponseSampleRowsItem';
import type { PlatePreviewModel } from './platePreviewModel';
import type { WellConflictModel } from './wellConflictModel';
import type { ReadoutConflictModel } from './readoutConflictModel';
import type { AmbiguousCompoundModel } from './ambiguousCompoundModel';

/**
 * Plate-file preview. Shared vocabulary from ``ImportForecastModel`` plus the
plate-specific extras. ``values_to_update`` stays 0: the plate importer never
overwrites — a cell that already exists lands in ``readout_conflicts``.
 */
export interface PreviewRunFileResponse {
  total_rows: number;
  matched_compound_count: number;
  unmatched_compound_refs?: string[];
  unmatched_batch_refs?: string[];
  rows_skipped: number;
  errors?: ImportRowErrorModel[];
  values_to_insert: number;
  values_to_update: number;
  preview_id: string;
  headers: string[];
  suggestions: HeaderSuggestionModel[];
  sample_rows: PreviewRunFileResponseSampleRowsItem[];
  plates: PlatePreviewModel[];
  matched_batch_count: number;
  expires_in_seconds: number;
  validation_errors?: string[];
  will_create_plates?: number;
  will_create_wells?: number;
  well_conflicts?: WellConflictModel[];
  readout_conflicts?: ReadoutConflictModel[];
  ambiguous_compounds?: AmbiguousCompoundModel[];
  auto_created_batches?: number;
}
