/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 1.0.0-26-g615828d7-dirty
 */
import type { PreviewRegistrationItemBodyName } from './previewRegistrationItemBodyName';
import type { PreviewRegistrationItemBodySmiles } from './previewRegistrationItemBodySmiles';
import type { ExternalIdBody } from './externalIdBody';

/**
 * Mirrors RegisterMoleculeBody so a caller can preview the exact payload it will
POST; keys the forecast does not use (originating_org_id, batch, …) are ignored.
 */
export interface PreviewRegistrationItemBody {
  name?: PreviewRegistrationItemBodyName;
  smiles?: PreviewRegistrationItemBodySmiles;
  molecule_type?: string;
  external_ids?: ExternalIdBody[];
}
