/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */

/**
 * A protocol's effective target, with provenance for the design tab.

``is_direct`` — attached directly at the protocol (survives auto-prune).
``run_count`` — how many of the protocol's runs reference it.
 */
export interface ProtocolTargetRefResponse {
  id: string;
  name: string;
  target_type: string;
  is_direct: boolean;
  run_count: number;
}
