/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 1.3.0-17-gd9da37bb-dirty
 */
import type { ReferenceKind } from './referenceKind';

/**
 * Raw input; the domain strips prefixes (``AID``, ``https://doi.org/``) and validates.
 */
export interface ProtocolReferenceRequest {
  kind: ReferenceKind;
  value: string;
}
