/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 1.3.0-17-gd9da37bb-dirty
 */
import type { ReferenceKind } from './referenceKind';

/**
 * A validated reference; ``<kind>:<value>`` is its key for DELETE.
 */
export interface ProtocolReferenceResponse {
  kind: ReferenceKind;
  value: string;
}
