/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 1.3.0-17-gd9da37bb-dirty
 */

export interface RederiveReportResponse {
  renamed: number;
  flagged: number;
  failed: string[];
}
