/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { RefitPreviewResponseConfidenceIntervalLow } from './refitPreviewResponseConfidenceIntervalLow';
import type { RefitPreviewResponseConfidenceIntervalHigh } from './refitPreviewResponseConfidenceIntervalHigh';

/**
 * Mirror of ``PreviewRefitResult`` — the subset the FE needs to redraw
the candidate curve during point editing.
 */
export interface RefitPreviewResponse {
  fitted_value: number;
  hill_slope: number;
  top: number;
  bottom: number;
  r_squared: number;
  confidence_interval_low?: RefitPreviewResponseConfidenceIntervalLow;
  confidence_interval_high?: RefitPreviewResponseConfidenceIntervalHigh;
  curve_class: string;
  points_in_fit: number;
  points_total: number;
}
