/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { RequestLoanBodyPlateIds } from './requestLoanBodyPlateIds';
import type { RequestLoanBodyBarcodes } from './requestLoanBodyBarcodes';
import type { RequestLoanBodyGroupId } from './requestLoanBodyGroupId';
import type { RequestLoanBodyBorrowerOrgId } from './requestLoanBodyBorrowerOrgId';
import type { RequestLoanBodyDueDate } from './requestLoanBodyDueDate';
import type { RequestLoanBodyNotes } from './requestLoanBodyNotes';

export interface RequestLoanBody {
  plate_ids?: RequestLoanBodyPlateIds;
  barcodes?: RequestLoanBodyBarcodes;
  group_id?: RequestLoanBodyGroupId;
  borrower_org_id?: RequestLoanBodyBorrowerOrgId;
  due_date?: RequestLoanBodyDueDate;
  notes?: RequestLoanBodyNotes;
}
