/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { ResolvedItemResponseItemType } from './resolvedItemResponseItemType';
import type { ResolvedItemResponseItemId } from './resolvedItemResponseItemId';
import type { ResolvedItemResponseLabel } from './resolvedItemResponseLabel';
import type { ResolvedItemResponseError } from './resolvedItemResponseError';

/**
 * One pasted barcode: either resolved (type/id/label) or an error.
 */
export interface ResolvedItemResponse {
  barcode: string;
  item_type?: ResolvedItemResponseItemType;
  item_id?: ResolvedItemResponseItemId;
  label?: ResolvedItemResponseLabel;
  error?: ResolvedItemResponseError;
}
