/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { RunResponseLockedBy } from './runResponseLockedBy';
import type { RunResponseLockReason } from './runResponseLockReason';
import type { RunResponseQcMetrics } from './runResponseQcMetrics';
import type { RunResponseNotes } from './runResponseNotes';
import type { RunResponsePerformedAtOrgId } from './runResponsePerformedAtOrgId';
import type { RunResponseParentRunId } from './runResponseParentRunId';
import type { RunResponseRunRelationshipType } from './runResponseRunRelationshipType';
import type { RunResponsePlateFormat } from './runResponsePlateFormat';
import type { RunResponsePlateTemplateId } from './runResponsePlateTemplateId';
import type { RunResponseConditions } from './runResponseConditions';
import type { TargetRefResponse } from './targetRefResponse';
import type { CollectionCoverageResponse } from './collectionCoverageResponse';

export interface RunResponse {
  id: string;
  workspace_id: string;
  protocol_id: string;
  run_date: string;
  created_at: string;
  operator: string;
  status: string;
  is_locked: boolean;
  locked_by?: RunResponseLockedBy;
  lock_reason?: RunResponseLockReason;
  qc_metrics?: RunResponseQcMetrics;
  notes?: RunResponseNotes;
  plate_count: number;
  plate_barcodes?: string[];
  molecule_count?: number;
  performed_at_org_id?: RunResponsePerformedAtOrgId;
  parent_run_id?: RunResponseParentRunId;
  run_relationship_type?: RunResponseRunRelationshipType;
  plate_format?: RunResponsePlateFormat;
  plate_template_id?: RunResponsePlateTemplateId;
  conditions?: RunResponseConditions;
  targets?: TargetRefResponse[];
  collections?: CollectionCoverageResponse[];
}
