/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */

export interface SaltEntryResponse {
  id: string;
  workspace_id: string;
  code: string;
  name: string;
  smiles: string;
  molecular_weight: number;
  is_default: boolean;
  is_active: boolean;
  version: number;
}
