/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { SavedSearchResponseColumnsAnyOf } from './savedSearchResponseColumnsAnyOf';

export type SavedSearchResponseColumns = SavedSearchResponseColumnsAnyOf | null;
