/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 1.3.0-17-gd9da37bb-dirty
 */

export type SearchOntologyApiV1OntologySearchGetParams = {
/**
 * @minLength 1
 */
q: string;
ontologies?: string;
subtree_root_id?: string | null;
exact_only?: boolean;
};
