/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { SearchCampaignResultsRequestStageId } from './searchCampaignResultsRequestStageId';
import type { StageOutcome } from './stageOutcome';
import type { SearchCampaignResultsRequestOrderBy } from './searchCampaignResultsRequestOrderBy';
import type { SearchCampaignResultsRequestDirection } from './searchCampaignResultsRequestDirection';
import type { SearchCampaignResultsRequestCursor } from './searchCampaignResultsRequestCursor';
import type { CampaignResultFilters } from './campaignResultFilters';

export interface SearchCampaignResultsRequest {
  stage_id?: SearchCampaignResultsRequestStageId;
  outcome?: StageOutcome[];
  order_by?: SearchCampaignResultsRequestOrderBy;
  direction?: SearchCampaignResultsRequestDirection;
  cursor?: SearchCampaignResultsRequestCursor;
  /**
   * @minimum 1
   * @maximum 200
   */
  limit?: number;
  filters?: CampaignResultFilters;
}
