/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Chem-Vault
 * OpenAPI spec version: 0.1.0
 */

export type SearchMoleculesApiV1MoleculesSearchGetParams = {
search_type: string;
query: string;
threshold?: number;
limit?: number;
query_kind?: string | null;
};
