/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 1.1.0-14-gdd8a8c7e-dirty
 */
import type { SetStageOverrideRequestOutcome } from './setStageOverrideRequestOutcome';

export interface SetStageOverrideRequest {
  outcome: SetStageOverrideRequestOutcome;
  reason: string;
}
