/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 1.1.0-14-gdd8a8c7e-dirty
 */

export type SetStageOverrideRequestOutcome = typeof SetStageOverrideRequestOutcome[keyof typeof SetStageOverrideRequestOutcome];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SetStageOverrideRequestOutcome = {
  hit: 'hit',
  miss: 'miss',
} as const;
