/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Chem-Vault
 * OpenAPI spec version: 0.1.0
 */

export interface SetUpRunPlateResponse {
  plate_id: string;
  wells_created: number;
  compounds_assigned: number;
  unresolved: string[];
}
