/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Chem-Vault
 * OpenAPI spec version: 0.1.0
 */
import type { CompoundAssignmentResponse } from './compoundAssignmentResponse';
import type { SetUpRunPlateRequestConcentrationSeries } from './setUpRunPlateRequestConcentrationSeries';

export interface SetUpRunPlateRequest {
  plate_number?: number;
  compound_assignments: CompoundAssignmentResponse[];
  concentration_series?: SetUpRunPlateRequestConcentrationSeries;
}
