/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */

/**
 * What a shipment item points at (spec 2026-08-26 §2).
 */
export type ShipmentItemType = typeof ShipmentItemType[keyof typeof ShipmentItemType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ShipmentItemType = {
  plate: 'plate',
  sample: 'sample',
} as const;
