/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { ShipmentItemType } from './shipmentItemType';
import type { ShipmentItemResponseBarcode } from './shipmentItemResponseBarcode';
import type { ShipmentItemResponseLabel } from './shipmentItemResponseLabel';
import type { ShipmentItemResponseAmountValue } from './shipmentItemResponseAmountValue';
import type { ShipmentItemResponseAmountUnit } from './shipmentItemResponseAmountUnit';

export interface ShipmentItemResponse {
  id: string;
  item_type: ShipmentItemType;
  item_id: string;
  barcode?: ShipmentItemResponseBarcode;
  label?: ShipmentItemResponseLabel;
  amount_value?: ShipmentItemResponseAmountValue;
  amount_unit?: ShipmentItemResponseAmountUnit;
}
