/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { StartScaffoldTreeResponseTree } from './startScaffoldTreeResponseTree';
import type { StartScaffoldTreeResponseJob } from './startScaffoldTreeResponseJob';

export interface StartScaffoldTreeResponse {
  tree: StartScaffoldTreeResponseTree;
  job: StartScaffoldTreeResponseJob;
}
