/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { StartUmapClusterBodyCollectionId } from './startUmapClusterBodyCollectionId';
import type { StartUmapClusterBodyMoleculeIds } from './startUmapClusterBodyMoleculeIds';
import type { StartUmapClusterBodyN } from './startUmapClusterBodyN';
import type { StartUmapClusterBodyThreshold } from './startUmapClusterBodyThreshold';

/**
 * Exactly one of ``collection_id`` or ``molecule_ids`` must be supplied.

``picker`` controls the representative-selection algorithm:
- ``maxmin``: MaxMin diversity picker; ``n`` (required) sets the output count.
- ``butina``: Butina cluster medoids; ``threshold`` (required) controls cluster size.
 */
export interface StartUmapClusterBody {
  collection_id?: StartUmapClusterBodyCollectionId;
  molecule_ids?: StartUmapClusterBodyMoleculeIds;
  /** @pattern ^(maxmin|butina)$ */
  picker: string;
  n?: StartUmapClusterBodyN;
  threshold?: StartUmapClusterBodyThreshold;
}
