/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 1.0.0-3-g8cef97a9-dirty
 */
import type { SubmitDisclosureBodyDisclosingOrgId } from './submitDisclosureBodyDisclosingOrgId';
import type { SubmitDisclosureBodyScientistName } from './submitDisclosureBodyScientistName';
import type { SubmitDisclosureBodyNotes } from './submitDisclosureBodyNotes';
import type { SubmitDisclosureBodyDisclosureDate } from './submitDisclosureBodyDisclosureDate';

export interface SubmitDisclosureBody {
  molecule_id: string;
  disclosed_smiles: string;
  disclosing_org_id?: SubmitDisclosureBodyDisclosingOrgId;
  scientist_name?: SubmitDisclosureBodyScientistName;
  auto_approve?: boolean;
  notes?: SubmitDisclosureBodyNotes;
  disclosure_date?: SubmitDisclosureBodyDisclosureDate;
}
