/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { SynthesisRouteResponseDescription } from './synthesisRouteResponseDescription';
import type { SynthesisRouteResponseOverallYield } from './synthesisRouteResponseOverallYield';
import type { SynthesisRouteResponseScale } from './synthesisRouteResponseScale';
import type { SynthesisRouteResponseSourceReference } from './synthesisRouteResponseSourceReference';
import type { StepResponse } from './stepResponse';

export interface SynthesisRouteResponse {
  id: string;
  workspace_id: string;
  target_molecule_id: string;
  name: string;
  description?: SynthesisRouteResponseDescription;
  route_type: string;
  status: string;
  total_steps: number;
  overall_yield?: SynthesisRouteResponseOverallYield;
  scale?: SynthesisRouteResponseScale;
  source: string;
  source_reference?: SynthesisRouteResponseSourceReference;
  created_by: string;
  steps: StepResponse[];
}
