/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { SynthesisRequestSummaryResponseTargetPurity } from './synthesisRequestSummaryResponseTargetPurity';

export interface SynthesisRequestSummaryResponse {
  id: string;
  workspace_id: string;
  requester_id: string;
  molecule_id: string;
  amount_value: number;
  amount_unit: string;
  purpose: string;
  priority: string;
  status: string;
  target_purity?: SynthesisRequestSummaryResponseTargetPurity;
}
