/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 1.2.0-dirty
 */

/**
 * Entity types that can carry tags (one link table each).
 */
export type TaggableEntityType = typeof TaggableEntityType[keyof typeof TaggableEntityType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TaggableEntityType = {
  Molecule: 'Molecule',
  Protocol: 'Protocol',
  Project: 'Project',
  Collection: 'Collection',
  Run: 'Run',
  Campaign: 'Campaign',
  Batch: 'Batch',
  Plate: 'Plate',
} as const;
