/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { UpdateRunRequestQcMetrics } from './updateRunRequestQcMetrics';
import type { UpdateRunRequestNotes } from './updateRunRequestNotes';
import type { UpdateRunRequestConditions } from './updateRunRequestConditions';

export interface UpdateRunRequest {
  qc_metrics?: UpdateRunRequestQcMetrics;
  notes?: UpdateRunRequestNotes;
  conditions?: UpdateRunRequestConditions;
}
