/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 1.3.0-17-gd9da37bb-dirty
 */
import type { UpdateProtocolRequestDescription } from './updateProtocolRequestDescription';
import type { UpdateProtocolRequestCategory } from './updateProtocolRequestCategory';
import type { UpdateProtocolRequestRecommendedHitCriteria } from './updateProtocolRequestRecommendedHitCriteria';
import type { UpdateProtocolRequestPosControlSignal } from './updateProtocolRequestPosControlSignal';

export interface UpdateProtocolRequest {
  description?: UpdateProtocolRequestDescription;
  category?: UpdateProtocolRequestCategory;
  recommended_hit_criteria?: UpdateProtocolRequestRecommendedHitCriteria;
  pos_control_signal?: UpdateProtocolRequestPosControlSignal;
}
