/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Chem-Vault
 * OpenAPI spec version: 0.1.0
 */
import type { UpdateProtocolFormBodyName } from './updateProtocolFormBodyName';
import type { UpdateProtocolFormBodyDescription } from './updateProtocolFormBodyDescription';
import type { UpdateProtocolFormBodyProtocolType } from './updateProtocolFormBodyProtocolType';
import type { UpdateProtocolFormBodyIsDefault } from './updateProtocolFormBodyIsDefault';
import type { UpdateProtocolFormBodyReadoutTemplates } from './updateProtocolFormBodyReadoutTemplates';
import type { UpdateProtocolFormBodyConditionTemplates } from './updateProtocolFormBodyConditionTemplates';
import type { UpdateProtocolFormBodyOntologyDefaults } from './updateProtocolFormBodyOntologyDefaults';

export interface UpdateProtocolFormBody {
  name?: UpdateProtocolFormBodyName;
  description?: UpdateProtocolFormBodyDescription;
  protocol_type?: UpdateProtocolFormBodyProtocolType;
  is_default?: UpdateProtocolFormBodyIsDefault;
  readout_templates?: UpdateProtocolFormBodyReadoutTemplates;
  condition_templates?: UpdateProtocolFormBodyConditionTemplates;
  ontology_defaults?: UpdateProtocolFormBodyOntologyDefaults;
}
