/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { UpdateMoleculeBodyLifecycleStage } from './updateMoleculeBodyLifecycleStage';
import type { UpdateMoleculeBodyLifecycleReason } from './updateMoleculeBodyLifecycleReason';
import type { UpdateMoleculeBodyCustomFields } from './updateMoleculeBodyCustomFields';

export interface UpdateMoleculeBody {
  lifecycle_stage?: UpdateMoleculeBodyLifecycleStage;
  lifecycle_reason?: UpdateMoleculeBodyLifecycleReason;
  custom_fields?: UpdateMoleculeBodyCustomFields;
}
