/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Chem-Vault
 * OpenAPI spec version: 0.1.0
 */
import type { UpdateChannelRequestLabel } from './updateChannelRequestLabel';
import type { UpdateChannelRequestSelectionRule } from './updateChannelRequestSelectionRule';
import type { UpdateChannelRequestQcFilter } from './updateChannelRequestQcFilter';
import type { UpdateChannelRequestHitThreshold } from './updateChannelRequestHitThreshold';

/**
 * Partial update — omitted fields are not changed; null clears the value.

The UC uses an UNSET sentinel to distinguish "omit" from None. We map
Pydantic's model_fields_set to thread the sentinel through correctly.
 */
export interface UpdateChannelRequest {
  label?: UpdateChannelRequestLabel;
  selection_rule?: UpdateChannelRequestSelectionRule;
  qc_filter?: UpdateChannelRequestQcFilter;
  hit_threshold?: UpdateChannelRequestHitThreshold;
}
