/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Chem-Vault
 * OpenAPI spec version: 0.1.0
 */
import type { UpdatePlateBodyPlateLabel } from './updatePlateBodyPlateLabel';
import type { UpdatePlateBodyPlateType } from './updatePlateBodyPlateType';
import type { UpdatePlateBodyNotes } from './updatePlateBodyNotes';
import type { UpdatePlateBodyProjectId } from './updatePlateBodyProjectId';
import type { UpdatePlateBodyStorageLocationId } from './updatePlateBodyStorageLocationId';

export interface UpdatePlateBody {
  plate_label?: UpdatePlateBodyPlateLabel;
  plate_type?: UpdatePlateBodyPlateType;
  notes?: UpdatePlateBodyNotes;
  project_id?: UpdatePlateBodyProjectId;
  storage_location_id?: UpdatePlateBodyStorageLocationId;
}
