/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Chem-Vault
 * OpenAPI spec version: 0.1.0
 */
import type { UpdateSampleRequestRequestPurpose } from './updateSampleRequestRequestPurpose';
import type { UpdateSampleRequestRequestPriority } from './updateSampleRequestRequestPriority';
import type { UpdateSampleRequestRequestAmountValue } from './updateSampleRequestRequestAmountValue';
import type { UpdateSampleRequestRequestAmountUnit } from './updateSampleRequestRequestAmountUnit';

export interface UpdateSampleRequestRequest {
  purpose?: UpdateSampleRequestRequestPurpose;
  priority?: UpdateSampleRequestRequestPriority;
  amount_value?: UpdateSampleRequestRequestAmountValue;
  amount_unit?: UpdateSampleRequestRequestAmountUnit;
}
