/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Chem-Vault
 * OpenAPI spec version: 0.1.0
 */
import type { UpdateSavedSearchBodyName } from './updateSavedSearchBodyName';
import type { UpdateSavedSearchBodyDescription } from './updateSavedSearchBodyDescription';
import type { UpdateSavedSearchBodyQuery } from './updateSavedSearchBodyQuery';
import type { UpdateSavedSearchBodyColumns } from './updateSavedSearchBodyColumns';
import type { UpdateSavedSearchBodyVisibility } from './updateSavedSearchBodyVisibility';
import type { UpdateSavedSearchBodyProjectId } from './updateSavedSearchBodyProjectId';

export interface UpdateSavedSearchBody {
  name?: UpdateSavedSearchBodyName;
  description?: UpdateSavedSearchBodyDescription;
  query?: UpdateSavedSearchBodyQuery;
  columns?: UpdateSavedSearchBodyColumns;
  visibility?: UpdateSavedSearchBodyVisibility;
  project_id?: UpdateSavedSearchBodyProjectId;
}
