/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Chem-Vault
 * OpenAPI spec version: 0.1.0
 */
import type { UpdateConditionDefinitionRequestName } from './updateConditionDefinitionRequestName';
import type { UpdateConditionDefinitionRequestDataType } from './updateConditionDefinitionRequestDataType';
import type { UpdateConditionDefinitionRequestUnit } from './updateConditionDefinitionRequestUnit';
import type { UpdateConditionDefinitionRequestPickListValues } from './updateConditionDefinitionRequestPickListValues';

/**
 * Partial-update payload.
 */
export interface UpdateConditionDefinitionRequest {
  name?: UpdateConditionDefinitionRequestName;
  data_type?: UpdateConditionDefinitionRequestDataType;
  unit?: UpdateConditionDefinitionRequestUnit;
  pick_list_values?: UpdateConditionDefinitionRequestPickListValues;
}
