/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { UpdateRunRequestConditionsAnyOf } from './updateRunRequestConditionsAnyOf';

export type UpdateRunRequestConditions = UpdateRunRequestConditionsAnyOf | null;
