/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Cellar
 * OpenAPI spec version: 0.1.0
 */
import type { WorkspaceMemberResponseAvatarUrl } from './workspaceMemberResponseAvatarUrl';

export interface WorkspaceMemberResponse {
  user_id: string;
  email: string;
  name: string;
  avatar_url?: WorkspaceMemberResponseAvatarUrl;
  role: string;
}
