/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Chem-Vault
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CompleteRunRequest,
  CreateRunRequest,
  HTTPValidationError,
  LockRequest,
  RejectRequest,
  ResetRunDataResponse,
  RunResponse,
  UnlockRequest,
  UpdateRunRequest
} from '.././model';

import { customInstance } from '.././custom-instance';




/**
 * @summary Create Run
 */
export const createRunApiV1RunsPost = (
    createRunRequest: CreateRunRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<RunResponse>(
      {url: `/api/v1/runs`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createRunRequest, signal
    },
      );
    }
  


export const getCreateRunApiV1RunsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRunApiV1RunsPost>>, TError,{data: CreateRunRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createRunApiV1RunsPost>>, TError,{data: CreateRunRequest}, TContext> => {

const mutationKey = ['createRunApiV1RunsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createRunApiV1RunsPost>>, {data: CreateRunRequest}> = (props) => {
          const {data} = props ?? {};

          return  createRunApiV1RunsPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateRunApiV1RunsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createRunApiV1RunsPost>>>
    export type CreateRunApiV1RunsPostMutationBody = CreateRunRequest
    export type CreateRunApiV1RunsPostMutationError = HTTPValidationError

    /**
 * @summary Create Run
 */
export const useCreateRunApiV1RunsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRunApiV1RunsPost>>, TError,{data: CreateRunRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createRunApiV1RunsPost>>,
        TError,
        {data: CreateRunRequest},
        TContext
      > => {

      const mutationOptions = getCreateRunApiV1RunsPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List Runs By Protocol
 */
export const listRunsByProtocolApiV1ProtocolsProtocolIdRunsGet = (
    protocolId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<RunResponse[]>(
      {url: `/api/v1/protocols/${protocolId}/runs`, method: 'GET', signal
    },
      );
    }
  



export const getListRunsByProtocolApiV1ProtocolsProtocolIdRunsGetQueryKey = (protocolId?: string,) => {
    return [
    `/api/v1/protocols/${protocolId}/runs`
    ] as const;
    }

    
export const getListRunsByProtocolApiV1ProtocolsProtocolIdRunsGetQueryOptions = <TData = Awaited<ReturnType<typeof listRunsByProtocolApiV1ProtocolsProtocolIdRunsGet>>, TError = HTTPValidationError>(protocolId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRunsByProtocolApiV1ProtocolsProtocolIdRunsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListRunsByProtocolApiV1ProtocolsProtocolIdRunsGetQueryKey(protocolId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listRunsByProtocolApiV1ProtocolsProtocolIdRunsGet>>> = ({ signal }) => listRunsByProtocolApiV1ProtocolsProtocolIdRunsGet(protocolId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(protocolId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listRunsByProtocolApiV1ProtocolsProtocolIdRunsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListRunsByProtocolApiV1ProtocolsProtocolIdRunsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listRunsByProtocolApiV1ProtocolsProtocolIdRunsGet>>>
export type ListRunsByProtocolApiV1ProtocolsProtocolIdRunsGetQueryError = HTTPValidationError


export function useListRunsByProtocolApiV1ProtocolsProtocolIdRunsGet<TData = Awaited<ReturnType<typeof listRunsByProtocolApiV1ProtocolsProtocolIdRunsGet>>, TError = HTTPValidationError>(
 protocolId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRunsByProtocolApiV1ProtocolsProtocolIdRunsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listRunsByProtocolApiV1ProtocolsProtocolIdRunsGet>>,
          TError,
          Awaited<ReturnType<typeof listRunsByProtocolApiV1ProtocolsProtocolIdRunsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListRunsByProtocolApiV1ProtocolsProtocolIdRunsGet<TData = Awaited<ReturnType<typeof listRunsByProtocolApiV1ProtocolsProtocolIdRunsGet>>, TError = HTTPValidationError>(
 protocolId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRunsByProtocolApiV1ProtocolsProtocolIdRunsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listRunsByProtocolApiV1ProtocolsProtocolIdRunsGet>>,
          TError,
          Awaited<ReturnType<typeof listRunsByProtocolApiV1ProtocolsProtocolIdRunsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListRunsByProtocolApiV1ProtocolsProtocolIdRunsGet<TData = Awaited<ReturnType<typeof listRunsByProtocolApiV1ProtocolsProtocolIdRunsGet>>, TError = HTTPValidationError>(
 protocolId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRunsByProtocolApiV1ProtocolsProtocolIdRunsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Runs By Protocol
 */

export function useListRunsByProtocolApiV1ProtocolsProtocolIdRunsGet<TData = Awaited<ReturnType<typeof listRunsByProtocolApiV1ProtocolsProtocolIdRunsGet>>, TError = HTTPValidationError>(
 protocolId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRunsByProtocolApiV1ProtocolsProtocolIdRunsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListRunsByProtocolApiV1ProtocolsProtocolIdRunsGetQueryOptions(protocolId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get Run
 */
export const getRunApiV1RunsRunIdGet = (
    runId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<RunResponse>(
      {url: `/api/v1/runs/${runId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetRunApiV1RunsRunIdGetQueryKey = (runId?: string,) => {
    return [
    `/api/v1/runs/${runId}`
    ] as const;
    }

    
export const getGetRunApiV1RunsRunIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getRunApiV1RunsRunIdGet>>, TError = HTTPValidationError>(runId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRunApiV1RunsRunIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRunApiV1RunsRunIdGetQueryKey(runId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRunApiV1RunsRunIdGet>>> = ({ signal }) => getRunApiV1RunsRunIdGet(runId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(runId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRunApiV1RunsRunIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRunApiV1RunsRunIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getRunApiV1RunsRunIdGet>>>
export type GetRunApiV1RunsRunIdGetQueryError = HTTPValidationError


export function useGetRunApiV1RunsRunIdGet<TData = Awaited<ReturnType<typeof getRunApiV1RunsRunIdGet>>, TError = HTTPValidationError>(
 runId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRunApiV1RunsRunIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRunApiV1RunsRunIdGet>>,
          TError,
          Awaited<ReturnType<typeof getRunApiV1RunsRunIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRunApiV1RunsRunIdGet<TData = Awaited<ReturnType<typeof getRunApiV1RunsRunIdGet>>, TError = HTTPValidationError>(
 runId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRunApiV1RunsRunIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRunApiV1RunsRunIdGet>>,
          TError,
          Awaited<ReturnType<typeof getRunApiV1RunsRunIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRunApiV1RunsRunIdGet<TData = Awaited<ReturnType<typeof getRunApiV1RunsRunIdGet>>, TError = HTTPValidationError>(
 runId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRunApiV1RunsRunIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Run
 */

export function useGetRunApiV1RunsRunIdGet<TData = Awaited<ReturnType<typeof getRunApiV1RunsRunIdGet>>, TError = HTTPValidationError>(
 runId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRunApiV1RunsRunIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRunApiV1RunsRunIdGetQueryOptions(runId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update Run
 */
export const updateRunApiV1RunsRunIdPatch = (
    runId: string,
    updateRunRequest: UpdateRunRequest,
 ) => {
      
      
      return customInstance<RunResponse>(
      {url: `/api/v1/runs/${runId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateRunRequest
    },
      );
    }
  


export const getUpdateRunApiV1RunsRunIdPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRunApiV1RunsRunIdPatch>>, TError,{runId: string;data: UpdateRunRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateRunApiV1RunsRunIdPatch>>, TError,{runId: string;data: UpdateRunRequest}, TContext> => {

const mutationKey = ['updateRunApiV1RunsRunIdPatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateRunApiV1RunsRunIdPatch>>, {runId: string;data: UpdateRunRequest}> = (props) => {
          const {runId,data} = props ?? {};

          return  updateRunApiV1RunsRunIdPatch(runId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateRunApiV1RunsRunIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateRunApiV1RunsRunIdPatch>>>
    export type UpdateRunApiV1RunsRunIdPatchMutationBody = UpdateRunRequest
    export type UpdateRunApiV1RunsRunIdPatchMutationError = HTTPValidationError

    /**
 * @summary Update Run
 */
export const useUpdateRunApiV1RunsRunIdPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRunApiV1RunsRunIdPatch>>, TError,{runId: string;data: UpdateRunRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateRunApiV1RunsRunIdPatch>>,
        TError,
        {runId: string;data: UpdateRunRequest},
        TContext
      > => {

      const mutationOptions = getUpdateRunApiV1RunsRunIdPatchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Delete Run
 */
export const deleteRunApiV1RunsRunIdDelete = (
    runId: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/runs/${runId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteRunApiV1RunsRunIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRunApiV1RunsRunIdDelete>>, TError,{runId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteRunApiV1RunsRunIdDelete>>, TError,{runId: string}, TContext> => {

const mutationKey = ['deleteRunApiV1RunsRunIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteRunApiV1RunsRunIdDelete>>, {runId: string}> = (props) => {
          const {runId} = props ?? {};

          return  deleteRunApiV1RunsRunIdDelete(runId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteRunApiV1RunsRunIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteRunApiV1RunsRunIdDelete>>>
    
    export type DeleteRunApiV1RunsRunIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Run
 */
export const useDeleteRunApiV1RunsRunIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRunApiV1RunsRunIdDelete>>, TError,{runId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteRunApiV1RunsRunIdDelete>>,
        TError,
        {runId: string},
        TContext
      > => {

      const mutationOptions = getDeleteRunApiV1RunsRunIdDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Wipe a run's plates, wells, readouts, dose-response curves, and QC.

The run row itself, its metadata, and any attached files are kept.
Only DRAFT and IN_PROGRESS runs may be reset. Locked or terminal
runs are rejected.
 * @summary Reset Run Data
 */
export const resetRunDataApiV1RunsRunIdResetDataPost = (
    runId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ResetRunDataResponse>(
      {url: `/api/v1/runs/${runId}/reset-data`, method: 'POST', signal
    },
      );
    }
  


export const getResetRunDataApiV1RunsRunIdResetDataPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resetRunDataApiV1RunsRunIdResetDataPost>>, TError,{runId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof resetRunDataApiV1RunsRunIdResetDataPost>>, TError,{runId: string}, TContext> => {

const mutationKey = ['resetRunDataApiV1RunsRunIdResetDataPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof resetRunDataApiV1RunsRunIdResetDataPost>>, {runId: string}> = (props) => {
          const {runId} = props ?? {};

          return  resetRunDataApiV1RunsRunIdResetDataPost(runId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ResetRunDataApiV1RunsRunIdResetDataPostMutationResult = NonNullable<Awaited<ReturnType<typeof resetRunDataApiV1RunsRunIdResetDataPost>>>
    
    export type ResetRunDataApiV1RunsRunIdResetDataPostMutationError = HTTPValidationError

    /**
 * @summary Reset Run Data
 */
export const useResetRunDataApiV1RunsRunIdResetDataPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resetRunDataApiV1RunsRunIdResetDataPost>>, TError,{runId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof resetRunDataApiV1RunsRunIdResetDataPost>>,
        TError,
        {runId: string},
        TContext
      > => {

      const mutationOptions = getResetRunDataApiV1RunsRunIdResetDataPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Start Run
 */
export const startRunApiV1RunsRunIdStartPost = (
    runId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<RunResponse>(
      {url: `/api/v1/runs/${runId}/start`, method: 'POST', signal
    },
      );
    }
  


export const getStartRunApiV1RunsRunIdStartPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startRunApiV1RunsRunIdStartPost>>, TError,{runId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof startRunApiV1RunsRunIdStartPost>>, TError,{runId: string}, TContext> => {

const mutationKey = ['startRunApiV1RunsRunIdStartPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof startRunApiV1RunsRunIdStartPost>>, {runId: string}> = (props) => {
          const {runId} = props ?? {};

          return  startRunApiV1RunsRunIdStartPost(runId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StartRunApiV1RunsRunIdStartPostMutationResult = NonNullable<Awaited<ReturnType<typeof startRunApiV1RunsRunIdStartPost>>>
    
    export type StartRunApiV1RunsRunIdStartPostMutationError = HTTPValidationError

    /**
 * @summary Start Run
 */
export const useStartRunApiV1RunsRunIdStartPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startRunApiV1RunsRunIdStartPost>>, TError,{runId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof startRunApiV1RunsRunIdStartPost>>,
        TError,
        {runId: string},
        TContext
      > => {

      const mutationOptions = getStartRunApiV1RunsRunIdStartPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Complete Run
 */
export const completeRunApiV1RunsRunIdCompletePost = (
    runId: string,
    completeRunRequest: CompleteRunRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<RunResponse>(
      {url: `/api/v1/runs/${runId}/complete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: completeRunRequest, signal
    },
      );
    }
  


export const getCompleteRunApiV1RunsRunIdCompletePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeRunApiV1RunsRunIdCompletePost>>, TError,{runId: string;data: CompleteRunRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof completeRunApiV1RunsRunIdCompletePost>>, TError,{runId: string;data: CompleteRunRequest}, TContext> => {

const mutationKey = ['completeRunApiV1RunsRunIdCompletePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof completeRunApiV1RunsRunIdCompletePost>>, {runId: string;data: CompleteRunRequest}> = (props) => {
          const {runId,data} = props ?? {};

          return  completeRunApiV1RunsRunIdCompletePost(runId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CompleteRunApiV1RunsRunIdCompletePostMutationResult = NonNullable<Awaited<ReturnType<typeof completeRunApiV1RunsRunIdCompletePost>>>
    export type CompleteRunApiV1RunsRunIdCompletePostMutationBody = CompleteRunRequest
    export type CompleteRunApiV1RunsRunIdCompletePostMutationError = HTTPValidationError

    /**
 * @summary Complete Run
 */
export const useCompleteRunApiV1RunsRunIdCompletePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeRunApiV1RunsRunIdCompletePost>>, TError,{runId: string;data: CompleteRunRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof completeRunApiV1RunsRunIdCompletePost>>,
        TError,
        {runId: string;data: CompleteRunRequest},
        TContext
      > => {

      const mutationOptions = getCompleteRunApiV1RunsRunIdCompletePostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Approve Run
 */
export const approveRunApiV1RunsRunIdApprovePost = (
    runId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<RunResponse>(
      {url: `/api/v1/runs/${runId}/approve`, method: 'POST', signal
    },
      );
    }
  


export const getApproveRunApiV1RunsRunIdApprovePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof approveRunApiV1RunsRunIdApprovePost>>, TError,{runId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof approveRunApiV1RunsRunIdApprovePost>>, TError,{runId: string}, TContext> => {

const mutationKey = ['approveRunApiV1RunsRunIdApprovePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof approveRunApiV1RunsRunIdApprovePost>>, {runId: string}> = (props) => {
          const {runId} = props ?? {};

          return  approveRunApiV1RunsRunIdApprovePost(runId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ApproveRunApiV1RunsRunIdApprovePostMutationResult = NonNullable<Awaited<ReturnType<typeof approveRunApiV1RunsRunIdApprovePost>>>
    
    export type ApproveRunApiV1RunsRunIdApprovePostMutationError = HTTPValidationError

    /**
 * @summary Approve Run
 */
export const useApproveRunApiV1RunsRunIdApprovePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof approveRunApiV1RunsRunIdApprovePost>>, TError,{runId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof approveRunApiV1RunsRunIdApprovePost>>,
        TError,
        {runId: string},
        TContext
      > => {

      const mutationOptions = getApproveRunApiV1RunsRunIdApprovePostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Reject Run
 */
export const rejectRunApiV1RunsRunIdRejectPost = (
    runId: string,
    rejectRequest: RejectRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<RunResponse>(
      {url: `/api/v1/runs/${runId}/reject`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: rejectRequest, signal
    },
      );
    }
  


export const getRejectRunApiV1RunsRunIdRejectPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rejectRunApiV1RunsRunIdRejectPost>>, TError,{runId: string;data: RejectRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof rejectRunApiV1RunsRunIdRejectPost>>, TError,{runId: string;data: RejectRequest}, TContext> => {

const mutationKey = ['rejectRunApiV1RunsRunIdRejectPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof rejectRunApiV1RunsRunIdRejectPost>>, {runId: string;data: RejectRequest}> = (props) => {
          const {runId,data} = props ?? {};

          return  rejectRunApiV1RunsRunIdRejectPost(runId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RejectRunApiV1RunsRunIdRejectPostMutationResult = NonNullable<Awaited<ReturnType<typeof rejectRunApiV1RunsRunIdRejectPost>>>
    export type RejectRunApiV1RunsRunIdRejectPostMutationBody = RejectRequest
    export type RejectRunApiV1RunsRunIdRejectPostMutationError = HTTPValidationError

    /**
 * @summary Reject Run
 */
export const useRejectRunApiV1RunsRunIdRejectPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rejectRunApiV1RunsRunIdRejectPost>>, TError,{runId: string;data: RejectRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof rejectRunApiV1RunsRunIdRejectPost>>,
        TError,
        {runId: string;data: RejectRequest},
        TContext
      > => {

      const mutationOptions = getRejectRunApiV1RunsRunIdRejectPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Lock Run
 */
export const lockRunApiV1RunsRunIdLockPost = (
    runId: string,
    lockRequest: LockRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<RunResponse>(
      {url: `/api/v1/runs/${runId}/lock`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: lockRequest, signal
    },
      );
    }
  


export const getLockRunApiV1RunsRunIdLockPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof lockRunApiV1RunsRunIdLockPost>>, TError,{runId: string;data: LockRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof lockRunApiV1RunsRunIdLockPost>>, TError,{runId: string;data: LockRequest}, TContext> => {

const mutationKey = ['lockRunApiV1RunsRunIdLockPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof lockRunApiV1RunsRunIdLockPost>>, {runId: string;data: LockRequest}> = (props) => {
          const {runId,data} = props ?? {};

          return  lockRunApiV1RunsRunIdLockPost(runId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LockRunApiV1RunsRunIdLockPostMutationResult = NonNullable<Awaited<ReturnType<typeof lockRunApiV1RunsRunIdLockPost>>>
    export type LockRunApiV1RunsRunIdLockPostMutationBody = LockRequest
    export type LockRunApiV1RunsRunIdLockPostMutationError = HTTPValidationError

    /**
 * @summary Lock Run
 */
export const useLockRunApiV1RunsRunIdLockPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof lockRunApiV1RunsRunIdLockPost>>, TError,{runId: string;data: LockRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof lockRunApiV1RunsRunIdLockPost>>,
        TError,
        {runId: string;data: LockRequest},
        TContext
      > => {

      const mutationOptions = getLockRunApiV1RunsRunIdLockPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Unlock Run
 */
export const unlockRunApiV1RunsRunIdUnlockPost = (
    runId: string,
    unlockRequest: UnlockRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<RunResponse>(
      {url: `/api/v1/runs/${runId}/unlock`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: unlockRequest, signal
    },
      );
    }
  


export const getUnlockRunApiV1RunsRunIdUnlockPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unlockRunApiV1RunsRunIdUnlockPost>>, TError,{runId: string;data: UnlockRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof unlockRunApiV1RunsRunIdUnlockPost>>, TError,{runId: string;data: UnlockRequest}, TContext> => {

const mutationKey = ['unlockRunApiV1RunsRunIdUnlockPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof unlockRunApiV1RunsRunIdUnlockPost>>, {runId: string;data: UnlockRequest}> = (props) => {
          const {runId,data} = props ?? {};

          return  unlockRunApiV1RunsRunIdUnlockPost(runId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UnlockRunApiV1RunsRunIdUnlockPostMutationResult = NonNullable<Awaited<ReturnType<typeof unlockRunApiV1RunsRunIdUnlockPost>>>
    export type UnlockRunApiV1RunsRunIdUnlockPostMutationBody = UnlockRequest
    export type UnlockRunApiV1RunsRunIdUnlockPostMutationError = HTTPValidationError

    /**
 * @summary Unlock Run
 */
export const useUnlockRunApiV1RunsRunIdUnlockPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unlockRunApiV1RunsRunIdUnlockPost>>, TError,{runId: string;data: UnlockRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof unlockRunApiV1RunsRunIdUnlockPost>>,
        TError,
        {runId: string;data: UnlockRequest},
        TContext
      > => {

      const mutationOptions = getUnlockRunApiV1RunsRunIdUnlockPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    