/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Chem-Vault
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  BatchCurvesRequest,
  BatchCurvesResponse,
  HTTPValidationError
} from '.././model';

import { customInstance } from '.././custom-instance';




/**
 * Look up dose-response curves by id, scoped to the caller's workspace.

Returns an empty list for missing ids or curves in a foreign workspace.
Cap: 500 ids per request (enforced by Pydantic ``max_length`` on the request body).

Note: identity fields (``registration_number``, ``molecule_name``,
``synonyms``, ``smiles``, ``batch_number``) are intentionally returned
as ``None`` — callers correlate curves to molecules by ``molecule_id``
and fetch identity through a separate query (e.g. ``useMoleculesByIds``
on the campaign frontend). Use the enriched ``GET
/api/v1/protocols/{protocol_id}/compounds/{molecule_id}/dose-response``
endpoint if you need identity fields populated.
 * @summary Get Curves Batch
 */
export const getCurvesBatchApiV1DoseResponseCurvesBatchPost = (
    batchCurvesRequest: BatchCurvesRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<BatchCurvesResponse>(
      {url: `/api/v1/dose-response/curves:batch`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: batchCurvesRequest, signal
    },
      );
    }
  


export const getGetCurvesBatchApiV1DoseResponseCurvesBatchPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCurvesBatchApiV1DoseResponseCurvesBatchPost>>, TError,{data: BatchCurvesRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof getCurvesBatchApiV1DoseResponseCurvesBatchPost>>, TError,{data: BatchCurvesRequest}, TContext> => {

const mutationKey = ['getCurvesBatchApiV1DoseResponseCurvesBatchPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getCurvesBatchApiV1DoseResponseCurvesBatchPost>>, {data: BatchCurvesRequest}> = (props) => {
          const {data} = props ?? {};

          return  getCurvesBatchApiV1DoseResponseCurvesBatchPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type GetCurvesBatchApiV1DoseResponseCurvesBatchPostMutationResult = NonNullable<Awaited<ReturnType<typeof getCurvesBatchApiV1DoseResponseCurvesBatchPost>>>
    export type GetCurvesBatchApiV1DoseResponseCurvesBatchPostMutationBody = BatchCurvesRequest
    export type GetCurvesBatchApiV1DoseResponseCurvesBatchPostMutationError = HTTPValidationError

    /**
 * @summary Get Curves Batch
 */
export const useGetCurvesBatchApiV1DoseResponseCurvesBatchPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCurvesBatchApiV1DoseResponseCurvesBatchPost>>, TError,{data: BatchCurvesRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getCurvesBatchApiV1DoseResponseCurvesBatchPost>>,
        TError,
        {data: BatchCurvesRequest},
        TContext
      > => {

      const mutationOptions = getGetCurvesBatchApiV1DoseResponseCurvesBatchPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    