/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Chem-Vault
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BodyPreviewImportApiV1PlatesImportPreviewPost,
  ChemVaultInterfaceRoutesPlateImportImportPreviewResponse,
  CreateImportTemplateBody,
  ExecuteImportBody,
  ExecuteImportResponse,
  HTTPValidationError,
  ImportTemplateResponse,
  ValidateImportBody,
  ValidationResultResponse
} from '.././model';

import { customInstance } from '.././custom-instance';




/**
 * @summary Preview Import
 */
export const previewImportApiV1PlatesImportPreviewPost = (
    bodyPreviewImportApiV1PlatesImportPreviewPost: BodyPreviewImportApiV1PlatesImportPreviewPost,
 signal?: AbortSignal
) => {
      
      const formData = new FormData();
formData.append(`file`, bodyPreviewImportApiV1PlatesImportPreviewPost.file)

      return customInstance<ChemVaultInterfaceRoutesPlateImportImportPreviewResponse>(
      {url: `/api/v1/plates/import/preview`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData, signal
    },
      );
    }
  


export const getPreviewImportApiV1PlatesImportPreviewPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof previewImportApiV1PlatesImportPreviewPost>>, TError,{data: BodyPreviewImportApiV1PlatesImportPreviewPost}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof previewImportApiV1PlatesImportPreviewPost>>, TError,{data: BodyPreviewImportApiV1PlatesImportPreviewPost}, TContext> => {

const mutationKey = ['previewImportApiV1PlatesImportPreviewPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof previewImportApiV1PlatesImportPreviewPost>>, {data: BodyPreviewImportApiV1PlatesImportPreviewPost}> = (props) => {
          const {data} = props ?? {};

          return  previewImportApiV1PlatesImportPreviewPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PreviewImportApiV1PlatesImportPreviewPostMutationResult = NonNullable<Awaited<ReturnType<typeof previewImportApiV1PlatesImportPreviewPost>>>
    export type PreviewImportApiV1PlatesImportPreviewPostMutationBody = BodyPreviewImportApiV1PlatesImportPreviewPost
    export type PreviewImportApiV1PlatesImportPreviewPostMutationError = HTTPValidationError

    /**
 * @summary Preview Import
 */
export const usePreviewImportApiV1PlatesImportPreviewPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof previewImportApiV1PlatesImportPreviewPost>>, TError,{data: BodyPreviewImportApiV1PlatesImportPreviewPost}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof previewImportApiV1PlatesImportPreviewPost>>,
        TError,
        {data: BodyPreviewImportApiV1PlatesImportPreviewPost},
        TContext
      > => {

      const mutationOptions = getPreviewImportApiV1PlatesImportPreviewPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Validate Import
 */
export const validateImportApiV1PlatesImportValidatePost = (
    validateImportBody: ValidateImportBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ValidationResultResponse>(
      {url: `/api/v1/plates/import/validate`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: validateImportBody, signal
    },
      );
    }
  


export const getValidateImportApiV1PlatesImportValidatePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof validateImportApiV1PlatesImportValidatePost>>, TError,{data: ValidateImportBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof validateImportApiV1PlatesImportValidatePost>>, TError,{data: ValidateImportBody}, TContext> => {

const mutationKey = ['validateImportApiV1PlatesImportValidatePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof validateImportApiV1PlatesImportValidatePost>>, {data: ValidateImportBody}> = (props) => {
          const {data} = props ?? {};

          return  validateImportApiV1PlatesImportValidatePost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ValidateImportApiV1PlatesImportValidatePostMutationResult = NonNullable<Awaited<ReturnType<typeof validateImportApiV1PlatesImportValidatePost>>>
    export type ValidateImportApiV1PlatesImportValidatePostMutationBody = ValidateImportBody
    export type ValidateImportApiV1PlatesImportValidatePostMutationError = HTTPValidationError

    /**
 * @summary Validate Import
 */
export const useValidateImportApiV1PlatesImportValidatePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof validateImportApiV1PlatesImportValidatePost>>, TError,{data: ValidateImportBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof validateImportApiV1PlatesImportValidatePost>>,
        TError,
        {data: ValidateImportBody},
        TContext
      > => {

      const mutationOptions = getValidateImportApiV1PlatesImportValidatePostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Execute Import Data
 */
export const executeImportDataApiV1PlatesImportExecutePost = (
    executeImportBody: ExecuteImportBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ExecuteImportResponse>(
      {url: `/api/v1/plates/import/execute`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: executeImportBody, signal
    },
      );
    }
  


export const getExecuteImportDataApiV1PlatesImportExecutePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof executeImportDataApiV1PlatesImportExecutePost>>, TError,{data: ExecuteImportBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof executeImportDataApiV1PlatesImportExecutePost>>, TError,{data: ExecuteImportBody}, TContext> => {

const mutationKey = ['executeImportDataApiV1PlatesImportExecutePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof executeImportDataApiV1PlatesImportExecutePost>>, {data: ExecuteImportBody}> = (props) => {
          const {data} = props ?? {};

          return  executeImportDataApiV1PlatesImportExecutePost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ExecuteImportDataApiV1PlatesImportExecutePostMutationResult = NonNullable<Awaited<ReturnType<typeof executeImportDataApiV1PlatesImportExecutePost>>>
    export type ExecuteImportDataApiV1PlatesImportExecutePostMutationBody = ExecuteImportBody
    export type ExecuteImportDataApiV1PlatesImportExecutePostMutationError = HTTPValidationError

    /**
 * @summary Execute Import Data
 */
export const useExecuteImportDataApiV1PlatesImportExecutePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof executeImportDataApiV1PlatesImportExecutePost>>, TError,{data: ExecuteImportBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof executeImportDataApiV1PlatesImportExecutePost>>,
        TError,
        {data: ExecuteImportBody},
        TContext
      > => {

      const mutationOptions = getExecuteImportDataApiV1PlatesImportExecutePostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List Import Templates
 */
export const listImportTemplatesApiV1ImportTemplatesGet = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<ImportTemplateResponse[]>(
      {url: `/api/v1/import-templates`, method: 'GET', signal
    },
      );
    }
  



export const getListImportTemplatesApiV1ImportTemplatesGetQueryKey = () => {
    return [
    `/api/v1/import-templates`
    ] as const;
    }

    
export const getListImportTemplatesApiV1ImportTemplatesGetQueryOptions = <TData = Awaited<ReturnType<typeof listImportTemplatesApiV1ImportTemplatesGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listImportTemplatesApiV1ImportTemplatesGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListImportTemplatesApiV1ImportTemplatesGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listImportTemplatesApiV1ImportTemplatesGet>>> = ({ signal }) => listImportTemplatesApiV1ImportTemplatesGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listImportTemplatesApiV1ImportTemplatesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListImportTemplatesApiV1ImportTemplatesGetQueryResult = NonNullable<Awaited<ReturnType<typeof listImportTemplatesApiV1ImportTemplatesGet>>>
export type ListImportTemplatesApiV1ImportTemplatesGetQueryError = unknown


export function useListImportTemplatesApiV1ImportTemplatesGet<TData = Awaited<ReturnType<typeof listImportTemplatesApiV1ImportTemplatesGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listImportTemplatesApiV1ImportTemplatesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listImportTemplatesApiV1ImportTemplatesGet>>,
          TError,
          Awaited<ReturnType<typeof listImportTemplatesApiV1ImportTemplatesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListImportTemplatesApiV1ImportTemplatesGet<TData = Awaited<ReturnType<typeof listImportTemplatesApiV1ImportTemplatesGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listImportTemplatesApiV1ImportTemplatesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listImportTemplatesApiV1ImportTemplatesGet>>,
          TError,
          Awaited<ReturnType<typeof listImportTemplatesApiV1ImportTemplatesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListImportTemplatesApiV1ImportTemplatesGet<TData = Awaited<ReturnType<typeof listImportTemplatesApiV1ImportTemplatesGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listImportTemplatesApiV1ImportTemplatesGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Import Templates
 */

export function useListImportTemplatesApiV1ImportTemplatesGet<TData = Awaited<ReturnType<typeof listImportTemplatesApiV1ImportTemplatesGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listImportTemplatesApiV1ImportTemplatesGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListImportTemplatesApiV1ImportTemplatesGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create Import Template
 */
export const createImportTemplateApiV1ImportTemplatesPost = (
    createImportTemplateBody: CreateImportTemplateBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ImportTemplateResponse>(
      {url: `/api/v1/import-templates`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createImportTemplateBody, signal
    },
      );
    }
  


export const getCreateImportTemplateApiV1ImportTemplatesPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createImportTemplateApiV1ImportTemplatesPost>>, TError,{data: CreateImportTemplateBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createImportTemplateApiV1ImportTemplatesPost>>, TError,{data: CreateImportTemplateBody}, TContext> => {

const mutationKey = ['createImportTemplateApiV1ImportTemplatesPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createImportTemplateApiV1ImportTemplatesPost>>, {data: CreateImportTemplateBody}> = (props) => {
          const {data} = props ?? {};

          return  createImportTemplateApiV1ImportTemplatesPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateImportTemplateApiV1ImportTemplatesPostMutationResult = NonNullable<Awaited<ReturnType<typeof createImportTemplateApiV1ImportTemplatesPost>>>
    export type CreateImportTemplateApiV1ImportTemplatesPostMutationBody = CreateImportTemplateBody
    export type CreateImportTemplateApiV1ImportTemplatesPostMutationError = HTTPValidationError

    /**
 * @summary Create Import Template
 */
export const useCreateImportTemplateApiV1ImportTemplatesPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createImportTemplateApiV1ImportTemplatesPost>>, TError,{data: CreateImportTemplateBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createImportTemplateApiV1ImportTemplatesPost>>,
        TError,
        {data: CreateImportTemplateBody},
        TContext
      > => {

      const mutationOptions = getCreateImportTemplateApiV1ImportTemplatesPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Delete Import Template
 */
export const deleteImportTemplateApiV1ImportTemplatesTemplateIdDelete = (
    templateId: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/import-templates/${templateId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteImportTemplateApiV1ImportTemplatesTemplateIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteImportTemplateApiV1ImportTemplatesTemplateIdDelete>>, TError,{templateId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteImportTemplateApiV1ImportTemplatesTemplateIdDelete>>, TError,{templateId: string}, TContext> => {

const mutationKey = ['deleteImportTemplateApiV1ImportTemplatesTemplateIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteImportTemplateApiV1ImportTemplatesTemplateIdDelete>>, {templateId: string}> = (props) => {
          const {templateId} = props ?? {};

          return  deleteImportTemplateApiV1ImportTemplatesTemplateIdDelete(templateId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteImportTemplateApiV1ImportTemplatesTemplateIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteImportTemplateApiV1ImportTemplatesTemplateIdDelete>>>
    
    export type DeleteImportTemplateApiV1ImportTemplatesTemplateIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Import Template
 */
export const useDeleteImportTemplateApiV1ImportTemplatesTemplateIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteImportTemplateApiV1ImportTemplatesTemplateIdDelete>>, TError,{templateId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteImportTemplateApiV1ImportTemplatesTemplateIdDelete>>,
        TError,
        {templateId: string},
        TContext
      > => {

      const mutationOptions = getDeleteImportTemplateApiV1ImportTemplatesTemplateIdDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    