/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Chem-Vault
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateCustomFieldBody,
  CustomFieldResponse,
  HTTPValidationError,
  ListCustomFieldsApiV1CustomFieldsGetParams,
  UpdateCustomFieldBody
} from '.././model';

import { customInstance } from '.././custom-instance';




/**
 * @summary List Custom Fields
 */
export const listCustomFieldsApiV1CustomFieldsGet = (
    params?: ListCustomFieldsApiV1CustomFieldsGetParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<CustomFieldResponse[]>(
      {url: `/api/v1/custom-fields`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getListCustomFieldsApiV1CustomFieldsGetQueryKey = (params?: ListCustomFieldsApiV1CustomFieldsGetParams,) => {
    return [
    `/api/v1/custom-fields`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListCustomFieldsApiV1CustomFieldsGetQueryOptions = <TData = Awaited<ReturnType<typeof listCustomFieldsApiV1CustomFieldsGet>>, TError = HTTPValidationError>(params?: ListCustomFieldsApiV1CustomFieldsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCustomFieldsApiV1CustomFieldsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListCustomFieldsApiV1CustomFieldsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listCustomFieldsApiV1CustomFieldsGet>>> = ({ signal }) => listCustomFieldsApiV1CustomFieldsGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listCustomFieldsApiV1CustomFieldsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListCustomFieldsApiV1CustomFieldsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listCustomFieldsApiV1CustomFieldsGet>>>
export type ListCustomFieldsApiV1CustomFieldsGetQueryError = HTTPValidationError


export function useListCustomFieldsApiV1CustomFieldsGet<TData = Awaited<ReturnType<typeof listCustomFieldsApiV1CustomFieldsGet>>, TError = HTTPValidationError>(
 params: undefined |  ListCustomFieldsApiV1CustomFieldsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCustomFieldsApiV1CustomFieldsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCustomFieldsApiV1CustomFieldsGet>>,
          TError,
          Awaited<ReturnType<typeof listCustomFieldsApiV1CustomFieldsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListCustomFieldsApiV1CustomFieldsGet<TData = Awaited<ReturnType<typeof listCustomFieldsApiV1CustomFieldsGet>>, TError = HTTPValidationError>(
 params?: ListCustomFieldsApiV1CustomFieldsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCustomFieldsApiV1CustomFieldsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCustomFieldsApiV1CustomFieldsGet>>,
          TError,
          Awaited<ReturnType<typeof listCustomFieldsApiV1CustomFieldsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListCustomFieldsApiV1CustomFieldsGet<TData = Awaited<ReturnType<typeof listCustomFieldsApiV1CustomFieldsGet>>, TError = HTTPValidationError>(
 params?: ListCustomFieldsApiV1CustomFieldsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCustomFieldsApiV1CustomFieldsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Custom Fields
 */

export function useListCustomFieldsApiV1CustomFieldsGet<TData = Awaited<ReturnType<typeof listCustomFieldsApiV1CustomFieldsGet>>, TError = HTTPValidationError>(
 params?: ListCustomFieldsApiV1CustomFieldsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCustomFieldsApiV1CustomFieldsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListCustomFieldsApiV1CustomFieldsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create Custom Field
 */
export const createCustomFieldApiV1CustomFieldsPost = (
    createCustomFieldBody: CreateCustomFieldBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<CustomFieldResponse>(
      {url: `/api/v1/custom-fields`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCustomFieldBody, signal
    },
      );
    }
  


export const getCreateCustomFieldApiV1CustomFieldsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCustomFieldApiV1CustomFieldsPost>>, TError,{data: CreateCustomFieldBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createCustomFieldApiV1CustomFieldsPost>>, TError,{data: CreateCustomFieldBody}, TContext> => {

const mutationKey = ['createCustomFieldApiV1CustomFieldsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCustomFieldApiV1CustomFieldsPost>>, {data: CreateCustomFieldBody}> = (props) => {
          const {data} = props ?? {};

          return  createCustomFieldApiV1CustomFieldsPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateCustomFieldApiV1CustomFieldsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createCustomFieldApiV1CustomFieldsPost>>>
    export type CreateCustomFieldApiV1CustomFieldsPostMutationBody = CreateCustomFieldBody
    export type CreateCustomFieldApiV1CustomFieldsPostMutationError = HTTPValidationError

    /**
 * @summary Create Custom Field
 */
export const useCreateCustomFieldApiV1CustomFieldsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCustomFieldApiV1CustomFieldsPost>>, TError,{data: CreateCustomFieldBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createCustomFieldApiV1CustomFieldsPost>>,
        TError,
        {data: CreateCustomFieldBody},
        TContext
      > => {

      const mutationOptions = getCreateCustomFieldApiV1CustomFieldsPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Update Custom Field
 */
export const updateCustomFieldApiV1CustomFieldsFieldIdPatch = (
    fieldId: string,
    updateCustomFieldBody: UpdateCustomFieldBody,
 ) => {
      
      
      return customInstance<CustomFieldResponse>(
      {url: `/api/v1/custom-fields/${fieldId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateCustomFieldBody
    },
      );
    }
  


export const getUpdateCustomFieldApiV1CustomFieldsFieldIdPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCustomFieldApiV1CustomFieldsFieldIdPatch>>, TError,{fieldId: string;data: UpdateCustomFieldBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateCustomFieldApiV1CustomFieldsFieldIdPatch>>, TError,{fieldId: string;data: UpdateCustomFieldBody}, TContext> => {

const mutationKey = ['updateCustomFieldApiV1CustomFieldsFieldIdPatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateCustomFieldApiV1CustomFieldsFieldIdPatch>>, {fieldId: string;data: UpdateCustomFieldBody}> = (props) => {
          const {fieldId,data} = props ?? {};

          return  updateCustomFieldApiV1CustomFieldsFieldIdPatch(fieldId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateCustomFieldApiV1CustomFieldsFieldIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateCustomFieldApiV1CustomFieldsFieldIdPatch>>>
    export type UpdateCustomFieldApiV1CustomFieldsFieldIdPatchMutationBody = UpdateCustomFieldBody
    export type UpdateCustomFieldApiV1CustomFieldsFieldIdPatchMutationError = HTTPValidationError

    /**
 * @summary Update Custom Field
 */
export const useUpdateCustomFieldApiV1CustomFieldsFieldIdPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCustomFieldApiV1CustomFieldsFieldIdPatch>>, TError,{fieldId: string;data: UpdateCustomFieldBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateCustomFieldApiV1CustomFieldsFieldIdPatch>>,
        TError,
        {fieldId: string;data: UpdateCustomFieldBody},
        TContext
      > => {

      const mutationOptions = getUpdateCustomFieldApiV1CustomFieldsFieldIdPatchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Delete Custom Field
 */
export const deleteCustomFieldApiV1CustomFieldsFieldIdDelete = (
    fieldId: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/custom-fields/${fieldId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteCustomFieldApiV1CustomFieldsFieldIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCustomFieldApiV1CustomFieldsFieldIdDelete>>, TError,{fieldId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteCustomFieldApiV1CustomFieldsFieldIdDelete>>, TError,{fieldId: string}, TContext> => {

const mutationKey = ['deleteCustomFieldApiV1CustomFieldsFieldIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCustomFieldApiV1CustomFieldsFieldIdDelete>>, {fieldId: string}> = (props) => {
          const {fieldId} = props ?? {};

          return  deleteCustomFieldApiV1CustomFieldsFieldIdDelete(fieldId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteCustomFieldApiV1CustomFieldsFieldIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCustomFieldApiV1CustomFieldsFieldIdDelete>>>
    
    export type DeleteCustomFieldApiV1CustomFieldsFieldIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Custom Field
 */
export const useDeleteCustomFieldApiV1CustomFieldsFieldIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCustomFieldApiV1CustomFieldsFieldIdDelete>>, TError,{fieldId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCustomFieldApiV1CustomFieldsFieldIdDelete>>,
        TError,
        {fieldId: string},
        TContext
      > => {

      const mutationOptions = getDeleteCustomFieldApiV1CustomFieldsFieldIdDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    