/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Chem-Vault
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateRegistrationFormBody,
  HTTPValidationError,
  ListRegistrationFormsApiV1RegistrationFormsGetParams,
  RegistrationFormResponse,
  UpdateRegistrationFormBody
} from '.././model';

import { customInstance } from '.././custom-instance';




/**
 * @summary List Registration Forms
 */
export const listRegistrationFormsApiV1RegistrationFormsGet = (
    params?: ListRegistrationFormsApiV1RegistrationFormsGetParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<RegistrationFormResponse[]>(
      {url: `/api/v1/registration-forms`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getListRegistrationFormsApiV1RegistrationFormsGetQueryKey = (params?: ListRegistrationFormsApiV1RegistrationFormsGetParams,) => {
    return [
    `/api/v1/registration-forms`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListRegistrationFormsApiV1RegistrationFormsGetQueryOptions = <TData = Awaited<ReturnType<typeof listRegistrationFormsApiV1RegistrationFormsGet>>, TError = HTTPValidationError>(params?: ListRegistrationFormsApiV1RegistrationFormsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRegistrationFormsApiV1RegistrationFormsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListRegistrationFormsApiV1RegistrationFormsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listRegistrationFormsApiV1RegistrationFormsGet>>> = ({ signal }) => listRegistrationFormsApiV1RegistrationFormsGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listRegistrationFormsApiV1RegistrationFormsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListRegistrationFormsApiV1RegistrationFormsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listRegistrationFormsApiV1RegistrationFormsGet>>>
export type ListRegistrationFormsApiV1RegistrationFormsGetQueryError = HTTPValidationError


export function useListRegistrationFormsApiV1RegistrationFormsGet<TData = Awaited<ReturnType<typeof listRegistrationFormsApiV1RegistrationFormsGet>>, TError = HTTPValidationError>(
 params: undefined |  ListRegistrationFormsApiV1RegistrationFormsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRegistrationFormsApiV1RegistrationFormsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listRegistrationFormsApiV1RegistrationFormsGet>>,
          TError,
          Awaited<ReturnType<typeof listRegistrationFormsApiV1RegistrationFormsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListRegistrationFormsApiV1RegistrationFormsGet<TData = Awaited<ReturnType<typeof listRegistrationFormsApiV1RegistrationFormsGet>>, TError = HTTPValidationError>(
 params?: ListRegistrationFormsApiV1RegistrationFormsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRegistrationFormsApiV1RegistrationFormsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listRegistrationFormsApiV1RegistrationFormsGet>>,
          TError,
          Awaited<ReturnType<typeof listRegistrationFormsApiV1RegistrationFormsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListRegistrationFormsApiV1RegistrationFormsGet<TData = Awaited<ReturnType<typeof listRegistrationFormsApiV1RegistrationFormsGet>>, TError = HTTPValidationError>(
 params?: ListRegistrationFormsApiV1RegistrationFormsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRegistrationFormsApiV1RegistrationFormsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Registration Forms
 */

export function useListRegistrationFormsApiV1RegistrationFormsGet<TData = Awaited<ReturnType<typeof listRegistrationFormsApiV1RegistrationFormsGet>>, TError = HTTPValidationError>(
 params?: ListRegistrationFormsApiV1RegistrationFormsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRegistrationFormsApiV1RegistrationFormsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListRegistrationFormsApiV1RegistrationFormsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create Registration Form
 */
export const createRegistrationFormApiV1RegistrationFormsPost = (
    createRegistrationFormBody: CreateRegistrationFormBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<RegistrationFormResponse>(
      {url: `/api/v1/registration-forms`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createRegistrationFormBody, signal
    },
      );
    }
  


export const getCreateRegistrationFormApiV1RegistrationFormsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRegistrationFormApiV1RegistrationFormsPost>>, TError,{data: CreateRegistrationFormBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createRegistrationFormApiV1RegistrationFormsPost>>, TError,{data: CreateRegistrationFormBody}, TContext> => {

const mutationKey = ['createRegistrationFormApiV1RegistrationFormsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createRegistrationFormApiV1RegistrationFormsPost>>, {data: CreateRegistrationFormBody}> = (props) => {
          const {data} = props ?? {};

          return  createRegistrationFormApiV1RegistrationFormsPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateRegistrationFormApiV1RegistrationFormsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createRegistrationFormApiV1RegistrationFormsPost>>>
    export type CreateRegistrationFormApiV1RegistrationFormsPostMutationBody = CreateRegistrationFormBody
    export type CreateRegistrationFormApiV1RegistrationFormsPostMutationError = HTTPValidationError

    /**
 * @summary Create Registration Form
 */
export const useCreateRegistrationFormApiV1RegistrationFormsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRegistrationFormApiV1RegistrationFormsPost>>, TError,{data: CreateRegistrationFormBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createRegistrationFormApiV1RegistrationFormsPost>>,
        TError,
        {data: CreateRegistrationFormBody},
        TContext
      > => {

      const mutationOptions = getCreateRegistrationFormApiV1RegistrationFormsPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get Registration Form
 */
export const getRegistrationFormApiV1RegistrationFormsFormIdGet = (
    formId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<RegistrationFormResponse>(
      {url: `/api/v1/registration-forms/${formId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetRegistrationFormApiV1RegistrationFormsFormIdGetQueryKey = (formId?: string,) => {
    return [
    `/api/v1/registration-forms/${formId}`
    ] as const;
    }

    
export const getGetRegistrationFormApiV1RegistrationFormsFormIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getRegistrationFormApiV1RegistrationFormsFormIdGet>>, TError = HTTPValidationError>(formId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRegistrationFormApiV1RegistrationFormsFormIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRegistrationFormApiV1RegistrationFormsFormIdGetQueryKey(formId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRegistrationFormApiV1RegistrationFormsFormIdGet>>> = ({ signal }) => getRegistrationFormApiV1RegistrationFormsFormIdGet(formId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(formId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRegistrationFormApiV1RegistrationFormsFormIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRegistrationFormApiV1RegistrationFormsFormIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getRegistrationFormApiV1RegistrationFormsFormIdGet>>>
export type GetRegistrationFormApiV1RegistrationFormsFormIdGetQueryError = HTTPValidationError


export function useGetRegistrationFormApiV1RegistrationFormsFormIdGet<TData = Awaited<ReturnType<typeof getRegistrationFormApiV1RegistrationFormsFormIdGet>>, TError = HTTPValidationError>(
 formId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRegistrationFormApiV1RegistrationFormsFormIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRegistrationFormApiV1RegistrationFormsFormIdGet>>,
          TError,
          Awaited<ReturnType<typeof getRegistrationFormApiV1RegistrationFormsFormIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRegistrationFormApiV1RegistrationFormsFormIdGet<TData = Awaited<ReturnType<typeof getRegistrationFormApiV1RegistrationFormsFormIdGet>>, TError = HTTPValidationError>(
 formId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRegistrationFormApiV1RegistrationFormsFormIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRegistrationFormApiV1RegistrationFormsFormIdGet>>,
          TError,
          Awaited<ReturnType<typeof getRegistrationFormApiV1RegistrationFormsFormIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRegistrationFormApiV1RegistrationFormsFormIdGet<TData = Awaited<ReturnType<typeof getRegistrationFormApiV1RegistrationFormsFormIdGet>>, TError = HTTPValidationError>(
 formId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRegistrationFormApiV1RegistrationFormsFormIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Registration Form
 */

export function useGetRegistrationFormApiV1RegistrationFormsFormIdGet<TData = Awaited<ReturnType<typeof getRegistrationFormApiV1RegistrationFormsFormIdGet>>, TError = HTTPValidationError>(
 formId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRegistrationFormApiV1RegistrationFormsFormIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRegistrationFormApiV1RegistrationFormsFormIdGetQueryOptions(formId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update Registration Form
 */
export const updateRegistrationFormApiV1RegistrationFormsFormIdPatch = (
    formId: string,
    updateRegistrationFormBody: UpdateRegistrationFormBody,
 ) => {
      
      
      return customInstance<RegistrationFormResponse>(
      {url: `/api/v1/registration-forms/${formId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateRegistrationFormBody
    },
      );
    }
  


export const getUpdateRegistrationFormApiV1RegistrationFormsFormIdPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRegistrationFormApiV1RegistrationFormsFormIdPatch>>, TError,{formId: string;data: UpdateRegistrationFormBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateRegistrationFormApiV1RegistrationFormsFormIdPatch>>, TError,{formId: string;data: UpdateRegistrationFormBody}, TContext> => {

const mutationKey = ['updateRegistrationFormApiV1RegistrationFormsFormIdPatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateRegistrationFormApiV1RegistrationFormsFormIdPatch>>, {formId: string;data: UpdateRegistrationFormBody}> = (props) => {
          const {formId,data} = props ?? {};

          return  updateRegistrationFormApiV1RegistrationFormsFormIdPatch(formId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateRegistrationFormApiV1RegistrationFormsFormIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateRegistrationFormApiV1RegistrationFormsFormIdPatch>>>
    export type UpdateRegistrationFormApiV1RegistrationFormsFormIdPatchMutationBody = UpdateRegistrationFormBody
    export type UpdateRegistrationFormApiV1RegistrationFormsFormIdPatchMutationError = HTTPValidationError

    /**
 * @summary Update Registration Form
 */
export const useUpdateRegistrationFormApiV1RegistrationFormsFormIdPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRegistrationFormApiV1RegistrationFormsFormIdPatch>>, TError,{formId: string;data: UpdateRegistrationFormBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateRegistrationFormApiV1RegistrationFormsFormIdPatch>>,
        TError,
        {formId: string;data: UpdateRegistrationFormBody},
        TContext
      > => {

      const mutationOptions = getUpdateRegistrationFormApiV1RegistrationFormsFormIdPatchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Delete Registration Form
 */
export const deleteRegistrationFormApiV1RegistrationFormsFormIdDelete = (
    formId: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/registration-forms/${formId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteRegistrationFormApiV1RegistrationFormsFormIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRegistrationFormApiV1RegistrationFormsFormIdDelete>>, TError,{formId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteRegistrationFormApiV1RegistrationFormsFormIdDelete>>, TError,{formId: string}, TContext> => {

const mutationKey = ['deleteRegistrationFormApiV1RegistrationFormsFormIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteRegistrationFormApiV1RegistrationFormsFormIdDelete>>, {formId: string}> = (props) => {
          const {formId} = props ?? {};

          return  deleteRegistrationFormApiV1RegistrationFormsFormIdDelete(formId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteRegistrationFormApiV1RegistrationFormsFormIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteRegistrationFormApiV1RegistrationFormsFormIdDelete>>>
    
    export type DeleteRegistrationFormApiV1RegistrationFormsFormIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Registration Form
 */
export const useDeleteRegistrationFormApiV1RegistrationFormsFormIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRegistrationFormApiV1RegistrationFormsFormIdDelete>>, TError,{formId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteRegistrationFormApiV1RegistrationFormsFormIdDelete>>,
        TError,
        {formId: string},
        TContext
      > => {

      const mutationOptions = getDeleteRegistrationFormApiV1RegistrationFormsFormIdDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    