export { OverviewTab } from "./overview-tab";
export { BatchesTab } from "./batches-tab";
export { ActivityTab } from "./activity-tab";
export { CollectionsTab } from "./collections-tab";
export { PlatesTab } from "./plates-tab";
export { RelationshipsTab } from "./relationships-tab";
export { HistoryTab } from "./history-tab";
export { FilesTab } from "./files-tab";
export { ProjectsTab } from "./projects-tab";
