/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Chem-Vault
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateOntologySlotBody,
  HTTPValidationError,
  ListOntologyDescendantsApiV1OntologyDescendantsGetParams,
  OntologySlotResponse,
  OntologyTermResponse,
  SearchOntologyApiV1OntologySearchGetParams,
  UpdateOntologySlotBody
} from '.././model';

import { customInstance } from '.././custom-instance';




/**
 * @summary Search Ontology
 */
export const searchOntologyApiV1OntologySearchGet = (
    params: SearchOntologyApiV1OntologySearchGetParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<OntologyTermResponse[]>(
      {url: `/api/v1/ontology/search`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getSearchOntologyApiV1OntologySearchGetQueryKey = (params?: SearchOntologyApiV1OntologySearchGetParams,) => {
    return [
    `/api/v1/ontology/search`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getSearchOntologyApiV1OntologySearchGetQueryOptions = <TData = Awaited<ReturnType<typeof searchOntologyApiV1OntologySearchGet>>, TError = HTTPValidationError>(params: SearchOntologyApiV1OntologySearchGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchOntologyApiV1OntologySearchGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchOntologyApiV1OntologySearchGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchOntologyApiV1OntologySearchGet>>> = ({ signal }) => searchOntologyApiV1OntologySearchGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchOntologyApiV1OntologySearchGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchOntologyApiV1OntologySearchGetQueryResult = NonNullable<Awaited<ReturnType<typeof searchOntologyApiV1OntologySearchGet>>>
export type SearchOntologyApiV1OntologySearchGetQueryError = HTTPValidationError


export function useSearchOntologyApiV1OntologySearchGet<TData = Awaited<ReturnType<typeof searchOntologyApiV1OntologySearchGet>>, TError = HTTPValidationError>(
 params: SearchOntologyApiV1OntologySearchGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchOntologyApiV1OntologySearchGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchOntologyApiV1OntologySearchGet>>,
          TError,
          Awaited<ReturnType<typeof searchOntologyApiV1OntologySearchGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchOntologyApiV1OntologySearchGet<TData = Awaited<ReturnType<typeof searchOntologyApiV1OntologySearchGet>>, TError = HTTPValidationError>(
 params: SearchOntologyApiV1OntologySearchGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchOntologyApiV1OntologySearchGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchOntologyApiV1OntologySearchGet>>,
          TError,
          Awaited<ReturnType<typeof searchOntologyApiV1OntologySearchGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchOntologyApiV1OntologySearchGet<TData = Awaited<ReturnType<typeof searchOntologyApiV1OntologySearchGet>>, TError = HTTPValidationError>(
 params: SearchOntologyApiV1OntologySearchGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchOntologyApiV1OntologySearchGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Search Ontology
 */

export function useSearchOntologyApiV1OntologySearchGet<TData = Awaited<ReturnType<typeof searchOntologyApiV1OntologySearchGet>>, TError = HTTPValidationError>(
 params: SearchOntologyApiV1OntologySearchGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchOntologyApiV1OntologySearchGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchOntologyApiV1OntologySearchGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * List all descendants of a concept — for dropdown-style selection.
 * @summary List Ontology Descendants
 */
export const listOntologyDescendantsApiV1OntologyDescendantsGet = (
    params: ListOntologyDescendantsApiV1OntologyDescendantsGetParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<OntologyTermResponse[]>(
      {url: `/api/v1/ontology/descendants`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getListOntologyDescendantsApiV1OntologyDescendantsGetQueryKey = (params?: ListOntologyDescendantsApiV1OntologyDescendantsGetParams,) => {
    return [
    `/api/v1/ontology/descendants`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListOntologyDescendantsApiV1OntologyDescendantsGetQueryOptions = <TData = Awaited<ReturnType<typeof listOntologyDescendantsApiV1OntologyDescendantsGet>>, TError = HTTPValidationError>(params: ListOntologyDescendantsApiV1OntologyDescendantsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listOntologyDescendantsApiV1OntologyDescendantsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListOntologyDescendantsApiV1OntologyDescendantsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listOntologyDescendantsApiV1OntologyDescendantsGet>>> = ({ signal }) => listOntologyDescendantsApiV1OntologyDescendantsGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listOntologyDescendantsApiV1OntologyDescendantsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListOntologyDescendantsApiV1OntologyDescendantsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listOntologyDescendantsApiV1OntologyDescendantsGet>>>
export type ListOntologyDescendantsApiV1OntologyDescendantsGetQueryError = HTTPValidationError


export function useListOntologyDescendantsApiV1OntologyDescendantsGet<TData = Awaited<ReturnType<typeof listOntologyDescendantsApiV1OntologyDescendantsGet>>, TError = HTTPValidationError>(
 params: ListOntologyDescendantsApiV1OntologyDescendantsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listOntologyDescendantsApiV1OntologyDescendantsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listOntologyDescendantsApiV1OntologyDescendantsGet>>,
          TError,
          Awaited<ReturnType<typeof listOntologyDescendantsApiV1OntologyDescendantsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListOntologyDescendantsApiV1OntologyDescendantsGet<TData = Awaited<ReturnType<typeof listOntologyDescendantsApiV1OntologyDescendantsGet>>, TError = HTTPValidationError>(
 params: ListOntologyDescendantsApiV1OntologyDescendantsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listOntologyDescendantsApiV1OntologyDescendantsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listOntologyDescendantsApiV1OntologyDescendantsGet>>,
          TError,
          Awaited<ReturnType<typeof listOntologyDescendantsApiV1OntologyDescendantsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListOntologyDescendantsApiV1OntologyDescendantsGet<TData = Awaited<ReturnType<typeof listOntologyDescendantsApiV1OntologyDescendantsGet>>, TError = HTTPValidationError>(
 params: ListOntologyDescendantsApiV1OntologyDescendantsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listOntologyDescendantsApiV1OntologyDescendantsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Ontology Descendants
 */

export function useListOntologyDescendantsApiV1OntologyDescendantsGet<TData = Awaited<ReturnType<typeof listOntologyDescendantsApiV1OntologyDescendantsGet>>, TError = HTTPValidationError>(
 params: ListOntologyDescendantsApiV1OntologyDescendantsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listOntologyDescendantsApiV1OntologyDescendantsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListOntologyDescendantsApiV1OntologyDescendantsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary List Ontology Slots
 */
export const listOntologySlotsApiV1OntologySlotsGet = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<OntologySlotResponse[]>(
      {url: `/api/v1/ontology-slots`, method: 'GET', signal
    },
      );
    }
  



export const getListOntologySlotsApiV1OntologySlotsGetQueryKey = () => {
    return [
    `/api/v1/ontology-slots`
    ] as const;
    }

    
export const getListOntologySlotsApiV1OntologySlotsGetQueryOptions = <TData = Awaited<ReturnType<typeof listOntologySlotsApiV1OntologySlotsGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listOntologySlotsApiV1OntologySlotsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListOntologySlotsApiV1OntologySlotsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listOntologySlotsApiV1OntologySlotsGet>>> = ({ signal }) => listOntologySlotsApiV1OntologySlotsGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listOntologySlotsApiV1OntologySlotsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListOntologySlotsApiV1OntologySlotsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listOntologySlotsApiV1OntologySlotsGet>>>
export type ListOntologySlotsApiV1OntologySlotsGetQueryError = unknown


export function useListOntologySlotsApiV1OntologySlotsGet<TData = Awaited<ReturnType<typeof listOntologySlotsApiV1OntologySlotsGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listOntologySlotsApiV1OntologySlotsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listOntologySlotsApiV1OntologySlotsGet>>,
          TError,
          Awaited<ReturnType<typeof listOntologySlotsApiV1OntologySlotsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListOntologySlotsApiV1OntologySlotsGet<TData = Awaited<ReturnType<typeof listOntologySlotsApiV1OntologySlotsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listOntologySlotsApiV1OntologySlotsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listOntologySlotsApiV1OntologySlotsGet>>,
          TError,
          Awaited<ReturnType<typeof listOntologySlotsApiV1OntologySlotsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListOntologySlotsApiV1OntologySlotsGet<TData = Awaited<ReturnType<typeof listOntologySlotsApiV1OntologySlotsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listOntologySlotsApiV1OntologySlotsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Ontology Slots
 */

export function useListOntologySlotsApiV1OntologySlotsGet<TData = Awaited<ReturnType<typeof listOntologySlotsApiV1OntologySlotsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listOntologySlotsApiV1OntologySlotsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListOntologySlotsApiV1OntologySlotsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create Ontology Slot
 */
export const createOntologySlotApiV1OntologySlotsPost = (
    createOntologySlotBody: CreateOntologySlotBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<OntologySlotResponse>(
      {url: `/api/v1/ontology-slots`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createOntologySlotBody, signal
    },
      );
    }
  


export const getCreateOntologySlotApiV1OntologySlotsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOntologySlotApiV1OntologySlotsPost>>, TError,{data: CreateOntologySlotBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createOntologySlotApiV1OntologySlotsPost>>, TError,{data: CreateOntologySlotBody}, TContext> => {

const mutationKey = ['createOntologySlotApiV1OntologySlotsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createOntologySlotApiV1OntologySlotsPost>>, {data: CreateOntologySlotBody}> = (props) => {
          const {data} = props ?? {};

          return  createOntologySlotApiV1OntologySlotsPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateOntologySlotApiV1OntologySlotsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createOntologySlotApiV1OntologySlotsPost>>>
    export type CreateOntologySlotApiV1OntologySlotsPostMutationBody = CreateOntologySlotBody
    export type CreateOntologySlotApiV1OntologySlotsPostMutationError = HTTPValidationError

    /**
 * @summary Create Ontology Slot
 */
export const useCreateOntologySlotApiV1OntologySlotsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOntologySlotApiV1OntologySlotsPost>>, TError,{data: CreateOntologySlotBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createOntologySlotApiV1OntologySlotsPost>>,
        TError,
        {data: CreateOntologySlotBody},
        TContext
      > => {

      const mutationOptions = getCreateOntologySlotApiV1OntologySlotsPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Update Ontology Slot
 */
export const updateOntologySlotApiV1OntologySlotsSlotIdPatch = (
    slotId: string,
    updateOntologySlotBody: UpdateOntologySlotBody,
 ) => {
      
      
      return customInstance<OntologySlotResponse>(
      {url: `/api/v1/ontology-slots/${slotId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateOntologySlotBody
    },
      );
    }
  


export const getUpdateOntologySlotApiV1OntologySlotsSlotIdPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOntologySlotApiV1OntologySlotsSlotIdPatch>>, TError,{slotId: string;data: UpdateOntologySlotBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateOntologySlotApiV1OntologySlotsSlotIdPatch>>, TError,{slotId: string;data: UpdateOntologySlotBody}, TContext> => {

const mutationKey = ['updateOntologySlotApiV1OntologySlotsSlotIdPatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateOntologySlotApiV1OntologySlotsSlotIdPatch>>, {slotId: string;data: UpdateOntologySlotBody}> = (props) => {
          const {slotId,data} = props ?? {};

          return  updateOntologySlotApiV1OntologySlotsSlotIdPatch(slotId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateOntologySlotApiV1OntologySlotsSlotIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateOntologySlotApiV1OntologySlotsSlotIdPatch>>>
    export type UpdateOntologySlotApiV1OntologySlotsSlotIdPatchMutationBody = UpdateOntologySlotBody
    export type UpdateOntologySlotApiV1OntologySlotsSlotIdPatchMutationError = HTTPValidationError

    /**
 * @summary Update Ontology Slot
 */
export const useUpdateOntologySlotApiV1OntologySlotsSlotIdPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOntologySlotApiV1OntologySlotsSlotIdPatch>>, TError,{slotId: string;data: UpdateOntologySlotBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateOntologySlotApiV1OntologySlotsSlotIdPatch>>,
        TError,
        {slotId: string;data: UpdateOntologySlotBody},
        TContext
      > => {

      const mutationOptions = getUpdateOntologySlotApiV1OntologySlotsSlotIdPatchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Delete Ontology Slot
 */
export const deleteOntologySlotApiV1OntologySlotsSlotIdDelete = (
    slotId: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/ontology-slots/${slotId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteOntologySlotApiV1OntologySlotsSlotIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOntologySlotApiV1OntologySlotsSlotIdDelete>>, TError,{slotId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteOntologySlotApiV1OntologySlotsSlotIdDelete>>, TError,{slotId: string}, TContext> => {

const mutationKey = ['deleteOntologySlotApiV1OntologySlotsSlotIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteOntologySlotApiV1OntologySlotsSlotIdDelete>>, {slotId: string}> = (props) => {
          const {slotId} = props ?? {};

          return  deleteOntologySlotApiV1OntologySlotsSlotIdDelete(slotId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteOntologySlotApiV1OntologySlotsSlotIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteOntologySlotApiV1OntologySlotsSlotIdDelete>>>
    
    export type DeleteOntologySlotApiV1OntologySlotsSlotIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Ontology Slot
 */
export const useDeleteOntologySlotApiV1OntologySlotsSlotIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOntologySlotApiV1OntologySlotsSlotIdDelete>>, TError,{slotId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteOntologySlotApiV1OntologySlotsSlotIdDelete>>,
        TError,
        {slotId: string},
        TContext
      > => {

      const mutationOptions = getDeleteOntologySlotApiV1OntologySlotsSlotIdDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    