/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Chem-Vault
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateVocabularyBody,
  HTTPValidationError,
  UpdateVocabularyBody,
  VocabularyResponse
} from '.././model';

import { customInstance } from '.././custom-instance';




/**
 * @summary List Vocabularies
 */
export const listVocabulariesApiV1VocabulariesGet = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<VocabularyResponse[]>(
      {url: `/api/v1/vocabularies`, method: 'GET', signal
    },
      );
    }
  



export const getListVocabulariesApiV1VocabulariesGetQueryKey = () => {
    return [
    `/api/v1/vocabularies`
    ] as const;
    }

    
export const getListVocabulariesApiV1VocabulariesGetQueryOptions = <TData = Awaited<ReturnType<typeof listVocabulariesApiV1VocabulariesGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVocabulariesApiV1VocabulariesGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListVocabulariesApiV1VocabulariesGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listVocabulariesApiV1VocabulariesGet>>> = ({ signal }) => listVocabulariesApiV1VocabulariesGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listVocabulariesApiV1VocabulariesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListVocabulariesApiV1VocabulariesGetQueryResult = NonNullable<Awaited<ReturnType<typeof listVocabulariesApiV1VocabulariesGet>>>
export type ListVocabulariesApiV1VocabulariesGetQueryError = unknown


export function useListVocabulariesApiV1VocabulariesGet<TData = Awaited<ReturnType<typeof listVocabulariesApiV1VocabulariesGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVocabulariesApiV1VocabulariesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listVocabulariesApiV1VocabulariesGet>>,
          TError,
          Awaited<ReturnType<typeof listVocabulariesApiV1VocabulariesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListVocabulariesApiV1VocabulariesGet<TData = Awaited<ReturnType<typeof listVocabulariesApiV1VocabulariesGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVocabulariesApiV1VocabulariesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listVocabulariesApiV1VocabulariesGet>>,
          TError,
          Awaited<ReturnType<typeof listVocabulariesApiV1VocabulariesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListVocabulariesApiV1VocabulariesGet<TData = Awaited<ReturnType<typeof listVocabulariesApiV1VocabulariesGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVocabulariesApiV1VocabulariesGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Vocabularies
 */

export function useListVocabulariesApiV1VocabulariesGet<TData = Awaited<ReturnType<typeof listVocabulariesApiV1VocabulariesGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVocabulariesApiV1VocabulariesGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListVocabulariesApiV1VocabulariesGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create Vocabulary
 */
export const createVocabularyApiV1VocabulariesPost = (
    createVocabularyBody: CreateVocabularyBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<VocabularyResponse>(
      {url: `/api/v1/vocabularies`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createVocabularyBody, signal
    },
      );
    }
  


export const getCreateVocabularyApiV1VocabulariesPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createVocabularyApiV1VocabulariesPost>>, TError,{data: CreateVocabularyBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createVocabularyApiV1VocabulariesPost>>, TError,{data: CreateVocabularyBody}, TContext> => {

const mutationKey = ['createVocabularyApiV1VocabulariesPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createVocabularyApiV1VocabulariesPost>>, {data: CreateVocabularyBody}> = (props) => {
          const {data} = props ?? {};

          return  createVocabularyApiV1VocabulariesPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateVocabularyApiV1VocabulariesPostMutationResult = NonNullable<Awaited<ReturnType<typeof createVocabularyApiV1VocabulariesPost>>>
    export type CreateVocabularyApiV1VocabulariesPostMutationBody = CreateVocabularyBody
    export type CreateVocabularyApiV1VocabulariesPostMutationError = HTTPValidationError

    /**
 * @summary Create Vocabulary
 */
export const useCreateVocabularyApiV1VocabulariesPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createVocabularyApiV1VocabulariesPost>>, TError,{data: CreateVocabularyBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createVocabularyApiV1VocabulariesPost>>,
        TError,
        {data: CreateVocabularyBody},
        TContext
      > => {

      const mutationOptions = getCreateVocabularyApiV1VocabulariesPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Update Vocabulary
 */
export const updateVocabularyApiV1VocabulariesVocabIdPatch = (
    vocabId: string,
    updateVocabularyBody: UpdateVocabularyBody,
 ) => {
      
      
      return customInstance<VocabularyResponse>(
      {url: `/api/v1/vocabularies/${vocabId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateVocabularyBody
    },
      );
    }
  


export const getUpdateVocabularyApiV1VocabulariesVocabIdPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateVocabularyApiV1VocabulariesVocabIdPatch>>, TError,{vocabId: string;data: UpdateVocabularyBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateVocabularyApiV1VocabulariesVocabIdPatch>>, TError,{vocabId: string;data: UpdateVocabularyBody}, TContext> => {

const mutationKey = ['updateVocabularyApiV1VocabulariesVocabIdPatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateVocabularyApiV1VocabulariesVocabIdPatch>>, {vocabId: string;data: UpdateVocabularyBody}> = (props) => {
          const {vocabId,data} = props ?? {};

          return  updateVocabularyApiV1VocabulariesVocabIdPatch(vocabId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateVocabularyApiV1VocabulariesVocabIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateVocabularyApiV1VocabulariesVocabIdPatch>>>
    export type UpdateVocabularyApiV1VocabulariesVocabIdPatchMutationBody = UpdateVocabularyBody
    export type UpdateVocabularyApiV1VocabulariesVocabIdPatchMutationError = HTTPValidationError

    /**
 * @summary Update Vocabulary
 */
export const useUpdateVocabularyApiV1VocabulariesVocabIdPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateVocabularyApiV1VocabulariesVocabIdPatch>>, TError,{vocabId: string;data: UpdateVocabularyBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateVocabularyApiV1VocabulariesVocabIdPatch>>,
        TError,
        {vocabId: string;data: UpdateVocabularyBody},
        TContext
      > => {

      const mutationOptions = getUpdateVocabularyApiV1VocabulariesVocabIdPatchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Delete Vocabulary
 */
export const deleteVocabularyApiV1VocabulariesVocabIdDelete = (
    vocabId: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/vocabularies/${vocabId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteVocabularyApiV1VocabulariesVocabIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteVocabularyApiV1VocabulariesVocabIdDelete>>, TError,{vocabId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteVocabularyApiV1VocabulariesVocabIdDelete>>, TError,{vocabId: string}, TContext> => {

const mutationKey = ['deleteVocabularyApiV1VocabulariesVocabIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteVocabularyApiV1VocabulariesVocabIdDelete>>, {vocabId: string}> = (props) => {
          const {vocabId} = props ?? {};

          return  deleteVocabularyApiV1VocabulariesVocabIdDelete(vocabId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteVocabularyApiV1VocabulariesVocabIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteVocabularyApiV1VocabulariesVocabIdDelete>>>
    
    export type DeleteVocabularyApiV1VocabulariesVocabIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Vocabulary
 */
export const useDeleteVocabularyApiV1VocabulariesVocabIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteVocabularyApiV1VocabulariesVocabIdDelete>>, TError,{vocabId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteVocabularyApiV1VocabulariesVocabIdDelete>>,
        TError,
        {vocabId: string},
        TContext
      > => {

      const mutationOptions = getDeleteVocabularyApiV1VocabulariesVocabIdDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    